"""Exercise the added UI using fictional records only. No external requests."""
import json
import os
from pathlib import Path
import shutil
import subprocess
from playwright.sync_api import sync_playwright
ROOT = Path(__file__).resolve().parents[1]
fixture=json.loads(subprocess.check_output(['node','-e',"console.log(JSON.stringify(require('./src/portfolio_engine.js').fixture()))"],cwd=ROOT,text=True,encoding='utf-8'))
results=[]
def check(name,condition):
    if not condition: raise AssertionError(name)
    results.append('PASS '+name)
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,executable_path=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium') or shutil.which('chromium-browser'),args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1500,'height':1100})
    page.set_default_timeout(5000)
    errors=[];requests=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('request',lambda r:requests.append(r.url))
    page.on('dialog',lambda d:d.accept())
    page.set_content((ROOT/'INVESTMENT_Dashboard.html').read_text(encoding='utf-8'),wait_until='load')
    page.get_by_role('tab',name='04 보유종목 점검').click()
    check('new holdings tab is available',page.locator('#panel-holdings').is_visible())
    check('empty state does not invent holdings','실제 보유종목은 포함되어 있지 않습니다' in page.locator('#pHoldBody').inner_text())
    page.locator('#pFixture').click()
    check('fictional mode label visible','가상 테스트' in page.locator('#pMode').inner_text())
    check('four fictional holdings displayed',page.locator('#pHoldBody tr').count()==4)
    check('company hold and overweight are independent','보유 검토' in page.locator('#pHoldBody tr').first.inner_text() and '상한 초과' in page.locator('#pHoldBody tr').first.inner_text())
    check('unknown input displays wait','판단 보류' in page.locator('#pHoldBody').inner_text())
    check('fictional input does not contaminate original screen',page.locator('#universeStat').inner_text()=='—')
    page.locator('#pHoldBody [data-review-detail="990001"]').click()
    check('support and counter evidence visible','반대 근거' in page.locator('#pDetail').inner_text() and '판단을 바꿀 조건' in page.locator('#pDetail').inner_text())
    check('fixture sources are not real external links',page.locator('#pDetail a').count()==0)
    page.evaluate('window.scrollTo(0,0)')
    page.locator('#toast').wait_for(state='hidden')
    page.screenshot(path=str(ROOT/'preview_holdings_desktop.png'),full_page=True)
    page.get_by_role('tab',name='05 포트폴리오').click()
    check('portfolio tab available',page.locator('#panel-portfolio').is_visible())
    page.locator('#pGenerate').click()
    check('unchecked configuration blocks proposal',page.locator('#pProposalBody tr').count()==0 and '설정' in page.locator('#pProposalNote').inner_text())
    page.locator('#pConfirm').check();page.locator('#pGenerate').click()
    check('max five companies enforced in UI',page.locator('#pProposalBody tr').count()==5)
    check('cash buffer displayed','20 %' in page.locator('#pCashLabel').inner_text())
    check('scenario explicitly not a loss guarantee','실제 손실 상한이 아닙니다' in page.locator('#pStress').inner_text())
    check('excluded holdings not automatic sell','자동 매도 의견이 아닙니다' in page.locator('#pUnselected').inner_text())
    page.screenshot(path=str(ROOT/'preview_portfolio_desktop.png'),full_page=True)
    with page.expect_download() as dl:page.locator('#pExportReport').click()
    check('review markdown exports',dl.value.suggested_filename.endswith('.md'))
    dl.value.save_as(str(ROOT/'tests/fixture_report.md'))
    check('export identifies fictional data','가상 테스트' in (ROOT/'tests/fixture_report.md').read_text(encoding='utf-8'))
    page.locator('#pLossLimit').fill('10')
    check('changing settings invalidates old proposal',page.locator('#pProposalBody tr').count()==0 and not page.locator('#pConfirm').is_checked())
    page.locator('#pConfirm').check();page.locator('#pGenerate').click()
    check('scenario limit reduces equity','66.7 %' in page.locator('#pCashLabel').inner_text())
    page.set_viewport_size({'width':390,'height':844})
    check('mobile no document overflow',page.evaluate('document.documentElement.scrollWidth <= window.innerWidth + 1'))
    page.screenshot(path=str(ROOT/'preview_portfolio_mobile.png'),full_page=True)
    page.set_viewport_size({'width':1500,'height':1100})
    page.get_by_role('tab',name='04 보유종목 점검').click()
    invalid=json.loads(json.dumps(fixture));invalid['holdings'].append(invalid['holdings'][0])
    page.locator('#pFile').set_input_files({'name':'bad.json','mimeType':'application/json','buffer':json.dumps(invalid).encode()})
    page.wait_for_timeout(100)
    check('invalid import preserves existing state',page.locator('#pHoldBody tr').count()==4 and '실패' in page.locator('#toast').inner_text())
    xss=json.loads(json.dumps(fixture));xss['research'][0]['name']='<img src=x onerror="window.INJECTED=true">'
    page.locator('#pFile').set_input_files({'name':'escape.json','mimeType':'application/json','buffer':json.dumps(xss).encode()})
    page.wait_for_timeout(100)
    check('user text safely escaped',page.locator('#pHoldBody img').count()==0 and not page.evaluate('Boolean(window.INJECTED)'))
    page.locator('#pCode').fill('000001');page.locator('#pQty').fill('2');page.locator('#pCost').fill('1000');page.locator('#pSaveHolding').click()
    check('leading zero manual code survives','000001' in page.locator('#pHoldBody').inner_text())
    check('missing researcher keeps holding in wait',page.locator('#pHoldBody tr').count()==5 and '판단 보류' in page.locator('#pHoldBody tr').last.inner_text())
    check('partial valuations do not create total',page.locator('#pValue').inner_text()=='—')
    page.locator('#pLoadEditor').click()
    check('JSON editor populated','holdings-portfolio-0.1' in page.locator('#pJsonEditor').input_value())
    page.locator('#pClear').click()
    check('clear removes new holdings',page.locator('#pHoldBody tr').count()==1 and '실제 보유종목은 포함되어 있지 않습니다' in page.locator('#pHoldBody').inner_text())
    check('clear removes editor copy',page.locator('#pJsonEditor').input_value()=='')
    check('no JS errors',not errors)
    check('no network calls',not requests)
    browser.close()
print('\n'.join(results))
print(f'{len(results)} portfolio UI checks passed.')
