'use strict';
const assert=require('assert');
const market=require('../src/market_explanation_ui.js');
const changes=require('../src/trend_changes_ui.js');
const tf=require('../src/trend_following_ui.js');
const capText=changes.renderChanges({as_of:'2026-10-06',default_cap_eok:1500,changes:{status:'no_prior'}});
assert(capText.includes('시총 1,500억원 이상')&&!capText.includes('1,000억원'),'default cap follows the data, not a fixed phrase');
const noPrior=changes.renderChanges({as_of:'2026-10-06',changes:{status:'no_prior'}});
assert(noPrior.includes('이전 체크포인트 없음'));assert(noPrior.includes('비교 대기'));assert(noPrior.includes('전일 사실을 추정하지'));
const html=changes.renderChanges({as_of:'2026-10-06',changes:{status:'ready',prior_as_of:'2026-09-29',new_qualified:[{code:'A',name:'<script>',rs:70}],breakouts:[{code:'B',name:'b',volume_confirmed:false,newly_observed:true}]}});
assert(html.includes('2026-09-29'));assert(html.includes('&lt;script&gt;'));assert(!html.includes('<script>'));assert(html.includes('거래량 보강/확인 필요'));
const mh=market.render({markets:[{market:'<x>',index:{label:'상승 정렬'},breadth:{above:{200:{count:2,eligible:10,pct:20}},population:12,valid:10},volatility:{},explanation:'혼합 신호'}]});
assert(mh.includes('2/10개'));assert(mh.includes('관찰 대상 12개'));assert(mh.includes('지수 방향'));assert(mh.includes('기업 참여'));assert(mh.includes('변동성'));assert(!mh.includes('<x>'));
const r={code:'A',name:'a',market:'KOSPI',ready:true,rs:70,cap_eok:1000,phase:'near',technical:{as_of:'2026-10-06',close:100,sma:{50:90}}};
assert(changes.observation(r,'2026-10-06').qualified);assert(!changes.observation(r,'2026-10-05').ready);
assert(!changes.observation({...r,discovery_allowed:false},'2026-10-06').qualified);
const state={query:'',market:'',industry:'',capMin:1000,rsMin:70,setup:'all',sort:'rs'};
assert.equal(tf.select([r,{...r,code:'B',discovery_allowed:false}],state).length,1);
let memory={},refreshes=0;global.localStorage={getItem:k=>memory[k],setItem:(k,v)=>memory[k]=v};
const ui=changes.create({data:{as_of:'2026-10-06',mode:'fixture',rows:[r]},refresh:()=>refreshes++});
const buttons={};const element={querySelectorAll:selector=>selector==='[data-tf-watch]'?[{dataset:{tfWatch:'A'},set onclick(fn){buttons.watch=fn;}}]:[],querySelector:()=>null};
ui.bind(element);buttons.watch();assert(ui.isWatched(r));ui.checkpoint();ui.checkpoint();
assert.equal(JSON.parse(Object.values(memory)[0]).checkpoints.length,1);
assert(ui.render().includes('수정본 1'));assert(ui.render().includes('직전 저장 2026-10-06'));
assert(!JSON.stringify(memory).includes('technical'));assert(refreshes>=3);
console.log('PASS market axes/denominators/XSS, no-prior labels, default boundaries, watch explicit save/reload compact checkpoint');
