'use strict';
const assert=require('node:assert/strict'),E=require('../src/ebitda_inputs.js');
const cache=new Map();global.localStorage={getItem:k=>cache.get(k)||null,setItem:(k,v)=>cache.set(k,v)};
const row={code:'005930',name:'삼성전자',market:'KOSPI'},other={code:'000660',name:'SK하이닉스',market:'KOSPI'};
const column={period_end:'2026-06-30',values:{ebitda:null,total_borrowings:200},interest_expense_eok:5,cell_notes:{debt_ebitda:'연간 자료 필요'}};
const group={id:'CFS-quarter',basis:'CFS',cadence:'quarter',columns:[column]};
const tables={[row.code]:{groups:[group]},[other.code]:{groups:[group]}};
const make=(options={})=>E.create({dataMode:'user_input',rows:[row,other],tables,...options});
const before=JSON.stringify(tables);let store=make();
for(const text of ['', ' ', '1,2', 'NaN', 'Infinity', '1e6', '=1+2'])assert.throws(()=>E.number(text));
assert.equal(E.number('1,000.25'),1000.25);assert.equal(E.number('-3.5'),-3.5);assert.equal(E.number('0'),0);
assert.equal(E.calculate(-10,20,5),15);assert.throws(()=>E.calculate(1,null,0));assert.throws(()=>E.calculate(1,-1,0));
store.save(row,group,column,{method:'direct',value:100,note:'가상 검사'});
let applied=store.apply(row,tables[row.code]).groups[0].columns[0];
assert.equal(applied.values.ebitda,100);assert.equal(applied.values.ebitda_interest,20);assert.equal(applied.values.debt_ebitda,null);
assert.equal(store.apply(other,tables[other.code]).groups[0].columns[0].values.ebitda,null,'other company does not inherit');
assert.equal(JSON.stringify(tables),before,'source remains intact');
assert.equal(make().find(row,group,column).value,100,'reload restores');
const payload=store.pack();assert.throws(()=>store.import({...payload,data_mode:'fixture'}));assert.throws(()=>store.import({...payload,unit:'원'}));
const lazyTables={},lazyStore=make({tables:lazyTables,lazyTables:true,initial:payload});
assert.equal(lazyStore.pack().entries.length,1,'lazy loading preserves a known company input until its table arrives');
assert.throws(()=>lazyStore.save(row,group,column,{method:'direct',value:120,note:''}),'saving still requires a verified table');
lazyTables[row.code]=tables[row.code];
assert.equal(lazyStore.apply(row,lazyTables[row.code]).groups[0].columns[0].values.ebitda,100,'loaded table restores saved input');
assert.throws(()=>store.import({...payload,entries:[payload.entries[0],payload.entries[0]]}));
assert.equal(store.find(row,group,column).value,100,'invalid import is atomic');
assert.equal(make({rows:[{...row,name:'식별 변경'}]}).pack().entries.length,0,'renamed company held back');
assert.equal(make({tables:{[row.code]:{groups:[{...group,basis:'OFS',id:'OFS-quarter'}]}}}).pack().entries.length,0,'basis mismatch held back');
assert.equal(make({dataMode:'fixture'}).pack().entries.length,0,'fixture mode isolated');
store.save(row,group,column,{method:'operating',value:15,note:'계산 검사',components:{operating_profit:-10,depreciation:20,amortization:5}});
assert.match(store.apply(row,tables[row.code]).groups[0].columns[0].cell_notes.ebitda,/사용자 계산/);
assert.throws(()=>store.save(row,group,column,{method:'operating',value:16,note:'',components:{operating_profit:-10,depreciation:20,amortization:5}}));
store.save(row,group,column,{method:'direct',value:0,note:''});assert.equal(store.apply(row,tables[row.code]).groups[0].columns[0].values.ebitda,0);
store.save(row,group,column,{method:'direct',value:-10,note:''});assert.equal(store.apply(row,tables[row.code]).groups[0].columns[0].values.ebitda_interest,-2);
store.remove(row,group,column);assert.equal(store.apply(row,tables[row.code]).groups[0].columns[0].values.ebitda,null);
const annual={...group,id:'CFS-annual',cadence:'annual'};const annualStore=make({tables:{[row.code]:{groups:[annual]}}});
annualStore.save(row,annual,column,{method:'direct',value:100,note:''});assert.equal(annualStore.apply(row,{groups:[annual]}).groups[0].columns[0].values.debt_ebitda,2);
annualStore.save(row,annual,column,{method:'direct',value:-10,note:''});assert.equal(annualStore.apply(row,{groups:[annual]}).groups[0].columns[0].values.debt_ebitda,null);
const noInterest={...column,interest_expense_eok:null};assert.equal(annualStore.apply(row,{groups:[{...annual,columns:[noInterest]}]}).groups[0].columns[0].values.ebitda_interest,null);
global.localStorage.setItem=()=>{throw Error('blocked');};annualStore.save(row,annual,column,{method:'direct',value:20,note:''});
assert.match(annualStore.storageNote(),/파일 저장/);assert.equal(annualStore.pack().entries[0].value,20);
console.log('PASS EBITDA: parsing, calculation, period identity, modes, restore, atomic import, source preservation, ratios, zero/negative, storage failure');
