'use strict';
const assert=require('node:assert/strict');
const P=require('../src/portfolio_engine.js');
let count=0;
function test(name,fn){fn();console.log('PASS '+name);count++;}
const f=()=>P.fixture();
const cfg=(extra={})=>({...P.DEFAULT,policyConfirmed:true,stressLossLimitPct:25,...extra});
const held=(x)=>P.reviewHoldings(x,cfg()).rows;
const decision=(x,i=0)=>P.companyReview(x.research[i],x.as_of,P.cleanPolicy(cfg()));
test('fixture validates',()=>assert.equal(P.validate(f()).mode,'fixture'));
test('zero cash is valid',()=>{const x=f();x.cash_krw=0;P.validate(x);});
test('null cash stays incomplete',()=>{const x=f();x.cash_krw=null;assert.equal(P.reviewHoldings(x,cfg()).book.complete,false);});
test('invalid calendar date rejected',()=>{const x=f();x.as_of='2026-02-30';assert.throws(()=>P.validate(x));});
test('negative cash rejected',()=>{const x=f();x.cash_krw=-1;assert.throws(()=>P.validate(x));});
test('fractional holdings rejected',()=>{const x=f();x.holdings[0].quantity=1.1;assert.throws(()=>P.validate(x));});
test('negative quantity rejected',()=>{const x=f();x.holdings[0].quantity=-1;assert.throws(()=>P.validate(x));});
test('duplicate holdings rejected',()=>{const x=f();x.holdings.push(x.holdings[0]);assert.throws(()=>P.validate(x));});
test('duplicate research rejected',()=>{const x=f();x.research.push(x.research[0]);assert.throws(()=>P.validate(x));});
test('numeric stock code rejected',()=>{const x=f();x.holdings[0].code=990001;assert.throws(()=>P.validate(x));});
test('unknown data modes rejected',()=>{const x=f();x.mode='live';assert.throws(()=>P.validate(x));});
test('unsafe evidence URL rejected',()=>{const x=f();x.research[0].evidence[0].url='javascript:alert(1)';assert.throws(()=>P.validate(x));});
test('source embedded credentials rejected',()=>{const x=f();x.research[0].evidence[0].url='https://synthetic:synthetic@example.invalid';assert.throws(()=>P.validate(x));});
test('zero price rejected, not cheap',()=>{const x=f();x.research[0].price_krw=0;assert.throws(()=>P.validate(x));});
test('unknown analysis enum rejected',()=>{const x=f();x.research[0].review.finance='great';assert.throws(()=>P.validate(x));});
test('intact thesis yields hold review',()=>assert.equal(decision(f()).opinion,'HOLD'));
test('broken thesis yields sell review',()=>assert.equal(decision(f(),5).opinion,'SELL'));
test('stretched valuation yields reduce review',()=>assert.equal(decision(f(),6).opinion,'REDUCE'));
test('unknown thesis yields wait, not hold',()=>assert.equal(decision(f(),7).opinion,'WAIT'));
test('weakened business yields re-review',()=>{const x=f();x.research[0].review.business='deteriorating';assert.equal(decision(x).opinion,'REVIEW');});
test('unresolved risk yields re-review',()=>{const x=f();x.research[0].review.material_risk='unresolved';assert.equal(decision(x).opinion,'REVIEW');});
test('unreviewed source blocks opinion',()=>{const x=f();x.research[0].evidence[0].reviewed=false;assert.equal(decision(x).opinion,'WAIT');});
test('future evidence does not leak into past',()=>{const x=f();x.research[0].evidence[0].available_on='2026-10-01';assert.equal(decision(x).opinion,'WAIT');});
test('future price blocks hold',()=>{const x=f();x.research[0].price_date='2026-10-01';assert.equal(decision(x).opinion,'WAIT');});
test('old price blocks hold',()=>{const x=f();x.research[0].price_date='2026-09-01';assert.equal(decision(x).opinion,'WAIT');});
test('old research blocks hold',()=>{const x=f();x.research[0].review.reviewed_on='2025-01-01';assert.equal(decision(x).opinion,'WAIT');});
test('missing counter-evidence blocks hold',()=>{const x=f();x.research[0].review.negatives=[];assert.equal(decision(x).opinion,'WAIT');});
test('verified critical event not hidden by missing price',()=>{const x=f();x.research[0].review.finance='critical';x.research[0].price_krw=null;x.research[0].review.valuation='unknown';assert.equal(decision(x).opinion,'SELL');assert.ok(decision(x).blockers.length);});
test('known adverse event survives missing positive section',()=>{const x=f();x.research[0].review.thesis='broken';x.research[0].review.positives=[];assert.equal(decision(x).opinion,'SELL');});
test('unknown source still blocks adverse conclusion',()=>{const x=f();x.research[0].review.thesis='broken';x.research[0].evidence=[];assert.equal(decision(x).opinion,'WAIT');});
test('average cost affects P&L, not thesis opinion',()=>{const x=f(),before=held(x)[0];x.holdings[0].avg_cost_krw=1000000;const after=held(x)[0];assert.equal(before.opinion,after.opinion);assert.notEqual(before.pnl_pct,after.pnl_pct);});
test('zero cost suppresses percent return',()=>{const x=f();x.holdings[0].avg_cost_krw=0;assert.equal(held(x)[0].pnl_pct,null);});
test('overweight is independent of company hold',()=>{const a=held(f())[0];assert.equal(a.opinion,'HOLD');assert.equal(a.overweight,true);});
test('missing one price prevents partial 100% renormalisation',()=>{const x=f();x.research[0].price_krw=null;const h=P.reviewHoldings(x,cfg());assert.equal(h.book.total_krw,null);assert.ok(h.rows.every(r=>r.weight_pct===null));});
test('missing researcher does not drop held stock',()=>{const x=f();x.research=x.research.filter(r=>r.code!=='990001');const h=held(x);assert.equal(h.length,4);assert.equal(h[0].opinion,'WAIT');});
test('unsafe total valuation not emitted',()=>{const x=f();x.holdings[0].quantity=Number.MAX_SAFE_INTEGER;assert.equal(P.reviewHoldings(x,cfg()).book.total_krw,null);});
test('settings not confirmed block allocation',()=>assert.equal(P.propose(f()).status,'SETTINGS_REQUIRED'));
test('missing stress loss input blocks allocation',()=>assert.equal(P.propose(f(),{policyConfirmed:true}).status,'SETTINGS_REQUIRED'));
test('more than five companies rejected',()=>assert.throws(()=>P.propose(f(),cfg({maxCompanies:6}))));
test('zero company count rejected',()=>assert.throws(()=>P.propose(f(),cfg({maxCompanies:0}))));
test('negative cap rejected',()=>assert.throws(()=>P.propose(f(),cfg({companyCapPct:-5}))));
test('invalid stress scenario rejected',()=>assert.throws(()=>P.propose(f(),cfg({stressShockPct:0}))));
test('empty research is not a cash recommendation',()=>{const x=P.empty('2026-09-25');const a=P.propose(x,cfg());assert.equal(a.status,'DATA_REQUIRED');assert.equal(a.cash_pct,null);});
test('five companies plus cash total 100',()=>{const a=P.propose(f(),cfg());assert.equal(a.items.length,5);assert.equal(a.cash_pct,20);assert.equal(a.items.reduce((s,r)=>s+r.weight_pct,0)+a.cash_pct,100);});
test('two eligible companies do not fill all equity slots',()=>{const x=f();x.research=x.research.slice(0,2);const a=P.propose(x,cfg());assert.equal(a.items.length,2);assert.equal(a.cash_pct,68);});
test('no eligible company is legitimate cash-only model',()=>{const x=f();x.research.forEach(r=>r.review.thesis='broken');const a=P.propose(x,cfg());assert.equal(a.items.length,0);assert.equal(a.cash_pct,100);});
test('sector cap enforced',()=>{const x=f();x.research.forEach(r=>r.sector='single');const a=P.propose(x,cfg());assert.ok(a.items.reduce((s,r)=>s+r.weight_pct,0)<=40);});
test('common risk group cap enforced across sectors',()=>{const x=f();x.research.forEach(r=>r.risk_group='shared-demand');const a=P.propose(x,cfg());assert.ok(a.items.reduce((s,r)=>s+r.weight_pct,0)<=40);});
test('issuer rather than ticker count deduplicated',()=>{const x=f();x.research[1].issuer_id=x.research[0].issuer_id;const a=P.propose(x,cfg());assert.equal(new Set(a.items.map(r=>r.issuer_id)).size,a.items.length);assert.equal(a.items.length,4);});
test('missing sector excluded not assumed diversified',()=>{const x=f();x.research[0].sector=null;assert.ok(!P.propose(x,cfg()).items.some(r=>r.code==='990001'));});
test('missing risk group excluded',()=>{const x=f();x.research[0].risk_group=null;assert.ok(!P.propose(x,cfg()).items.some(r=>r.code==='990001'));});
test('unsupported security not recommended',()=>{const x=f();x.research[0].security_type='preferred';assert.ok(!P.propose(x,cfg()).items.some(r=>r.code==='990001'));});
test('scenario loss input reduces stock allocation',()=>{const a=P.propose(f(),cfg({stressLossLimitPct:10}));assert.ok(P.stress(a.items,-30)>=-10);assert.ok(a.cash_pct>=66.66);});
test('smaller sector cap adjusts fixed slot',()=>{const a=P.propose(f(),cfg({sectorCapPct:10}));assert.ok(a.items.length>0);assert.ok(Object.values(a.sector_weights).every(v=>v<=10));});
test('min cash 100 permits cash-only result',()=>{const a=P.propose(f(),cfg({minCashPct:100}));assert.equal(a.cash_pct,100);assert.equal(a.items.length,0);});
test('deterministic under input reorder',()=>{const x=f(),a=P.propose(x,cfg());x.research.reverse();const b=P.propose(x,cfg());assert.deepEqual(a.items.map(r=>[r.code,r.weight_pct]),b.items.map(r=>[r.code,r.weight_pct]));});
test('input and holdings not mutated',()=>{const x=f(),before=JSON.stringify(x);P.propose(x,cfg());P.reviewHoldings(x,cfg());assert.equal(JSON.stringify(x),before);});
test('unselected holding not silently deleted',()=>{const a=P.propose(f(),cfg());assert.ok(a.unselected_holdings.includes('990006'));assert.equal(f().holdings.length,4);});
test('same issuer holdings aggregated for company cap',()=>{const x=f();x.research[5].issuer_id=x.research[0].issuer_id;const h=held(x);assert.ok(h[0].issuer_weight_pct>h[0].weight_pct);assert.equal(h[1].issuer_weight_pct,h[0].issuer_weight_pct);});
test('stress is a weighted arithmetic scenario',()=>assert.equal(P.stress([{weight_pct:20},{weight_pct:30}],-40),-20));
test('stress rejects undefined or invalid inputs',()=>assert.throws(()=>P.stress([],5)));
test('review cannot precede source availability',()=>{const x=f();x.research[0].review.reviewed_on='2026-09-24';assert.equal(decision(x).opinion,'WAIT');});
test('all unknown candidates not converted to cash-only opinion',()=>{const x=f();x.research.forEach(r=>r.review.thesis='unknown');const a=P.propose(x,cfg());assert.equal(a.status,'DATA_REQUIRED');assert.equal(a.cash_pct,null);});
test('all missing sectors require data instead of cash opinion',()=>{const x=f();x.research=x.research.slice(0,2);x.research.forEach(r=>r.sector=null);const a=P.propose(x,cfg());assert.equal(a.status,'DATA_REQUIRED');assert.equal(a.cash_pct,null);});
test('mixed adverse and unknown zero-candidate outcome stays incomplete',()=>{const x=f();x.research=x.research.slice(5);x.research[1].review.thesis='broken';const a=P.propose(x,cfg());assert.equal(a.cash_pct,null);});

test('manual unknown company computes book without inventing research',()=>{
 const x=P.empty('2026-10-01'),before=JSON.stringify(x);
 const y=P.saveHolding(x,{code:'000001',quantity:10,avg_cost_krw:10000},200000,{price:12000,date:'2026-10-01',label:'가상 입력',name:'가상 기업'});
 const r=P.reviewHoldings(y);assert.equal(r.book.total_krw,320000);assert.equal(r.rows[0].cost_krw,100000);
 assert.equal(r.rows[0].value_krw,120000);assert.equal(r.rows[0].pnl_krw,20000);assert.ok(Math.abs(r.rows[0].pnl_pct-20)<1e-9);
 assert.equal(r.rows[0].weight_pct,37.5);assert.equal(r.rows[0].opinion,'WAIT');assert.equal(y.research[0].market,'unknown');
 assert.deepEqual(y.research[0].evidence,[]);assert.equal(JSON.stringify(x),before);
});
test('cash zero works while blank cash preserves unknown denominator',()=>{
 const h={code:'000001',quantity:2,avg_cost_krw:0},q={price:100,date:'2026-10-01',label:'가상 입력'};
 let x=P.saveHolding(P.empty('2026-10-01'),h,null,q),r=P.reviewHoldings(x);
 assert.equal(r.rows[0].pnl_krw,200);assert.equal(r.rows[0].pnl_pct,null);assert.equal(r.book.total_krw,null);assert.equal(r.rows[0].weight_pct,null);
 x=P.saveHolding(x,h,0);r=P.reviewHoldings(x);assert.equal(r.book.total_krw,200);assert.equal(r.rows[0].weight_pct,100);
});
test('invalid manual quote fails atomically',()=>{
 const x=P.empty('2026-10-01'),before=JSON.stringify(x),h={code:'000001',quantity:2,avg_cost_krw:100},q={price:120,date:'2026-10-01',label:'가상 입력'};
 for(const patch of [{price:0},{price:-1},{price:Infinity},{date:'2026-10-02'},{date:'2026-02-30'},{label:''}])assert.throws(()=>P.saveHolding(x,h,0,{...q,...patch}));
 assert.throws(()=>P.saveHolding(x,{...h,quantity:0},0,q));assert.throws(()=>P.saveHolding(x,h,-1,q));assert.equal(JSON.stringify(x),before);
});
test('manual quote does not overwrite identity or reviewed thesis',()=>{
 const x=f(),r=x.research[0],before=P.clone(r);
 const y=P.saveHolding(x,{code:r.code,quantity:2,avg_cost_krw:100},0,{price:120,date:x.as_of,label:'가상 입력',name:'wrong identity'});
 assert.equal(y.research[0].name,before.name);assert.deepEqual(y.research[0].review,before.review);assert.deepEqual(y.research[0].evidence,before.evidence);
});
test('newer market quote replaces manual while equal date preserves explicit input',()=>{
 const market=f();market.mode='user_input';market.holdings=[];
 const h={code:market.research[0].code,quantity:2,avg_cost_krw:100};
 let x=P.saveHolding(market,h,0,{price:120,date:market.as_of,label:'가상 입력'});
 assert.equal(P.attachMarket(x,market).research[0].price_krw,120);
 market.as_of='2026-09-26';market.research[0].price_date=market.as_of;
 assert.equal(P.attachMarket(x,market).research[0].price_krw,market.research[0].price_krw);
});
test('manual source rejects unsafe optional URL and stale quote remains blocked',()=>{
 let x=P.saveHolding(P.empty('2026-10-01'),{code:'000001',quantity:1,avg_cost_krw:10},0,{price:12,date:'2026-09-23',label:'가상 입력'});
 assert.equal(P.reviewHoldings(x).book.total_krw,null);assert.equal(P.reviewHoldings(x,{maxPriceAgeDays:10}).book.total_krw,12);
 x.research[0].price_source.url='javascript:alert(1)';assert.throws(()=>P.validate(x));
});
console.log(count+' portfolio tests passed.');
