'use strict';
const assert=require('assert/strict'),P=require('../src/portfolio_engine.js'),H=require('../src/holdings_sync.js');
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS '+name);};
const state=()=>{let x=P.fixture();x.mode='user_input';return H.pack(x,P.DEFAULT);};
test('initial save restores exact user input',()=>{const a=state();assert.deepEqual(H.merge(null,a,null).state,a);});
test('initial pull does not invent state',()=>{const a=state();assert.deepEqual(H.merge(null,null,a).state,a);});
test('fixture cannot enter private sync',()=>assert.throws(()=>H.pack(P.fixture(),P.DEFAULT)));
test('unrecognized fields cannot enter stored input',()=>{const x=state();x.input.account_secret='synthetic-must-not-store';assert.throws(()=>H.validate(x));const y=state();y.policy.unrecognized='synthetic';assert.throws(()=>H.validate(y));});
test('independent company edits merge without losing either',()=>{const b=state(),l=P.clone(b),r=P.clone(b);l.input.holdings[0].quantity=42;r.input.holdings[1].avg_cost_krw=123;
 const m=H.merge(b,l,r);assert.equal(m.conflicts.length,0);assert.equal(m.state.input.holdings[0].quantity,42);assert.equal(m.state.input.holdings[1].avg_cost_krw,123);});
test('same holding different fields merge',()=>{const b=state(),l=P.clone(b),r=P.clone(b);l.input.holdings[0].quantity=42;r.input.holdings[0].avg_cost_krw=123;
 const m=H.merge(b,l,r);assert.equal(m.conflicts.length,0);assert.equal(m.state.input.holdings[0].quantity,42);assert.equal(m.state.input.holdings[0].avg_cost_krw,123);});
test('same field conflicting quantity is explicit',()=>{const b=state(),l=P.clone(b),r=P.clone(b);l.input.holdings[0].quantity=42;r.input.holdings[0].quantity=43;
 const m=H.merge(b,l,r);assert.equal(m.conflicts.length,1);assert.ok(m.conflicts[0].path.includes('990001/quantity'));
 assert.equal(H.merge(b,l,r,'local').state.input.holdings[0].quantity,42);assert.equal(H.merge(b,l,r,'remote').state.input.holdings[0].quantity,43);});
test('deletion on one PC preserves changes to another holding',()=>{const b=state(),l=P.clone(b),r=P.clone(b);l.input.holdings.shift();r.input.holdings[1].quantity=12;
 const m=H.merge(b,l,r);assert.equal(m.conflicts.length,0);assert.equal(m.state.input.holdings.length,3);assert.equal(m.state.input.holdings[0].quantity,12);});
test('deletion versus editing never silently loses a row',()=>{const b=state(),l=P.clone(b),r=P.clone(b);l.input.holdings.shift();r.input.holdings[0].quantity=12;
 const m=H.merge(b,l,r);assert.equal(m.conflicts.length,1);assert.equal(H.merge(b,l,r,'remote').state.input.holdings[0].quantity,12);});
test('prices and identity remain coherent atomic records',()=>{const b=state(),l=P.clone(b),r=P.clone(b);l.input.research[0].price_krw=12;r.input.research[0].price_date='2026-09-24';
 const m=H.merge(b,l,r);assert.equal(m.conflicts.length,1);assert.equal(H.merge(b,l,r,'remote').state.input.research[0].price_krw,b.input.research[0].price_krw);});
test('cash zero distinct from missing and from conflicting edits',()=>{const b=state(),l=P.clone(b),r=P.clone(b);l.input.cash_krw=0;r.input.cash_krw=null;assert.equal(H.merge(b,l,r).conflicts.length,1);});
test('policy settings merge separately',()=>{const b=state(),l=P.clone(b),r=P.clone(b);l.policy.maxPriceAgeDays=10;r.policy.minCashPct=30;const m=H.merge(b,l,r);assert.equal(m.conflicts.length,0);assert.equal(m.state.policy.maxPriceAgeDays,10);assert.equal(m.state.policy.minCashPct,30);});
test('metadata changes do not masquerade as user edits',()=>{const b=state(),l=P.clone(b),r=P.clone(b);l.input.as_of='2026-10-01';r.input.snapshot_id='new-snapshot';r.input.research[0].pending_events=[];assert.equal(H.merge(b,l,r).conflicts.length,0);});
test('edits during in-flight write are rebased onto returned remote',()=>{const sent=state(),newer=P.clone(sent),reply=P.clone(sent);newer.input.holdings[0].quantity=99;reply.input.holdings[1].quantity=33;
 const m=H.merge(sent,newer,reply);assert.equal(m.conflicts.length,0);assert.equal(m.state.input.holdings[0].quantity,99);assert.equal(m.state.input.holdings[1].quantity,33);});
test('merge is pure and reordered collections deterministic',()=>{const b=state(),l=P.clone(b),r=P.clone(b),before=JSON.stringify([b,l,r]);l.input.holdings[0].quantity=99;r.input.holdings.reverse();const copy=JSON.stringify([b,l,r]);H.merge(b,l,r);assert.equal(JSON.stringify([b,l,r]),copy);assert.ok(before);});
test('two initial PCs add different companies without erasing',()=>{const l=state(),r=state();l.input.holdings=l.input.holdings.slice(0,1);r.input.holdings=r.input.holdings.slice(1,2);l.input.research=[];r.input.research=[];const m=H.merge(null,l,r);assert.equal(m.conflicts.length,0);assert.equal(m.state.input.holdings.length,2);});
test('pending review events survive synchronization and still block ready status',()=>{const b=state();b.input.research[0].pending_events=[{id:'pending-synthetic',title:'가상 재검토 이벤트',url:'https://example.invalid/event',published_on:'2026-09-25'}];
 const l=P.clone(b),r=P.clone(b);l.input.holdings[0].quantity=41;r.input.cash_krw=300000;const m=H.merge(b,l,r);
 assert.equal(m.state.input.research[0].pending_events.length,1);assert.equal(P.reviewHoldings(m.state.input).rows[0].opinion,'WAIT');});
console.log(count+' holdings sync tests passed.');
