'use strict';
const assert=require('node:assert/strict'), E=require('../src/discovery_engine.js');
const rows=Array.from({length:40},(_,i)=>({code:String(900000+i),name:'기업 '+i,market:'KOSPI',industry:'산업A',security_type:'ordinary',analysis_profile:'nonfinancial',metrics:{roe_pct:i,operating_margin_pct:i/2,per:i===0?null:10,pbr:1,market_cap_eok:100}}));
const research={rows:Object.fromEntries(rows.map(r=>[r.code,{fundamental:{period:'2026-H1',basis:'CFS',metrics:r.metrics},technical:{status:'pass',gap_to_52w_high_pct:-4}}]))};
assert.equal(E.filter(rows,{roeMin:'30'},research).length,10,'filter all companies, not first 30');
assert.equal(E.filter(rows,{roeMin:'39',perMax:'10'},research)[0].code,'900039');
assert.equal(E.filter(rows,{perMax:'12'},research).length,39,'missing valuation excluded');
assert.equal(E.filter(rows,{roeMin:'bad'},research).length,0,'malformed criterion cannot match');
assert.equal(E.filter(rows,{trend:true,highMax:'3'},research).length,0,'high distance cutoff');
assert.equal(E.filter(rows,{watch:true},research,[rows[3]]).length,1,'watchlist intersect');
const sorted=E.sort(rows,'per','asc');assert.equal(sorted.at(-1).code,'900000','nulls last both directions');
assert.equal(rows[0].code,'900000','sorting cannot mutate original');
assert.equal(E.peers(rows,rows[0],research,'roe_pct').count,39);
assert.equal(E.peers(rows.slice(0,5),rows[0],research,'roe_pct').median,null,'sparse peer sample');
assert.equal(E.peers(rows,rows[0],research,'per').count,0,'ratios require comparable evidence');
const future={rows:{...research.rows,'900000':{fundamental:{metrics:{roe_pct:null}}}}};
assert.equal(E.prepare({companies:rows},future)[0].metrics.roe_pct,null,'unverified period overrides raw value');
assert.equal(E.sectors(rows)[0].cap,4000);
assert.equal(E.sectors(rows)[0].metrics.per.count,39);
const saved={version:1,data_mode:'fixture',companies:[rows[1],{...rows[2],name:'changed'},rows[1]]};
assert.equal(E.restoreWatch(saved,rows,'fixture').skipped,2);
assert.throws(()=>E.restoreWatch(saved,rows,'user_input'),/모드/);
const exported=E.csv(rows,{price_date:'2026-09-23'},research);
assert.equal(exported.split('\r\n').length,41,'all pages exported');
assert.ok(E.csv([{...rows[0],name:'=1+1'}],{},research).includes("'=1+1"),'spreadsheet formula escaped');
assert.ok(E.csv([{...rows[0],name:'  =1+1'}],{},research).includes("'  =1+1"),'leading whitespace formula escaped');
const prepared=E.prepare({companies:rows},{rows:{...research.rows,'900000':{technical:{price_strength:{score:90},rs126_pct:2,rs252_pct:5}}}});
assert.equal(E.filter(prepared,{rsMin:'80'},research).length,1,'price rank lower bound');
const candidate={...rows[0],code:'001234',name:'발굴 후보',security_type:'ordinary_candidate',analysis_profile:'candidate',eligibility:'candidate',legacy_available:false,metric_details:{per:{source:'NAVER 공개 참고',period:null,basis:null,observed_on:'2026-09-29',reason:'원천 기간 미명시'}}};
const candidateResearch={rows:{'001234':{fundamental:{metrics:{roe_pct:14,per:8,pbr:1.2}},technical:{status:'unknown',price_trend_status:'pass',source_note:'NAVER 전일 일별 자료',price_strength:{score:90,status:'ready',venue:'KRX',eligible_count:2000,universe_count:2400,source:'NAVER'}}}}};
assert.equal(E.prepare({companies:[candidate]},candidateResearch).length,0,'candidate cannot enter canonical snapshot');
const discoverySnapshot={meta:{discovery:true,data_mode:'user_input',price_date:'2026-09-29',discovery_note:'종목 분류·원천 기간 확인 필요'},companies:[candidate]};
const candidates=E.prepare(discoverySnapshot,candidateResearch);
assert.equal(candidates.length,1,'candidate enters explicitly separate discovery snapshot');
assert.equal(candidates[0].legacy_available,false);
assert.equal(E.prepare({...discoverySnapshot,companies:[{...candidate,eligibility:'confirmed'}]},candidateResearch).length,0,'candidate gate requires explicit eligibility');
assert.equal(E.filter(candidates,{trend:true},candidateResearch).length,1,'discovery price trend does not imply liquidity confirmation');
assert.equal(E.filter([{...candidates[0],discovery:false}],{trend:true},candidateResearch).length,0,'canonical full trend remains unknown');
const unknownPeers=Array.from({length:6},(_,i)=>({...candidates[0],code:'00200'+i}));
assert.equal(E.peers(unknownPeers,candidates[0],candidateResearch,'per').count,0,'unknown periods cannot support peer comparison');
assert.equal(E.sectors(candidates,candidateResearch)[0].metrics.per.value,null,'unknown periods cannot support sector comparison');
const comparable=unknownPeers.map(r=>({...r,metric_details:{per:{source:'Infomax',period:'2026-H1',basis:'CFS',observed_on:'2026-09-29'}}}));
assert.equal(E.peers(comparable,comparable[0],{},'per').count,5,'known matching metadata enables peers');
assert.equal(E.sectors(comparable,{})[0].metrics.per.value,8);
const discoveryCsv=E.csv(candidates,discoverySnapshot.meta,candidateResearch);
assert.ok(discoveryCsv.includes('per_source')&&discoveryCsv.includes('per_period')&&discoveryCsv.includes('per_basis'));
assert.ok(discoveryCsv.includes('NAVER 공개 참고')&&discoveryCsv.includes('원천 기간 미명시'),'CSV retains per-field evidence');
const vm=require('node:vm'),fs=require('node:fs'),context={DiscoveryEngine:E};
vm.runInNewContext(fs.readFileSync(require.resolve('../src/financial_table_ui.js'),'utf8'),context);
vm.runInNewContext(fs.readFileSync(require.resolve('../src/research_ui.js'),'utf8')+'\nglobalThis.UI=ResearchUI;',context);
vm.runInNewContext(fs.readFileSync(require.resolve('../src/ebitda_inputs.js'),'utf8'),context);
vm.runInNewContext(fs.readFileSync(require.resolve('../src/ebitda_editor.js'),'utf8'),context);
const element={innerHTML:'',querySelector:()=>null,querySelectorAll:()=>[]};
const ui=context.UI.create({element,snapshot:discoverySnapshot,research:candidateResearch,getCode:()=>candidate.code,setCode:()=>{},go:()=>{}});
ui.render('finder');
assert.ok(element.innerHTML.includes('참고 PER · PBR 확보')&&element.innerHTML.includes('종목 분류·원천 기간 확인 필요'));
ui.render('brief');
assert.ok(element.innerHTML.includes('data-research-go="company" disabled')&&element.innerHTML.includes('data-research-go="holdings" disabled'));
assert.ok(element.innerHTML.includes('NAVER 공개 참고')&&element.innerHTML.includes('기간 미확인'));
ui.render('trend');
assert.ok(element.innerHTML.includes('가격 추세 충족 · 거래대금 미확인')&&element.innerHTML.includes('NAVER 전일 일별 자료'));
console.log('PASS discovery: canonical + separate candidate eligibility, source metadata, comparisons, CSV, and UI labels');

const dated=comparable.map((r,i)=>({...r,metric_details:{per:{...r.metric_details.per,observed_on:i?'2026-09-29':'2026-09-28'}}}));
assert.equal(E.sectors(dated,{})[0].metrics.per.value,null,'mixed valuation dates cannot form sector median');
const badRatios=comparable.map((r,i)=>({...r,metrics:{...r.metrics,per:i<2?-i:8}}));
assert.equal(E.sectors(badRatios,{})[0].metrics.per.count,4,'zero and negative multiples excluded');
const priceMeta=E.detail(candidates[0],candidateResearch,'price_rs');
assert.equal(priceMeta.source,'NAVER 전일 일별 자료');
assert.equal(priceMeta.period,'252거래일');
assert.ok(discoveryCsv.includes('NAVER 전일 일별 자료'),'CSV retains technical source too');
console.log('PASS valuation date/positive denominator and technical provenance regressions');
