'use strict';
const assert=require('node:assert/strict'),S=require('../src/dashboard_stability.js');
const now=Date.parse('2026-10-07T12:00:00+09:00');
const stale=S.quoteStatus({retrieved_at:'2026-10-02T11:00:00+09:00',price_time:null},now);
assert.equal(stale.stale,true);assert.match(stale.label,/이전 조회/);assert.match(stale.detail,/시세시각 미확인/);assert.match(stale.action,/새로고침/);
const today=S.quoteStatus({retrieved_at:'2026-10-06T16:00:00Z'},now);
assert.equal(today.stale,false);assert.match(today.label,/오늘 조회/);assert.equal(today.observed_at,'미확인');
for(const retrieved_at of [null,'invalid','2026-10-07T10:00:00','2026-10-08T10:00:00+09:00'])assert.equal(S.quoteStatus({retrieved_at},now).stale,true);
const r={code:'900000',metrics:{roe_pct:3},metric_details:{roe_pct:{source:'DART'}},common_financial:{details_from_row:true}},f={metrics_from_row:true,details_from_row:true},analysis={status:'pass'};
const data={wire_format:'live-v2',analysis_snapshot:{companies:[]},discovery:{snapshot:{companies:[r]},research:{rows:{'900000':{fundamental:f}}}},trend_following:{rows:[{analysis,technical:{},analysis_shared:true}]}};
S.restoreWire(data);assert.equal(data.snapshot,data.analysis_snapshot);assert.equal(f.metrics,r.metrics);assert.equal(f.metric_details,r.metric_details);assert.equal(r.common_financial.metric_details,r.metric_details);assert.equal(data.trend_following.rows[0].technical.trend_analysis,analysis);
console.log('PASS quote stale/today/unknown/future/timezone and compact wire restores shared contracts');
const marker='__investment_wire_text__',description='DART official account source: '+ 'verified '.repeat(30),reference={[marker]:0};
const coded={wire_format:'live-v2',wire_text:[description],analysis_snapshot:{companies:[]},discovery:{snapshot:{companies:[{code:'900000',metric_details:{per:{source:reference}},financial_completeness:{latest_stored:{reason:reference}},valuation_from_details:true,common_financial:{completeness_from_row:true}}]},research:{rows:{'900000':{technical:{price_health:{status:'ready',reason:reference}}}}}},trend_following:{rows:[{code:'900000',technical_from_research:['price_health'],analysis:{reason:reference},analysis_shared:true}]}};
S.restoreWire(coded);
const row2=coded.discovery.snapshot.companies[0],trend2=coded.trend_following.rows[0];
assert.equal(row2.valuation_details.per.source,description);assert.equal(row2.common_financial.financial_completeness.latest_stored.reason,description);assert.equal(trend2.technical.price_health.reason,description);assert.equal(trend2.analysis.reason,description);assert.ok(!Object.hasOwn(coded,'wire_text'));
trend2.technical.price_health.status='pending';assert.equal(coded.discovery.research.rows['900000'].technical.price_health.status,'ready');
assert.throws(()=>S.restoreWire({wire_format:'live-v2',wire_text:[description],bad:{[marker]:999}}),/복원/);
const reserved={wire_format:'live-v2',analysis_snapshot:{},custom:{[marker]:3}};S.restoreWire(reserved);assert.equal(reserved.custom[marker],3);
console.log('PASS lossless source text, valuation/completeness sharing, independent technical copies, invalid references and reserved namespace');
