const assert=require('node:assert/strict'),J=require('../src/dashboard_journey.js');
const rows=[{code:'900000',name:'가상 기업',market:'KOSPI',industry:'가상 산업',metrics:{market_cap_eok:900},common_financial:{basis:'CFS',period:'2026-06-30',amounts:{revenue:10,operating_profit:0,net_income:1},metrics:{roe_pct:0},metric_details:{}}}];
const research={rows:{900000:{technical:{as_of:'2026-10-01',price_trend_status:'fail',short_rs:{'1m':{score:60}}}}}};
const state={};const storage={getItem:k=>state[k],setItem:(k,v)=>state[k]=v};
assert.equal(J.journal(rows,research,'2026-10-01','fixture',storage).previous,null);
research.rows[900000].technical.short_rs['1m'].score=80;
assert.equal(J.journal(rows,research,'2026-10-01','fixture',storage).events.length,0,'same-day baseline is not fabricated history');
research.rows[900000].technical.as_of='2026-10-02';research.rows[900000].technical.price_trend_status='pass';research.rows[900000].technical.short_rs['1m'].score=86;
const next=J.journal(rows,research,'2026-10-02','fixture',storage);
assert.equal(next.events.length,2);assert.equal(next.events.find(x=>x.kind==='rs').delta,6);
assert.equal(J.journal(rows,research,'2026-10-02','fixture',storage).events.length,2,'reload preserves prior-day comparison');
assert.equal(J.journal(rows,research,'2026-10-03','fixture',storage).events.length,0,'unchanged completed price date produces no RS event');
assert.deepEqual(J.health(rows[0]).missing,[],'zero is a value');
assert.equal(J.growth(50,25),100);assert.equal(J.growth(50,0),null);assert.equal(J.growth(50,-25),null);
assert.equal(J.adjacent('2026-06-30',-3),'2026-03-31');assert.equal(J.adjacent('2026-03-31',-3),'2025-12-31');
const peers=['CFS','OFS','CFS'].map((basis,i)=>({...rows[0],code:'90000'+(i+1),common_financial:{...rows[0].common_financial,basis,period:i===2?'2025-12-31':'2026-06-30'}}));
assert.equal(J.compareRows([...rows,...peers],rows[0]).length,1,'peers exclude other basis and period');
const changed=structuredClone(next.current);changed.items[900000].name='다른 기업';assert.equal(J.diff(next.previous,changed).length,0,'identity mismatch cannot inherit history');
assert.ok(J.healthCard({...rows[0],collection_health:{source_urls:['javascript:alert(1)']}}).includes('자료 상태'));
assert.ok(!J.links(['javascript:alert(1)']).includes('href'));
assert.ok(J.journal(rows,research,'2026-10-02','fixture',undefined).note.includes('제한'));
console.log('PASS journal rollover/no false history, identity, peer basis, zero/negative growth, source links');
