'use strict';
const CompanyDetailUI=(()=>{
  const E=CompanyDetailEngine, esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=(v,d=1)=>E.num(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:d}):'—';
  const money=v=>E.num(v)?Math.abs(v)>=10000?fmt(v/10000,1)+'조':fmt(v,0)+'억':'—';
  const unit=(v,u,d=1)=>E.num(v)?fmt(v,d)+u:'—';
  const short=d=>d?.slice(2,7).replace('-','.')||'—';
  const tabs=[['summary','요약'],['business','사업'],['financial','재무'],['value','밸류에이션']];
  const heading=(s,controls='')=>`<div class="sd-heading"><h3>${esc(s)}</h3>${controls}</div>`;
  const empty=s=>`<div class="sd-empty"><strong>자료 미연결</strong><p>${esc(s)}</p></div>`;
  const card=(label,value,note='')=>`<div class="sd-stat"><span>${esc(label)}</span><b>${value}</b>${note?`<small>${esc(note)}</small>`:''}</div>`;
  function plot(cs,keys,title,mode='bars',unit='억원'){
    const valid=cs.flatMap(c=>keys.map(([k])=>c.values[k]).filter(E.num));if(!valid.length)return empty(title+'의 같은 기간 원자료가 필요합니다.');
    const low=Math.min(0,...valid),high=Math.max(0,...valid),span=high-low||1,y=v=>195-(v-low)/span*160,x=i=>58+(i+.5)/cs.length*570;
    let svg='';for(let i=0;i<=4;i++){const v=low+span*i/4;svg+=`<path d="M55 ${y(v)}H640" stroke="#eceef1" stroke-dasharray="3 4"/><text x="49" y="${y(v)+4}" text-anchor="end">${fmt(v,0)}</text>`;}
    keys.forEach(([k,label,color],j)=>{
      if(mode==='bars')svg+=cs.map((c,i)=>{const v=c.values[k],w=Math.min(42,570/cs.length/(keys.length+1));return E.num(v)?`<rect x="${x(i)+(j-(keys.length-1)/2)*w-w/2}" y="${Math.min(y(0),y(v))}" width="${w*.85}" height="${Math.max(1,Math.abs(y(v)-y(0)))}" fill="${color}" rx="2"><title>${esc(c.period_end+' '+label)} ${fmt(v)} ${unit}</title></rect>`:'';}).join('');
      else{let start=false;svg+=`<path d="${cs.map((c,i)=>{if(!E.num(c.values[k])){start=false;return '';}const d=(start?'L':'M')+x(i)+','+y(c.values[k]);start=true;return d;}).join(' ')}" fill="none" stroke="${color}" stroke-width="2"/>`+cs.map((c,i)=>E.num(c.values[k])?`<circle cx="${x(i)}" cy="${y(c.values[k])}" r="3" fill="${color}"><title>${esc(c.period_end+' '+label)} ${fmt(c.values[k])} ${unit}</title></circle>`:'').join('');}
    });
    svg+=cs.map((c,i)=>i===0||i===cs.length-1||i%Math.ceil(cs.length/7)===0?`<text x="${x(i)}" y="219" text-anchor="middle">${short(c.period_end)}</text>`:'').join('');
    return `<svg class="sd-plot" viewBox="0 0 665 240" role="img" aria-label="${esc(title)}">${svg}</svg><div class="sd-legend">${keys.map(([,l,c])=>`<span style="--c:${c}">${esc(l)}</span>`).join('')}<small>${unit}</small></div>`;
  }
  function create({element,rows,models,research,meta,getCode,setCode,shared,go,initial}){
    const key='investment-company-detail-v2-'+meta.data_mode;
    const defaults={tab:'summary',basis:meta.financial_basis==='OFS'?'OFS':'CFS',cadence:'ttm',chart:'day',range:'126',ma:true,bb:false,env:false,expanded:false,statement:'income',reverse:false,filter:'all',band:'per',valueFrom:'2023-01-01',factorFrom:'2023-01-01',factorMetric:'per',requiredReturn:10,shown:['cap','revenue','op','net','opMargin','growth','roe','per','pbr','debt','borrowings']};
    let state={...defaults,shown:[...defaults.shown]},settings=false,notice='';const editors={},financialViews={};
    if(!initial){try{initial=JSON.parse(sessionStorage.getItem(key)||'null');}catch{}}
    if(initial){const identity=rows.find(r=>r.code===initial.company?.code&&r.name===initial.company?.name&&r.market===initial.company?.market);if(identity)setCode(identity.code);for(const k of ['tab','basis','cadence','chart','range','statement','filter','band']){
      const valid={tab:tabs.map(t=>t[0]),basis:['CFS','OFS'],cadence:['ttm','annual','quarter'],chart:['day','week','month'],range:['63','126','252','all'],statement:['income','balance','cash'],filter:['all','disclosure','report','news'],band:['per','pbr','pcr']};if(valid[k].includes(initial[k]))state[k]=initial[k];}
      for(const k of ['ma','bb','env','reverse'])if(typeof initial[k]==='boolean')state[k]=initial[k];if(Array.isArray(initial.shown))state.shown=defaults.shown.filter(k=>initial.shown.includes(k));
    }
    if(initial){if(Number.isFinite(initial.requiredReturn)&&initial.requiredReturn>=.1&&initial.requiredReturn<=100)state.requiredReturn=initial.requiredReturn;if(['per','pbr','pcr'].includes(initial.factorMetric))state.factorMetric=initial.factorMetric;for(const k of ['valueFrom','factorFrom'])if(/^\d{4}-\d{2}-\d{2}$/.test(initial[k]||''))state[k]=initial[k];}
    const row=()=>rows.find(r=>r.code===getCode())||rows[0];
    const displayPrice=()=>{const chart=models[row().code].chart,last=chart.bars.at(-1);return last?{value:last.close,date:last.date,label:'저장 수정 종가'}:{value:row().metrics.price,date:meta.price_date,label:'검토 가격'};};
    const table=()=>shared.ebitda.apply(row(),shared.tables[row().code]);
    const inputGroup=()=>financialViews[row().code]||table().groups.find(g=>g.basis===state.basis&&g.cadence==='quarter')?.id||table().groups.find(g=>g.basis===state.basis)?.id;
    const periods=(cadence=state.cadence,basis=state.basis)=>E.periods(models[row().code],basis,cadence,table());
    const segments=(field,options)=>`<div class="sd-segments" aria-label="${esc(field)}">${options.map(([v,t])=>`<button data-sd-field="${field}" data-value="${v}" aria-pressed="${state[field]===v}">${esc(t)}</button>`).join('')}</div>`;
    const basis=()=>segments('basis',[['CFS','연결'],['OFS','별도']]);
    const cadence=()=>segments('cadence',[['ttm','TTM'],['annual','연간'],['quarter','분기']]);
    function jump(items){return `<nav class="sd-jump" aria-label="섹션 바로가기">${items.map(([id,t])=>`<button data-sd-jump="${id}">${esc(t)}</button>`).join('')}</nav>`;}
    function financialCharts(){return ['revenue','operating_profit','net_income'].map((k,i)=>{
      const label=['매출액','영업이익','당기순이익'][i],color=['#8172c7','#2d9c90','#5a87b7'][i];return `<section class="sd-trend-row"><h4>${label}</h4><div class="sd-grid"><div><p class="sd-muted">연간</p>${plot(periods('annual'),[[k,label,color]],label+' 연간 추이','bars',k==='eps'?'원':'억원')}</div><div><p class="sd-muted">분기별</p>${plot(periods('quarter'),[[k,label,color]],label+' 분기 추이','bars',k==='eps'?'원':'억원')}</div></div></section>`;}).join('');}
    function priceChart(){const model=models[row().code].chart;
      if(!model.bars.length)return empty(model.reason);
      const all=E.indicators(E.aggregate(model.bars,state.chart)),count=state.range==='all'?all.length:Math.ceil(Number(state.range)/(state.chart==='week'?5:state.chart==='month'?21:1)),ps=all.slice(-count),rs=E.relative(ps,model.benchmark);
      const paths=[...(state.ma?[['ma5','#c7a248'],['ma20','#8274c8'],['ma60','#3eaa99']]:[]),...(state.bb?[['bbHigh','#b494c6'],['bbLow','#b494c6']]:[]),...(state.env?[['envHigh','#df9848'],['envLow','#df9848']]:[])];
      const values=ps.flatMap(p=>[p.close,p.high,p.low,...paths.map(([k])=>p[k])].filter(E.num)),lo=Math.min(...values)*.98,hi=Math.max(...values)*1.02,span=hi-lo||1,x=i=>50+(i+.5)/ps.length*670,y=v=>290-(v-lo)/span*248;
      const hasCandles=ps.every(p=>['open','high','low'].every(k=>E.num(p[k]))),vols=ps.map(p=>p.volume).filter(E.num),vm=Math.max(1,...vols);let out='';
      for(let i=0;i<=4;i++){const v=lo+span*i/4;out+=`<path d="M50 ${y(v)}H728" stroke="#eceef1" stroke-dasharray="3 4"/><text x="738" y="${y(v)+4}">${fmt(v,0)}</text>`;}
      const width=Math.max(1,Math.min(12,670/ps.length*.65));
      if(hasCandles)out+=ps.map((p,i)=>{const color=p.close>=p.open?'#e15161':'#3971d6';return `<g><title>${esc(p.date)} 시 ${fmt(p.open,0)} 고 ${fmt(p.high,0)} 저 ${fmt(p.low,0)} 종 ${fmt(p.close,0)} 거래량 ${fmt(p.volume,0)}</title><path d="M${x(i)} ${y(p.high)}V${y(p.low)}" stroke="${color}"/><rect x="${x(i)-width/2}" y="${Math.min(y(p.open),y(p.close))}" width="${width}" height="${Math.max(1,Math.abs(y(p.open)-y(p.close)))}" fill="${color}"/></g>`;}).join('');
      else out+=`<path d="${ps.map((p,i)=>(i?'L':'M')+x(i)+','+y(p.close)).join(' ')}" fill="none" stroke="#6e66b2" stroke-width="2"/>`;
      for(const [k,c]of paths){let start=false;out+=`<path d="${ps.map((p,i)=>{if(!E.num(p[k])){start=false;return '';}const d=(start?'L':'M')+x(i)+','+y(p[k]);start=true;return d;}).join(' ')}" fill="none" stroke="${c}" stroke-width="1.3"/>`;}
      out+=`<path d="M50 ${y(ps.at(-1).close)}H728" stroke="#d65c8d" stroke-dasharray="4 4"/>`;
      out+=ps.map((p,i)=>E.num(p.volume)?`<rect x="${x(i)-width/2}" y="${351-p.volume/vm*45}" width="${width}" height="${p.volume/vm*45}" fill="${p.close>=(p.open??p.close)?'#e15161':'#3971d6'}"><title>${esc(p.date)} 거래량 ${fmt(p.volume,0)}주</title></rect>`:'').join('');
      out+='<text x="50" y="310">거래량 (주)</text>';
      const rv=rs.map(p=>p.rs).filter(E.num);if(rv.length){const rl=Math.min(...rv),rh=Math.max(...rv),ry=v=>410-(v-rl)/(rh-rl||1)*35;let start=false;out+=`<text x="50" y="374">지수 대비 상대가격 · 시작 100</text><path d="${rs.map((p,i)=>{if(!E.num(p.rs)){start=false;return '';}const d=(start?'L':'M')+x(i)+','+ry(p.rs);start=true;return d;}).join(' ')}" fill="none" stroke="#8172c7"/>`;}
      out+=`<text x="50" y="435">${ps[0].date}</text><text x="728" y="435" text-anchor="end">${ps.at(-1).date}</text>`;
      return `<p class="sd-chart-readout">${esc(ps.at(-1).date)} · 종가 <b>${fmt(ps.at(-1).close,0)}원</b> · ${hasCandles?'OHLC 캔들':'시가·고가·저가 미확보 · 종가 선'} · ${ps.length}개 관측 구간</p><svg class="sd-price-plot" viewBox="0 0 820 450" role="img" aria-label="${esc(row().name)} ${state.chart} 주가와 거래량">${out}</svg><p class="sd-muted">${esc(model.source)} · ${esc(model.as_of)}<br>MA 5·20·60 구간 · BB 20구간 평균 ± 2σ · ENV 20구간 평균 ± 5% · 주·월은 마지막 관측일 종가</p>`;
    }
    function summaryMetrics(){return Object.fromEntries(E.summary(row(),models[row().code],research,meta,state.basis).map(([k,l,v,u,n])=>[k,[l,u==='억원'?money(v):unit(v,u),n||'미확보']]));}
    function summary(){const metrics=summaryMetrics();return `<div class="sd-overview ${state.expanded?'expanded':''}"><section>${heading('주가 차트',`<button data-sd-toggle="expanded" aria-pressed="${state.expanded}">${state.expanded?'차트 축소':'차트 확장'}</button>`)}<div class="sd-box sd-chart"><div class="sd-chart-controls">${segments('chart',[['day','일'],['week','주'],['month','월']])}${['ma','bb','env'].map(k=>`<button data-sd-toggle="${k}" aria-pressed="${state[k]}">${k.toUpperCase()}</button>`).join('')}<label>표시 기간<select id="sdChartRange">${[['63','3개월'],['126','6개월'],['252','1년'],['all','전체']].map(([v,l])=>`<option value="${v}" ${state.range===v?'selected':''}>${l}</option>`).join('')}</select></label></div>${priceChart()}</div></section><section>${heading('요약 정보',`<small>기준 ${short(periods('quarter').at(-1)?.period_end)} · ${state.basis==='CFS'?'연결':'별도'}</small><button id="sdSettings" aria-label="요약 정보 표시 항목 설정">⚙</button>`)}<div class="sd-box sd-metrics">${state.shown.map(k=>card(...metrics[k])).join('')}</div></section></div>${settings?`<div class="sd-box sd-settings">${heading('요약 정보 항목 설정','<button id="sdSettingsClose">설정 닫기</button>')}<p class="sd-muted">표시할 항목을 선택합니다. 선택값은 같은 탭에서 유지됩니다.</p>${Object.entries(metrics).map(([k,[l]])=>`<label><input type="checkbox" data-sd-metric="${k}" ${state.shown.includes(k)?'checked':''}>${l}</label>`).join('')}<button id="sdSettingsReset">기본값으로 초기화</button></div>`:''}<section class="sd-section">${heading('재무 추이',basis())}<p class="sd-muted">실제 실적 · 단독분기 / 연간 · 인포맥스 우선 / 공시 보충</p><div class="sd-box">${financialCharts()}</div></section>`; }
    function business(){const cs=periods(),v=cs.at(-1)?.values||{};return jump([['profile','기업 개요'],['sales','매출 분석'],['cost','비용 분석']])+`<section id="sd-profile" class="sd-section">${heading('기업 개요')}<div class="sd-box"><p><b>${esc(row().name)}</b> · ${esc(row().industry)} · ${esc(row().market)}</p><p class="sd-muted">검토 종목 분류: ${esc(row().security_type)} · ${esc(row().analysis_profile)}</p>${empty('사업 설명·발행주식수·외국인 지분율 원자료가 연결되면 여기에 표시합니다.')}</div>${heading('수주잔고 추이')}${empty('기간별 수주잔고와 사업보고서 원자료가 필요합니다.')}</section><section id="sd-sales" class="sd-section">${heading(row().name+' 매출 분석',basis()+cadence())}<div class="sd-overview"><article class="sd-box">${heading('매출 추이')}${plot(cs,[['revenue','매출액','#8274c8']],'매출 추이')}</article><article class="sd-box">${heading('실적 요약')}<div class="sd-stats">${card('매출액',money(v.revenue))}${card('영업이익',money(v.operating_profit),'영업이익률 '+unit(v.operating_margin,'%'))}${card('순이익',money(v.net_income),'순이익률 '+unit(v.net_margin,'%'))}</div></article></div>${heading('부문별 매출 비중 추이')}${empty('동일 기간의 사업부별 매출과 비중 자료가 필요합니다.')}${heading('부문별 매출')}${empty('사업부·매출액·전년 동기 비교값이 연결되지 않았습니다.')}</section><section id="sd-cost" class="sd-section">${heading(row().name+' 비용 분석',cadence())}<div class="sd-grid"><article class="sd-box">${heading('비용 구성')}${plot(cs,[['cost_of_sales','매출원가','#8172c7'],['sga','판관비','#5a87b7']],'비용 구성')}</article><article class="sd-box">${heading('마진 추이')}${plot(cs,[['operating_margin','OPM','#2d9c90'],['net_margin','순이익률','#8274c8']],'마진 추이','line','%')}</article></div>${heading('비용 현황')}${plot(cs,[['gross_margin','매출총이익률','#8172c7'],['operating_margin','영업이익률','#2d9c90']],'매출총이익률과 영업이익률','line','%')}</section>`;}
    const statementDefs={
      income:[['revenue','매출액'],['cost_of_sales','매출원가'],['gross_profit','매출총이익'],['gross_margin','매출총이익률','%'],['sga','판매비와관리비'],['operating_profit','영업이익'],['operating_margin','영업이익률','%'],['finance_income','금융수익'],['finance_cost','금융원가'],['other_income','기타수익'],['other_cost','기타비용'],['pretax','세전계속사업이익'],['tax','법인세비용'],['net_income','당기순이익'],['parent_net','지배주주순이익'],['nci_net','비지배주주순이익'],['eps','EPS (원)','원'],['ebitda','EBITDA']],
      balance:[['assets','자산총계'],['current_assets','유동자산'],['noncurrent_assets','비유동자산'],['liabilities','부채총계'],['current_liabilities','유동부채'],['noncurrent_liabilities','비유동부채'],['equity','자본총계'],['parent_equity','지배주주지분'],['retained_earnings','이익잉여금'],['borrowings','차입금'],['total_borrowings','총차입금'],['debt_ratio','부채비율','%']],
      cash:[['ocf','영업활동 현금흐름'],['net_income','당기순손익'],['noncash_cost','현금유출 없는 비용 가산'],['noncash_income','현금유입 없는 수익 차감'],['noncash_adjustments','비현금 항목 조정'],['working_capital','영업활동 자산부채변동'],['cash_generated','영업에서 창출된 현금흐름'],['icf','투자활동 현금흐름'],['capex_ppe','유형자산 취득'],['capex_intangibles','무형자산 취득'],['financing_cf','재무활동 현금흐름'],['cash_change','현금증감'],['cash_start','기초현금'],['cash_end','기말현금'],['fcf','FCF']]
    };
    function statementPeriods(){return periods(state.statement==='balance'&&state.cadence==='ttm'?'quarter':state.cadence);}
    function statement(){let cs=statementPeriods(),defs=statementDefs[state.statement];
      if(state.reverse)cs=[...cs].reverse();
      return heading('재무제표',basis()+cadence())+`<div class="sd-box"><div class="sd-heading">${segments('statement',[['income','손익계산서'],['balance','재무상태표'],['cash','현금흐름표']])}<button data-sd-toggle="reverse">${state.reverse?'오래된순':'최신순'}으로 정렬</button></div>
      ${!cs.length?empty('선택한 회계기준·기간의 재무제표가 없습니다.'):`<div class="sd-table-scroll" tabindex="0" aria-label="재무제표 좌우 스크롤"><table class="sd-table"><thead><tr><th>항목</th>${cs.map(c=>`<th>${short(c.period_end)}</th>`).join('')}</tr></thead><tbody>${defs.map(([k,l,u])=>`<tr data-sd-account="${k}"><th><button data-sd-trend="${k}" aria-label="${l} 추세 차트">${l} ◷</button></th>${cs.map(c=>`<td title="${esc(c.source+' · '+(c.cell_notes?.[k]||''))}">${u?unit(c.values[k],u,u==='원'?0:1):money(c.values[k])}${c.cell_notes?.[k]&&E.num(c.values[k])?'*':''}</td>`).join('')}</tr>`).join('')}</tbody></table></div>
      <p class="sd-muted">${state.statement==='balance'?'재무상태표는 기말 잔액':state.cadence==='quarter'?'단독 3개월 실적 · 현금흐름은 같은 연도 누적 차감':state.cadence==='ttm'?'연속 4개 단독분기 합계 · 기초현금은 시작 잔액':'연간 실적'} · EPS는 기간 차감·합계하지 않으며 TTM 공시 주당값은 별도 확인 · FCF = 영업현금흐름 − 유형/무형자산 취득</p>
      <details><summary>기간별 출처와 공시일</summary>${cs.map(c=>`<p>${esc(c.period_end)} · ${esc(c.source)} · 공개일 ${esc(c.available_at||c.filing_available_at||'공급자 미확인')} ${c.source_url?`<a href="${esc(c.source_url)}" target="_blank" rel="noopener noreferrer">DART 원문 ↗</a>`:''}</p>`).join('')}</details>`}<div id="sdRowTrend"></div></div>`;
    }
    function financial(){const t=table(),g=t.groups.find(g=>g.id===inputGroup());return `<section id="sd-statement" class="sd-section">${statement()}</section><section class="sd-section sd-box">${heading('EBITDA 수기 입력 · 계산')}${g?`<label>입력 기준<select id="financialPeriodSelect">${t.groups.map(g=>`<option value="${g.id}" ${g.id===inputGroup()?'selected':''}>${g.basis==='CFS'?'연결':'별도'} · ${g.cadence==='annual'?'연간':'분기'}</option>`).join('')}</select></label>`+EbitdaEditor.render(row(),g,shared.ebitda,editors[row().code]||(editors[row().code]={})):empty('수기 입력 대상 재무 기간이 없습니다.')}</section>`;}
    function valuation(){const r=row(),v=E.valuation(r,models[r.code],state.basis),current=v.current,stats=E.distribution(v.history.filter(p=>p.date>=state.valueFrom),state.band,current[state.band]),metricKey={per:'eps',pbr:'bps',pcr:'cps'}[state.band];
      const bandKeys=[['close','관측 종가','#343d50'],['b10','10%','#5576b6'],['b25','25%','#6594be'],['b50','50%','#8b7bc4'],['b75','75%','#bc96bf'],['b90','90%','#dc9bab']],bandRows=v.history.filter(p=>p.date>=state.valueFrom).map(p=>({period_end:p.date,values:{close:p.close,...Object.fromEntries((stats?.bands||[]).map((b,i)=>['b'+[10,25,50,75,90][i],E.num(p[metricKey])?p[metricKey]*b:null]))}}));
      const info=['per','pbr','pcr'].map(k=>{const d=E.distribution(v.history,k,current[k]);return `<article class="sd-position">${card(k.toUpperCase(),unit(current[k],'배',2),d?`관측 ${d.count}일 · 하위 ${fmt(d.percentile,0)}% 위치`:'분포용 유효 관측 20일 이상 필요')}<div class="sd-position-bar">${d?`<i style="left:${d.percentile}%" title="하위 ${fmt(d.percentile)}%"></i>`:''}</div><div class="sd-position-label"><span>${d?fmt(d.min,2):'—'}</span><span>${d?fmt(d.max,2):'—'}</span></div></article>`;}).join('');
      const histogram=stats?`<svg viewBox="0 0 650 150" class="sd-histogram" role="img" aria-label="${state.band.toUpperCase()} 역사 분포">${stats.histogram.map((b,i)=>{const h=b.count/Math.max(1,...stats.histogram.map(x=>x.count))*100;return `<rect x="${35+i*48}" y="${120-h}" width="40" height="${h}" fill="${current[state.band]>=b.lo&&current[state.band]<=b.hi?'#6958a6':'#d9d4e8'}"><title>${fmt(b.lo,2)}~${fmt(b.hi,2)}배 · ${b.count}일</title></rect>`;}).join('')}<text x="35" y="143">${fmt(stats.min,2)}배</text><text x="610" y="143" text-anchor="end">${fmt(stats.max,2)}배</text></svg>`:empty('양수 평가배수 20일 이상 필요');
      const rim=E.rim(current.bps,current.eps,state.requiredReturn/100),last=v.ttm.at(-1),first=v.history.find(p=>p.date>=state.factorFrom&&E.num(p[state.factorMetric])),end=v.history.at(-1),factorKey={per:state.basis==='OFS'?'net_income':'parent_net',pbr:state.basis==='OFS'?'equity':'parent_equity',pcr:'ocf'}[state.factorMetric],firstFin=v.ttm.find(c=>c.period_end===first?.period),endFin=v.ttm.find(c=>c.period_end===end?.period),cap=p=>E.ratio(p?.close*current.shares,1e8),factors=E.decomposition(cap(first),cap(end),firstFin?.values[factorKey],endFin?.values[factorKey]);
      const factorDates=v.history.filter(p=>p.date>=first?.date),factorIndex=factorDates.map(p=>{const c=v.ttm.find(c=>c.period_end===p.period);return {period_end:p.date,values:{cap:E.ratio(cap(p),cap(first),100),fundamental:E.ratio(c?.values[factorKey],firstFin?.values[factorKey],100)}};});
      const dateControl=(id,value)=>`<label>시작일<input type="date" id="${id}" value="${value}" max="${meta.price_date}"></label>`;
      function waterfall(f){const points=[{label:'시작',from:0,to:f.start},{label:'재무 변화',from:f.start,to:f.start+f.profit},{label:'배수 변화',from:f.start+f.profit,to:f.end},{label:'현재',from:0,to:f.end}],low=Math.min(0,...points.flatMap(p=>[p.from,p.to])),high=Math.max(...points.flatMap(p=>[p.from,p.to])),y=v=>195-(v-low)/(high-low||1)*155;return `<svg class="sd-plot" viewBox="0 0 665 240" role="img" aria-label="시가총액 변화 폭포 차트">${points.map((p,i)=>`<rect x="${70+i*150}" y="${Math.min(y(p.from),y(p.to))}" width="95" height="${Math.max(1,Math.abs(y(p.from)-y(p.to)))}" fill="${i===0||i===3?'#8172c7':p.to>=p.from?'#e15161':'#3971d6'}"/><text x="${117+i*150}" y="${Math.min(y(p.from),y(p.to))-8}" text-anchor="middle">${fmt(i===0?f.start:i===3?f.end:p.to-p.from,0)}</text><text x="${117+i*150}" y="220" text-anchor="middle">${p.label}</text>${i<3?`<path d="M${165+i*150} ${y(p.to)}H${220+i*150}" stroke="#9ca4b3" stroke-dasharray="3 3"/>`:''}`).join('')}</svg><p class="sd-muted">단위: 억원 · 증가/감소를 앞 항목에서 이어 표시합니다.</p>`;}
      return `<section class="sd-section">${heading(r.name+' 밸류에이션',basis())}<p class="sd-method">시총·가격 기준 ${esc(meta.price_date)} · 재무 ${short(current.period)}. 현재 시총 ÷ 수정종가로 구한 주식수를 전 기간에 고정한 <b>근사 계산</b>입니다. 주식수 변동·우선주 배분을 반영하지 않으며 기존 판단 엔진에 합산하지 않습니다.</p>
      ${heading('지금 가격의 위치')}<div class="sd-box sd-grid3">${info}</div>
      ${heading(state.band.toUpperCase()+' 밴드',segments('band',[['per','PER'],['pbr','PBR'],['pcr','PCR']])+dateControl('sdValueFrom',state.valueFrom))}<div class="sd-box"><div class="sd-grid"><div>${stats?plot(bandRows,bandKeys,'주가와 '+state.band.toUpperCase()+' 밴드','line','원'):empty('평가배수 분포와 같은 기간 재무 자료 필요')}</div><div>${card('현재 '+state.band.toUpperCase(),unit(current[state.band],'배',2))}${stats?stats.bands.map((b,i)=>card(['하위 10%','하위 25%','중앙값','상위 25%','상위 10%'][i],unit(b,'배',2),'현재 주당값 환산 '+unit(b*current[metricKey],'원',0))).join(''):''}</div></div>${histogram}<p class="sd-muted">선택 기간의 10·25·50·75·90% 분위수. 적자 PER·음수 PCR는 제외합니다. 각 계정의 확인된 공개일 이후에만 재무를 연결합니다. 공개일 미확인 계정은 제외하며 공시 정정 당시 원본의 재현은 미확인입니다. 확보 기간 ${esc(v.history.find(p=>E.num(p[state.band]))?.date||'—')} ~ ${esc(current.date||'—')}.</p></div>
      ${heading('RIM 적정가')}<div class="sd-box"><label>요구수익률 (%)<input id="sdRequiredReturn" type="number" min="0.1" max="100" step="0.1" value="${state.requiredReturn}"></label><p class="sd-muted">초기 요구수익률 10%는 조정 가능한 가정입니다. 관측 TTM 이익을 유지하고 초과이익이 매년 100·90·80% 남는 상황을 계산합니다.</p>${rim?`<div class="sd-grid3">${rim.scenarios.map(x=>card('초과이익 지속 '+fmt(x.w*100,0)+'%',unit(x.value,'원',0),'현재가 대비 '+unit(E.ratio(x.value-current.price,current.price,100),'%'))).join('')}</div><details><summary>초과이익 계산 내역 · 90% 지속</summary><p>BPS ${unit(current.bps,'원',0)} · EPS ${unit(current.eps,'원',0)} · 초과이익 = EPS − BPS × 요구수익률</p><div class="sd-table-scroll"><table class="sd-table"><thead><tr><th>경과연도</th><th>초과이익 (원/주)</th><th>현재가치 (원/주)</th></tr></thead><tbody>${rim.years.map(x=>`<tr><th>${x.year}</th><td>${fmt(x.excess,0)}</td><td>${fmt(x.pv,0)}</td></tr>`).join('')}</tbody></table></div><p>주당가치 = BPS + 초과이익 × 지속률 ÷ (1 + 요구수익률 − 지속률). 이익의 미래 실현을 보장하지 않는 가정 계산입니다.</p></details>`:empty('양수 BPS와 확인된 TTM 이익 필요')}</div>
      ${heading('시가총액 변화 요인',segments('factorMetric',[['per','순이익'],['pbr','자본'],['pcr','영업현금']])+dateControl('sdFactorFrom',state.factorFrom))}<div class="sd-box">${factors?waterfall(factors)+plot(factorIndex,[['cap','시가총액','#8172c7'],['fundamental','재무값','#2d9c90']],'시총과 재무값의 변화','line','시작 = 100')+`<p>시작 ${money(factors.start)} + 재무 변화 ${money(factors.profit)} + 배수 변화 ${money(factors.multiple)} = 현재 ${money(factors.end)}</p><p class="sd-muted">${esc(first.date)} → ${esc(end.date)} · 재무 변화 = (기말 재무값 − 기초 재무값) × 기초 배수. 나머지를 배수 변화로 표시합니다. 주식수 고정 추정 시총입니다.</p>`:empty('두 날짜의 양수 재무값과 가격 필요')}</div>
      ${heading('사후 확인 재무 · 기말 참고배수')}<div class="sd-box sd-table-scroll"><table class="sd-table"><thead><tr><th>기간</th><th>기말 수정종가</th><th>EPS 근사</th><th>BPS 근사</th><th>PER 근사</th><th>PBR 근사</th></tr></thead><tbody>${v.detail.map(c=>`<tr><th>${short(c.period_end)}</th>${['close','eps','bps','per','pbr'].map(k=>`<td>${fmt(c.values[k],['per','pbr'].includes(k)?2:0)}</td>`).join('')}</tr>`).join('')}</tbody></table><p class="sd-muted">사후에 공개된 재무를 기말 수정종가에 연결한 참고배수이며 당시 이용 가능했던 지표가 아닙니다. 공개일이 없거나 평가일 이후 공개된 계정은 —로 표시합니다. 현재 추정 주식수 고정 가정으로 공시 EPS와 다릅니다. 배수는 TTM / 기말 지배자본 기준입니다.</p></div>
      ${heading('동종업종 밸류에이션')}<div class="sd-box"><div class="sd-stats">${['per','pbr'].map(k=>{const peer=DiscoveryEngine.peers(rows,r,research,k);return card(k.toUpperCase()+' 중앙값',unit(peer.median,'배',2),'동일 산업·기간·기준 '+peer.count+'개 · 5개 이상 필요');}).join('')}</div><p class="sd-muted">같은 기준으로 확인된 기업만 비교합니다. 전체 동종업종 원자료 연결은 추가 수집이 필요합니다.</p></div></section>`;
    }
    function availability(){return `<div class="sd-table-scroll"><table class="sd-table"><thead><tr><th>자료</th><th>가능 여부</th><th>현재 상태</th></tr></thead><tbody><tr><th>연결/별도 재무제표·비용</th><td>연결 가능</td><td>선택 기업의 기간·기준·통화는 재무 확보 상태에서 확인합니다.</td></tr><tr><th>사업 설명·부문 매출·수주</th><td>공시에서 수집 가능</td><td>기업마다 계정·표가 달라 별도 추출 필요; 일괄 구조화는 미완료</td></tr><tr><th>주식수·외국인 지분·10년 밴드</th><td>추가 원자료로 가능</td><td>주식수 변동 이력과 장기 수정주가 확보 필요</td></tr><tr><th>동종업종 비교</th><td>추가 수집으로 가능</td><td>같은 기간·기준의 업종 전체 재무 자료 필요</td></tr><tr><th>스탁이지 자체 등급·독자 계산값</th><td>현재 정확한 재현 불가</td><td>공식 제공 경로나 공개 산식이 미확인</td></tr><tr><th>정정 전 과거 공시값</th><td>현재 파일로 재현 불가</td><td>각 시점의 최초·정정 보고서를 따로 보존해야 함</td></tr></tbody></table></div>`;}
    function save(){try{sessionStorage.setItem(key,JSON.stringify({...state,company:{code:row().code,name:row().name,market:row().market}}));}catch{notice='화면 설정 복원이 제한됩니다. 입력값은 JSON 파일로 보관하세요.';}}
    function render(){const r=row();if(!r){element.innerHTML=empty('검토 기업 자료가 없습니다.');return;}save();const chart=models[r.code].chart,priceInfo=displayPrice(),price=priceInfo.value,pos=E.ratio(price-chart.low_52w,chart.high_52w-chart.low_52w,100);
      element.innerHTML=`<div class="sd-selector"><label>분석 기업<select id="sdCompany">${rows.map(x=>`<option value="${x.code}" ${x.code===r.code?'selected':''}>${esc(x.name)} · ${x.code}</option>`).join('')}</select></label><button data-sd-go="brief">간단 분석</button><button data-sd-go="holdings">보유 검토</button></div><header class="sd-stock-header"><div class="sd-name"><span class="sd-avatar" aria-hidden="true">${esc(r.name.slice(0,2))}</span><div><div class="sd-title"><h2>${esc(r.name)}</h2><small>${esc(r.code+' · '+r.market)}</small><button id="sdWatch" aria-label="${esc(r.name)} 관심종목" aria-pressed="${shared.isWatched(r.code)}">${shared.isWatched(r.code)?'★':'☆'}</button></div><b class="sd-stock-price">${unit(price,'원',0)}</b><small>${priceInfo.label} · ${priceInfo.date}</small></div></div><div class="sd-header-values">${card('시가총액',money(r.metrics.market_cap_eok))}${(()=>{const metric=E.summary(r,models[r.code],research,meta,state.basis).find(x=>x[0]==='per');return card(metric[1]+' (TTM)',unit(metric[2],'배',2));})()}<div class="sd-range"><span>52주 종가 범위</span><div>${fmt(chart.low_52w,0)} <i>${E.num(pos)?`<b style="left:${Math.max(0,Math.min(100,pos))}%"></b>`:''}</i> ${fmt(chart.high_52w,0)}</div><small>${esc(chart.reason)}</small></div></div></header><nav class="sd-tabs" aria-label="검토 상세분석 탭" role="tablist">${tabs.map(([id,t])=>`<button role="tab" id="sd-tab-${id}" aria-controls="sdContent" data-sd-tab="${id}" aria-selected="${state.tab===id}" tabindex="${state.tab===id?'0':'-1'}">${t}</button>`).join('')}</nav><p class="sd-muted" role="status">${esc(notice)}</p><div id="sdContent" role="tabpanel" aria-labelledby="sd-tab-${state.tab}">${typeof FinancialCompletenessUI!=='undefined'?FinancialCompletenessUI.render(models[r.code]?.financial_completeness||models[r.code]?.native_financial?models[r.code]:shared.tables[r.code]?.financial_completeness||shared.tables[r.code]?.native_financial?shared.tables[r.code]:null):''}${({summary,business,financial,value:valuation})[state.tab]()}</div><details class="sd-source"><summary>출처·기간·미연결 자료 확인</summary><p>${esc(meta.financial_period+' · '+meta.financial_basis+' · 가격 '+meta.price_date)}</p>${models[r.code].notes.map(n=>`<p>${esc(n)}</p>`).join('')}${availability()}<p>재무 연결 범위와 공개일은 선택 기업의 확보 상태를 따릅니다. 인포맥스 우선 금액과 DART 보충값을 표시합니다. 공시 정정 전의 과거값 재현은 보장하지 않습니다.</p></details>`;
      bind();
    }
    function bind(){const $=id=>element.querySelector('#'+id);
      $('sdCompany').onchange=e=>{setCode(e.target.value);settings=false;render();};$('sdWatch').onclick=()=>{shared.toggleWatch(row().code);render();};
      element.querySelectorAll('[data-sd-tab]').forEach(el=>el.onclick=()=>{state.tab=el.dataset.sdTab;settings=false;render();element.querySelector('#sd-tab-'+state.tab)?.focus();});
      element.querySelectorAll('[role=tab]').forEach(el=>el.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const i=tabs.findIndex(t=>t[0]===state.tab);state.tab=tabs[e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length][0];render();element.querySelector('#sd-tab-'+state.tab).focus();});
      element.querySelectorAll('[data-sd-field]').forEach(el=>el.onclick=()=>{state[el.dataset.sdField]=el.dataset.value;if(el.dataset.sdField==='basis')delete financialViews[row().code];render();});element.querySelectorAll('[data-sd-toggle]').forEach(el=>el.onclick=()=>{state[el.dataset.sdToggle]=!state[el.dataset.sdToggle];render();});
      element.querySelectorAll('[data-sd-jump]').forEach(el=>el.onclick=()=>element.querySelector('#sd-'+el.dataset.sdJump)?.scrollIntoView({behavior:'smooth',block:'start'}));
      element.querySelectorAll('[data-sd-go]').forEach(el=>el.onclick=()=>go(el.dataset.sdGo));
      if($('sdChartRange'))$('sdChartRange').onchange=e=>{state.range=e.target.value;render();};
      if($('sdSettings'))$('sdSettings').onclick=()=>{settings=!settings;render();};if($('sdSettingsClose'))$('sdSettingsClose').onclick=()=>{settings=false;render();};
      if($('sdSettingsReset'))$('sdSettingsReset').onclick=()=>{state.shown=[...defaults.shown];render();};
      element.querySelectorAll('[data-sd-metric]').forEach(el=>el.onchange=()=>{state.shown=defaults.shown.filter(k=>element.querySelector(`[data-sd-metric="${k}"]`)?.checked);render();});
      for(const [id,k]of [['sdValueFrom','valueFrom'],['sdFactorFrom','factorFrom']])if($(id))$(id).onchange=e=>{if(/^\d{4}-\d{2}-\d{2}$/.test(e.target.value)&&e.target.value<=meta.price_date)state[k]=e.target.value;render();};
      if($('sdRequiredReturn'))$('sdRequiredReturn').onchange=e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>=.1&&n<=100)state.requiredReturn=n;render();};
      element.querySelectorAll('[data-sd-trend]').forEach(el=>el.onclick=()=>{const k=el.dataset.sdTrend,def=statementDefs[state.statement].find(x=>x[0]===k);$('sdRowTrend').innerHTML=plot(statementPeriods(),[[k,def[1],'#8172c7']],def[1]+' 추이','line',def[2]||'억원');});
      if(state.tab==='financial'){EbitdaEditor.bind(element,row(),shared.tables[row().code],inputGroup(),shared.ebitda,editors[row().code],render);if($('financialPeriodSelect'))$('financialPeriodSelect').onchange=e=>{financialViews[row().code]=e.target.value;editors[row().code]={};state.basis=e.target.value.split('-')[0];render();};}
    }
    return {render,state:()=>({...state})};
  }
  function metricCards(row,model,research,meta){return `<article class="panel below brief-financial"><h3>주요 재무지표</h3><div class="brief-metrics">${E.summary(row,model,research,meta).map(([k,l,v,u,n])=>`<div class="sd-stat" data-brief-metric="${k}"><span>${esc(l)}</span><b>${u==='억원'?money(v):unit(v,u,2)}</b><small>${esc(n||'자료 미확보')}</small></div>`).join('')}</div>${model?`<div class="sd-grid3 brief-comparison">${[['revenue','매출액','#8172c7'],['operating_profit','영업이익','#2d9c90'],['net_income','당기순이익','#5a87b7']].map(([k,l,c])=>`<section><h4>${l} · 최근 4분기</h4>${plot(E.periods(model,meta.financial_basis,'quarter').slice(-4),[[k,l,c]],l+' 분기 비교')}</section>`).join('')}</div>`:''}<p class="psub">손익은 최신 단독분기 · ROE는 검토 TTM · PER/PBR 근사는 상세 밸류에이션의 계산 기준을 따릅니다.</p></article>`;}
  return {create,metricCards};
})();
