'use strict';
const CompanyDetailUI=(()=>{
  const E=CompanyDetailEngine, esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=(v,d=1)=>E.num(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:d}):'—';
  const money=v=>E.num(v)?Math.abs(v)>=10000?fmt(v/10000,1)+'조':fmt(v,0)+'억':'—';
  const unit=(v,u,d=1)=>E.num(v)?fmt(v,d)+u:'—';
  const short=d=>d?.slice(2,7).replace('-','.')||'—';
  const tabs=[['summary','요약'],['business','사업'],['financial','재무'],['earnings','실적·전망'],['value','밸류에이션'],['news','소식']];
  const heading=(s,controls='')=>`<div class="sd-heading"><h3>${esc(s)}</h3>${controls}</div>`;
  const empty=s=>`<div class="sd-empty"><strong>자료 미연결</strong><p>${esc(s)}</p></div>`;
  const card=(label,value,note='')=>`<div class="sd-stat"><span>${esc(label)}</span><b>${value}</b>${note?`<small>${esc(note)}</small>`:''}</div>`;
  function plot(cs,keys,title,mode='bars',unit='억원'){
    const valid=cs.flatMap(c=>keys.map(([k])=>c.values[k]).filter(E.num));if(!valid.length)return empty(title+'의 같은 기간 원자료가 필요합니다.');
    const low=Math.min(0,...valid),high=Math.max(0,...valid),span=high-low||1,y=v=>195-(v-low)/span*160,x=i=>58+(i+.5)/cs.length*570;
    let svg='';for(let i=0;i<=4;i++){const v=low+span*i/4;svg+=`<path d="M55 ${y(v)}H640" stroke="#eceef1" stroke-dasharray="3 4"/><text x="49" y="${y(v)+4}" text-anchor="end">${fmt(v,0)}</text>`;}
    keys.forEach(([k,label,color],j)=>{
      if(mode==='bars')svg+=cs.map((c,i)=>{const v=c.values[k],w=Math.min(42,570/cs.length/(keys.length+1));return E.num(v)?`<rect x="${x(i)+(j-(keys.length-1)/2)*w-w/2}" y="${Math.min(y(0),y(v))}" width="${w*.85}" height="${Math.max(1,Math.abs(y(v)-y(0)))}" fill="${color}" rx="2"><title>${esc(c.period_end+' '+label)} ${fmt(v)} ${unit}</title></rect>`:'';}).join('');
      else{let start=false;svg+=`<path d="${cs.map((c,i)=>{if(!E.num(c.values[k])){start=false;return '';}const d=(start?'L':'M')+x(i)+','+y(c.values[k]);start=true;return d;}).join(' ')}" fill="none" stroke="${color}" stroke-width="2"/>`+cs.map((c,i)=>E.num(c.values[k])?`<circle cx="${x(i)}" cy="${y(c.values[k])}" r="3" fill="${color}"><title>${esc(c.period_end+' '+label)} ${fmt(c.values[k])} ${unit}</title></circle>`:'').join('');}
    });
    svg+=cs.map((c,i)=>`<text x="${x(i)}" y="219" text-anchor="middle">${short(c.period_end)}</text>`).join('');
    return `<svg class="sd-plot" viewBox="0 0 665 240" role="img" aria-label="${esc(title)}">${svg}</svg><div class="sd-legend">${keys.map(([,l,c])=>`<span style="--c:${c}">${esc(l)}</span>`).join('')}<small>${unit}</small></div>`;
  }
  function create({element,rows,models,research,meta,getCode,setCode,shared,go,initial}){
    const key='investment-company-detail-v1-'+meta.data_mode;
    const defaults={tab:'summary',basis:meta.financial_basis==='OFS'?'OFS':'CFS',cadence:'ttm',chart:'day',range:'126',ma:true,bb:false,env:false,expanded:false,statement:'income',reverse:false,filter:'all',band:'per',shown:['cap','revenue','op','net','eps','opMargin','netMargin','growth','opGrowth','roe','per','pbr','debt','yield','rs']};
    let state={...defaults,shown:[...defaults.shown]},settings=false,notice='';const editors={},financialViews={};
    if(!initial){try{initial=JSON.parse(sessionStorage.getItem(key)||'null');}catch{}}
    if(initial){const identity=rows.find(r=>r.code===initial.company?.code&&r.name===initial.company?.name&&r.market===initial.company?.market);if(identity)setCode(identity.code);for(const k of ['tab','basis','cadence','chart','range','statement','filter','band']){
      const valid={tab:tabs.map(t=>t[0]),basis:['CFS','OFS'],cadence:['ttm','annual','quarter'],chart:['day','week','month'],range:['63','126','252','all'],statement:['income','balance','cash'],filter:['all','disclosure','report','news'],band:['per','pbr','pcr']};if(valid[k].includes(initial[k]))state[k]=initial[k];}
      for(const k of ['ma','bb','env','reverse'])if(typeof initial[k]==='boolean')state[k]=initial[k];if(Array.isArray(initial.shown))state.shown=defaults.shown.filter(k=>initial.shown.includes(k));
    }
    const row=()=>rows.find(r=>r.code===getCode())||rows[0];
    const displayPrice=()=>{const chart=models[row().code].chart,last=chart.bars.at(-1);return last?{value:last.close,date:last.date,label:'저장 수정 종가'}:{value:row().metrics.price,date:meta.price_date,label:'검토 가격'};};
    const table=()=>shared.ebitda.apply(row(),shared.tables[row().code]);
    const inputGroup=()=>financialViews[row().code]||table().groups.find(g=>g.basis===state.basis&&g.cadence==='quarter')?.id||table().groups.find(g=>g.basis===state.basis)?.id;
    const periods=(cadence=state.cadence,basis=state.basis)=>E.periods(models[row().code],basis,cadence,table());
    const segments=(field,options)=>`<div class="sd-segments" aria-label="${esc(field)}">${options.map(([v,t])=>`<button data-sd-field="${field}" data-value="${v}" aria-pressed="${state[field]===v}">${esc(t)}</button>`).join('')}</div>`;
    const basis=()=>segments('basis',[['CFS','연결'],['OFS','별도']]);
    const cadence=()=>segments('cadence',[['ttm','TTM'],['annual','연간'],['quarter','분기']]);
    function jump(items){return `<nav class="sd-jump" aria-label="섹션 바로가기">${items.map(([id,t])=>`<button data-sd-jump="${id}">${esc(t)}</button>`).join('')}</nav>`;}
    function financialCharts(){return ['revenue','operating_profit','eps'].map((k,i)=>{
      const label=['매출액','영업이익','EPS (원)'][i],color=['#8172c7','#2d9c90','#5a87b7'][i];return `<section class="sd-trend-row"><h4>${label}</h4><div class="sd-grid"><div><p class="sd-muted">연간</p>${plot(periods('annual'),[[k,label,color]],label+' 연간 추이','bars',k==='eps'?'원':'억원')}</div><div><p class="sd-muted">분기별</p>${plot(periods('quarter'),[[k,label,color]],label+' 분기 추이','bars',k==='eps'?'원':'억원')}</div></div></section>`;}).join('');}
    function priceChart(){const model=models[row().code].chart;
      if(!model.bars.length)return empty(model.reason);
      const all=E.indicators(E.aggregate(model.bars,state.chart)),count=state.range==='all'?all.length:Math.ceil(Number(state.range)/(state.chart==='week'?5:state.chart==='month'?21:1)),ps=all.slice(-count),rs=E.relative(ps,model.benchmark);
      const paths=[...(state.ma?[['ma5','#c7a248'],['ma20','#8274c8'],['ma60','#3eaa99']]:[]),...(state.bb?[['bbHigh','#b494c6'],['bbLow','#b494c6']]:[]),...(state.env?[['envHigh','#df9848'],['envLow','#df9848']]:[])];
      const values=ps.flatMap(p=>[p.close,p.high,p.low,...paths.map(([k])=>p[k])].filter(E.num)),lo=Math.min(...values)*.98,hi=Math.max(...values)*1.02,span=hi-lo||1,x=i=>50+(i+.5)/ps.length*670,y=v=>290-(v-lo)/span*248;
      const hasCandles=ps.every(p=>['open','high','low'].every(k=>E.num(p[k]))),vols=ps.map(p=>p.volume).filter(E.num),vm=Math.max(1,...vols);let out='';
      for(let i=0;i<=4;i++){const v=lo+span*i/4;out+=`<path d="M50 ${y(v)}H728" stroke="#eceef1" stroke-dasharray="3 4"/><text x="738" y="${y(v)+4}">${fmt(v,0)}</text>`;}
      const width=Math.max(1,Math.min(12,670/ps.length*.65));
      if(hasCandles)out+=ps.map((p,i)=>{const color=p.close>=p.open?'#e15161':'#3971d6';return `<g><title>${esc(p.date)} 시 ${fmt(p.open,0)} 고 ${fmt(p.high,0)} 저 ${fmt(p.low,0)} 종 ${fmt(p.close,0)} 거래량 ${fmt(p.volume,0)}</title><path d="M${x(i)} ${y(p.high)}V${y(p.low)}" stroke="${color}"/><rect x="${x(i)-width/2}" y="${Math.min(y(p.open),y(p.close))}" width="${width}" height="${Math.max(1,Math.abs(y(p.open)-y(p.close)))}" fill="${color}"/></g>`;}).join('');
      else out+=`<path d="${ps.map((p,i)=>(i?'L':'M')+x(i)+','+y(p.close)).join(' ')}" fill="none" stroke="#6e66b2" stroke-width="2"/>`;
      for(const [k,c]of paths){let start=false;out+=`<path d="${ps.map((p,i)=>{if(!E.num(p[k])){start=false;return '';}const d=(start?'L':'M')+x(i)+','+y(p[k]);start=true;return d;}).join(' ')}" fill="none" stroke="${c}" stroke-width="1.3"/>`;}
      out+=`<path d="M50 ${y(ps.at(-1).close)}H728" stroke="#d65c8d" stroke-dasharray="4 4"/>`;
      out+=ps.map((p,i)=>E.num(p.volume)?`<rect x="${x(i)-width/2}" y="${351-p.volume/vm*45}" width="${width}" height="${p.volume/vm*45}" fill="${p.close>=(p.open??p.close)?'#e15161':'#3971d6'}"><title>${esc(p.date)} 거래량 ${fmt(p.volume,0)}주</title></rect>`:'').join('');
      out+='<text x="50" y="310">거래량 (주)</text>';
      const rv=rs.map(p=>p.rs).filter(E.num);if(rv.length){const rl=Math.min(...rv),rh=Math.max(...rv),ry=v=>410-(v-rl)/(rh-rl||1)*35;let start=false;out+=`<text x="50" y="374">지수 대비 상대가격 · 시작 100</text><path d="${rs.map((p,i)=>{if(!E.num(p.rs)){start=false;return '';}const d=(start?'L':'M')+x(i)+','+ry(p.rs);start=true;return d;}).join(' ')}" fill="none" stroke="#8172c7"/>`;}
      out+=`<text x="50" y="435">${ps[0].date}</text><text x="728" y="435" text-anchor="end">${ps.at(-1).date}</text>`;
      return `<p class="sd-chart-readout">${esc(ps.at(-1).date)} · 종가 <b>${fmt(ps.at(-1).close,0)}원</b> · ${hasCandles?'OHLC 캔들':'시가·고가·저가 미확보 · 종가 선'} · ${ps.length}개 관측 구간</p><svg class="sd-price-plot" viewBox="0 0 820 450" role="img" aria-label="${esc(row().name)} ${state.chart} 주가와 거래량">${out}</svg><p class="sd-muted">${esc(model.source)} · ${esc(model.as_of)}<br>MA 5·20·60 구간 · BB 20구간 평균 ± 2σ · ENV 20구간 평균 ± 5% · 주·월은 마지막 관측일 종가</p>`;
    }
    function summaryMetrics(){const r=row(),last=periods('quarter').at(-1),v=last?.values||{},f=research.rows?.[r.code]?.fundamental,t=research.rows?.[r.code]?.technical,metrics=state.basis===meta.financial_basis?r.metrics:{market_cap_eok:r.metrics.market_cap_eok};
      return {cap:['시가총액',money(metrics.market_cap_eok),meta.price_date],revenue:['매출액',money(v.revenue)],op:['영업이익',money(v.operating_profit)],net:['당기순이익',money(v.net_income)],eps:['EPS','—','주식수·동일 기간 EPS 필요'],opMargin:['영업이익률',unit(v.operating_margin,'%')],netMargin:['순이익률',unit(v.net_margin,'%')],growth:['매출성장률',unit(state.basis===meta.financial_basis?f?.metrics?.revenue_growth_pct:null,'%'),'검토 지표 기준'],opGrowth:['영업이익성장률','—','전년 동기 실적 필요'],roe:['ROE',unit(metrics.roe_pct,'%'),'기존 검토의 TTM 기준'],per:['PER',unit(metrics.per,'배'),r.valuation_details?.per?.reason],pbr:['PBR',unit(metrics.pbr,'배'),r.valuation_details?.pbr?.reason],debt:['부채비율',unit(v.debt_ratio,'%')],yield:['배당수익률',fmt(E.ratio(models[r.code].dividends.at(-1)?.dps,displayPrice().value,100))+'%'],rs:['가격 추세 순위',fmt(t?.price_strength?.score,2),t?.price_strength?.as_of+' · 저장 유효 표본 순위']};
    }
    function summary(){const metrics=summaryMetrics();return `<div class="sd-overview ${state.expanded?'expanded':''}"><section>${heading('주가 차트',`<button data-sd-toggle="expanded" aria-pressed="${state.expanded}">${state.expanded?'차트 축소':'차트 확장'}</button>`)}<div class="sd-box sd-chart"><div class="sd-chart-controls">${segments('chart',[['day','일'],['week','주'],['month','월']])}${['ma','bb','env'].map(k=>`<button data-sd-toggle="${k}" aria-pressed="${state[k]}">${k.toUpperCase()}</button>`).join('')}<label>표시 기간<select id="sdChartRange">${[['63','3개월'],['126','6개월'],['252','1년'],['all','전체']].map(([v,l])=>`<option value="${v}" ${state.range===v?'selected':''}>${l}</option>`).join('')}</select></label></div>${priceChart()}</div></section><section>${heading('요약 정보',`<small>기준 ${short(periods('quarter').at(-1)?.period_end)} · ${state.basis==='CFS'?'연결':'별도'}</small><button id="sdSettings" aria-label="요약 정보 표시 항목 설정">⚙</button>`)}<div class="sd-box sd-metrics">${state.shown.map(k=>card(...metrics[k])).join('')}</div></section></div>${settings?`<div class="sd-box sd-settings">${heading('요약 정보 항목 설정','<button id="sdSettingsClose">설정 닫기</button>')}<p class="sd-muted">표시할 항목을 선택합니다. 선택값은 같은 탭에서 유지됩니다.</p>${Object.entries(metrics).map(([k,[l]])=>`<label><input type="checkbox" data-sd-metric="${k}" ${state.shown.includes(k)?'checked':''}>${l}</label>`).join('')}<button id="sdSettingsReset">기본값으로 초기화</button></div>`:''}<section class="sd-section">${heading('재무 추이',basis())}<p class="sd-muted">관측 실적만 표시 · 단독분기와 연간 구분 · 전망치는 별도 자료 필요</p><div class="sd-box">${financialCharts()}</div></section><section class="sd-section">${heading('EPS 전망치 추이')}${empty('같은 회계기준·전망연도의 EPS와 수집일별 변경 이력이 필요합니다.')}</section><section class="sd-section">${heading('증권사 목표가','<button data-sd-tab="earnings">목표가 추이 보기 →</button>')}${empty('증권사별 목표가·발행일·투자의견 원자료가 필요합니다.')}</section>`;}
    function business(){const cs=periods(),v=cs.at(-1)?.values||{};return jump([['profile','기업 개요'],['sales','매출 분석'],['cost','비용 분석']])+`<section id="sd-profile" class="sd-section">${heading('기업 개요')}<div class="sd-box"><p><b>${esc(row().name)}</b> · ${esc(row().industry)} · ${esc(row().market)}</p><p class="sd-muted">검토 종목 분류: ${esc(row().security_type)} · ${esc(row().analysis_profile)}</p>${empty('사업 설명·발행주식수·외국인 지분율 원자료가 연결되면 여기에 표시합니다.')}</div>${heading('수주잔고 추이')}${empty('기간별 수주잔고와 사업보고서 원자료가 필요합니다.')}</section><section id="sd-sales" class="sd-section">${heading(row().name+' 매출 분석',basis()+cadence())}<div class="sd-overview"><article class="sd-box">${heading('매출 추이')}${plot(cs,[['revenue','매출액','#8274c8']],'매출 추이')}</article><article class="sd-box">${heading('실적 요약')}<div class="sd-stats">${card('매출액',money(v.revenue))}${card('영업이익',money(v.operating_profit),'영업이익률 '+unit(v.operating_margin,'%'))}${card('순이익',money(v.net_income),'순이익률 '+unit(v.net_margin,'%'))}</div></article></div>${heading('부문별 매출 비중 추이')}${empty('동일 기간의 사업부별 매출과 비중 자료가 필요합니다.')}${heading('부문별 매출')}${empty('사업부·매출액·전년 동기 비교값이 연결되지 않았습니다.')}</section><section id="sd-cost" class="sd-section">${heading(row().name+' 비용 분석',cadence())}<div class="sd-grid"><article class="sd-box">${heading('비용 구성')}${empty('매출원가·판매관리비를 구분하는 원계정이 필요합니다.')}</article><article class="sd-box">${heading('마진 추이')}${plot(cs,[['operating_margin','OPM','#2d9c90'],['net_margin','순이익률','#8274c8']],'마진 추이','line','%')}</article></div>${heading('비용 현황')}${empty('같은 기간 매출원가·판관비가 연결되면 비용 구성과 비율을 표시합니다.')}</section>`;}
    function flowDiagram(v){const entries=[['매출액',v.revenue],['영업이익',v.operating_profit],['순이익',v.net_income]];return `<div class="sd-flow">${entries.map(([l,value],i)=>`${i?'<span aria-hidden="true">→</span>':''}${card(l,money(value))}`).join('')}</div><details><summary>계산식·합계 확인</summary><p>영업이익률 = 영업이익 ÷ 매출액 × 100 · 순이익률 = 순이익 ÷ 매출액 × 100</p><p class="sd-muted">매출원가·영업외손익·세금 원계정이 없어 중간 비용 단계는 표시하지 않습니다.</p></details>`;}
    function statement(){let cs=periods(),defs=state.statement==='income'?[['revenue','매출액'],['operating_profit','영업이익'],['net_income','당기순이익'],['ebitda','EBITDA'],['interest_expense','이자비용'],['operating_margin','영업이익률','%'],['net_margin','순이익률','%']]:state.statement==='balance'?[['assets','자산총계'],['liabilities','부채총계'],['equity','자본총계'],['borrowings','차입금'],['total_borrowings','총차입금'],['debt_ratio','부채비율','%']]:[];
      if(state.reverse)cs=[...cs].reverse();return heading('재무제표',basis()+cadence())+`<div class="sd-box"><div class="sd-heading">${segments('statement',[['income','손익계산서'],['balance','재무상태표'],['cash','현금흐름표']])}<button data-sd-toggle="reverse">${state.reverse?'오래된순':'최신순'}으로 정렬</button></div>${!defs.length?empty('영업·투자·재무 현금흐름의 원계정이 필요합니다.'):!cs.length?empty('선택한 회계기준·기간의 재무제표가 없습니다.'):`<div class="sd-table-scroll" tabindex="0" aria-label="재무제표 좌우 스크롤"><table class="sd-table"><thead><tr><th>항목</th>${cs.map(c=>`<th>${short(c.period_end)}</th>`).join('')}</tr></thead><tbody>${defs.map(([k,l,u])=>`<tr><th><button data-sd-trend="${k}" aria-label="${l} 추세 차트">${l} ◷</button></th>${cs.map(c=>`<td title="${esc(c.source+' · '+(c.cell_notes?.[k]||''))}">${u?fmt(c.values[k])+u:money(c.values[k])}${c.cell_notes?.[k]&&E.num(c.values[k])?'*':''}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="sd-muted">손익: ${state.cadence==='quarter'?'단독 3개월':state.cadence==='ttm'?'연속 4개 단독분기의 실제 합계':'연간'} · 잔액: 기말 · * 원표 산출 범위 확인</p>`}<div id="sdRowTrend"></div></div>`;
    }
    function dividends(){const ds=models[row().code].dividends;return heading(row().name+' 배당')+(ds.length?`<div class="sd-box"><div class="sd-stats">${card('최근 연간 DPS',fmt(ds.at(-1).dps,0)+'원',ds.at(-1).period_end)}${card('표시 가격 기준 배당수익률',fmt(E.ratio(ds.at(-1).dps,displayPrice().value,100))+'%',displayPrice().date)}</div>${plot(ds.map(d=>({...d,values:{dps:d.dps}})),[['dps','주당배당금','#8274c8']],'연간 DPS 추이','bars','원')}</div>`:empty('연도별 보통주 DPS·배당성향 원자료가 필요합니다.'));}
    function financial(){const cs=periods(),v=cs.at(-1)?.values||{},metrics=row().metrics;return jump([['judgment','핵심 판정'],['profit','수익성'],['structure','재무 구조'],['cash','현금흐름'],['dividend','배당'],['statement','재무제표']])+`<section id="sd-judgment" class="sd-section">${heading(row().name+' 재무 분석',basis()+cadence())}<p class="sd-muted">${cs.length?short(cs[0].period_end)+' ~ '+short(cs.at(-1).period_end):'선택 기간 자료 미확보'} · TTM은 최근 4분기 합계 · 공개일 미확인 자료 포함</p><div class="sd-box sd-judgments"><div><h4>수익성</h4>${card('영업이익률',unit(v.operating_margin,'%'),'매출 100원당 영업이익 '+fmt(v.operating_margin)+'원')}${card('순이익률',unit(v.net_margin,'%'))}</div><div><h4>재무 구조</h4>${card('부채 부담',unit(v.debt_ratio,'%'),'자본 100원당 부채 '+fmt(v.debt_ratio)+'원')}${card('검토 유동비율',fmt(state.basis===meta.financial_basis?metrics.current_ratio_pct:null)+'%',meta.financial_period)}</div><div><h4>현금흐름</h4>${empty('영업현금·투자지출·기초/기말 현금 원자료 필요')}</div></div></section><section id="sd-profit" class="sd-section">${heading('수익성')}${heading('매출에서 순이익까지')}<div class="sd-box">${flowDiagram(v)}</div>${heading('매출 100원은 어디로 갔나')}<div class="sd-box">${plot(cs,[['operating_margin','영업이익률','#2d9c90'],['net_margin','순이익률','#8274c8']],'이익률 추이','line','%')}</div>${heading('ROE는 왜 변했나')}${empty('기간별 순이익·평균 자본·평균 자산의 같은 기준 자료가 필요합니다. 검토 ROE는 요약 정보에서 확인할 수 있습니다.')}</section><section id="sd-structure" class="sd-section">${heading('재무 구조')}${heading('무엇으로 조달해 무엇을 가졌나')}<div class="sd-box">${plot(cs,[['assets','자산','#8172c7'],['liabilities','부채','#bd9652'],['equity','자본','#2d9c90']],'자산 부채 자본 구성')}<p class="sd-muted">자산 = 부채 + 자본 · 기말 잔액 비교</p></div>${heading('늘어난 자산은 무엇으로 채웠나')}<div class="sd-box">${cs.length>=2?`<div class="sd-stats">${['assets','liabilities','equity'].map((k,i)=>card(['자산 증감','부채 증감','자본 증감'][i],E.num(cs[0].values[k])&&E.num(v[k])?money(v[k]-cs[0].values[k]):'—',short(cs[0].period_end)+' → '+short(cs.at(-1).period_end))).join('')}</div>`:empty('동일 기준의 기말 잔액 2개 이상이 필요합니다.')}</div></section><section id="sd-cash" class="sd-section">${heading('현금흐름')}${heading('번 돈을 어디에 썼나')}${empty('영업·투자·재무 현금흐름·기초/기말 현금 원자료가 연결되지 않았습니다.')}${heading('순이익이 현금이 되기까지')}${empty('비현금 조정·운전자본 증감 원자료가 필요합니다.')}</section><section id="sd-dividend" class="sd-section">${dividends()}</section><section id="sd-statement" class="sd-section">${statement()}</section><section class="sd-section">${table().groups.some(g=>g.basis===state.basis)?FinancialTableUI.render(row(),research,table(),inputGroup(),shared.ebitda,editors[row().code]||(editors[row().code]={})):empty('선택한 회계기준의 EBITDA 입력 대상 기간이 없습니다.')}</section>`;}
    function earnings(){const cs=periods('quarter');return jump([['earnings','실적'],['forecast','전망치 추이'],['analyst','애널리스트']])+`<section id="sd-earnings" class="sd-section">${heading('실적')}<p class="sd-muted">분기 실적 발표 · 전망치는 원자료 연결 필요</p><div class="sd-box sd-grid"><div>${heading('매출 전망치 대비 실적')}${plot(cs,[['revenue','관측 실적','#8172c7']],'분기 매출 실적')}${empty('발표 전 매출 전망치 미확보 · 서프라이즈 판정 대기')}</div><div>${heading('영업이익 전망치 대비 실적')}${plot(cs,[['operating_profit','관측 실적','#2d9c90']],'분기 영업이익 실적')}${empty('발표 전 영업이익 전망치 미확보 · 서프라이즈 판정 대기')}</div></div></section><section id="sd-forecast" class="sd-section">${heading(row().name+' 전망치 추이')}<div class="sd-overview"><article>${heading('전망치 수정 추이')}${empty('매출·영업이익·순이익·EPS 전망치의 수집일별 이력이 필요합니다.')}</article><article>${heading('전망치 수정 현황')}${empty('1개월 전·연도별 전망치와 수정률 원자료가 필요합니다.')}</article></div>${heading('연간 전망')}${empty('연도별 실적과 동일 기준의 전망치를 연결해야 합니다.')}</section><section id="sd-analyst" class="sd-section">${heading(row().name+' 애널리스트')}<div class="sd-stats">${card('리포트 수','—','증권사 원자료 미연결')}${card('평균 목표가','—')}${card('목표가 범위','—')}</div>${heading('목표가 추이')}${empty('증권사별 리포트 발행일·목표가 원자료 필요')}${heading('리포트 목록')}${empty('발행일·증권사·투자의견·목표가·제목·요약·원문 링크가 필요합니다.')}</section>`;}
    function valuation(){const r=row();return `<section class="sd-section">${heading(r.name+' 밸류에이션')}${heading('지금 가격의 위치')}<div class="sd-box"><p class="sd-muted">검토 가격 ${meta.price_date} · 같은 기준으로 검증된 평가값</p><div class="sd-stats">${['per','pbr'].map(k=>card(k.toUpperCase(),fmt(r.metrics[k],2)+'배',r.valuation_details?.[k]?.reason)).join('')}${card('PCR','—','영업현금흐름·주식수 필요')}</div><button id="sdDividend">배당 상세 보기 →</button></div>${heading(state.band.toUpperCase()+' 밴드',segments('band',[['per','PER'],['pbr','PBR'],['pcr','PCR']]))}${empty('과거 날짜별 '+state.band.toUpperCase()+' 분포와 당시 주당 재무값이 필요합니다. 현재 주식수를 과거에 고정하지 않습니다.')}${heading('RIM 적정가')}${empty('동일 기준 BPS·전망 EPS·요구수익률 원자료와 초과이익 가정이 필요합니다.')}${heading('시가총액 변화 요인')}${empty('동일 기간의 시가총액·최근 4분기 이익·발행주식수 이력이 필요합니다.')}${heading('밸류에이션 상세 지표')}<div class="sd-box"><div class="sd-stats">${card('검토 가격',fmt(r.metrics.price,0)+'원',meta.price_date)}${card('PER',fmt(r.metrics.per,2)+'배')}${card('PBR',fmt(r.metrics.pbr,2)+'배')}</div><p class="sd-muted">검증되지 않은 주당값·과거 배수는 생성하지 않습니다. 네이버 공개 참고값은 간단 분석의 보완 자료에서 출처와 함께 확인하세요.</p></div>${heading('동종업종 밸류에이션')}<div class="sd-box">${['per','pbr'].map(k=>{const peer=DiscoveryEngine.peers(rows,r,research,k);return card(k.toUpperCase()+' 중앙값',fmt(peer.median,2)+'배','동일 산업·기간·기준 '+peer.count+'개 · 5개 이상 필요');}).join('')}</div></section>`;}
    function news(){const items=E.eventList(research.rows?.[row().code]?.events,state.filter);return jump([['feed','공시·리포트·뉴스'],['insider','내부자 매매']])+`<section id="sd-feed" class="sd-section">${heading('공시·리포트·뉴스',segments('filter',[['all','전체'],['disclosure','공시'],['report','리포트'],['news','뉴스']]))}<p class="sd-muted">${meta.price_date} 이전 공개된 저장 자료 · 최신순</p><div class="sd-feed"><div class="sd-feed-list">${items.length?items.map((e,i)=>`<button data-sd-event="${i}"><small>${esc(e.published_on)} · ${e.kind==='disclosure'?'공시':e.kind==='report'?'리포트':'뉴스'}</small><b>${esc(e.title)}</b><span>${esc(e.source)}</span></button>`).join(''):empty('이 필터의 저장된 자료가 없습니다.')}</div><div class="sd-box" id="sdEventDetail">${items.length?eventDetail(items[0]):empty('공시·기사 항목을 선택하면 날짜·출처·원문 링크를 표시합니다.')}</div></div></section><section id="sd-insider" class="sd-section">${heading(row().name+' 내부자 거래')}${empty('임원·주요주주 소유상황 보고서에서 거래일·매수/매도·주식수·가격을 확인한 자료가 필요합니다.')}</section>`;}
    function eventDetail(e){return `<p class="sd-muted">${esc(e.published_on)} · ${esc(e.source)}</p><h4>${esc(e.title)}</h4><p>저장된 제목과 출처입니다. 내용은 원문에서 확인하세요.</p><a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">원문 보기 ↗</a>`;}
    function save(){try{sessionStorage.setItem(key,JSON.stringify({...state,company:{code:row().code,name:row().name,market:row().market}}));}catch{notice='화면 설정 복원이 제한됩니다. 입력값은 JSON 파일로 보관하세요.';}}
    function render(){const r=row();if(!r){element.innerHTML=empty('검토 기업 자료가 없습니다.');return;}save();const chart=models[r.code].chart,priceInfo=displayPrice(),price=priceInfo.value,pos=E.ratio(price-chart.low_52w,chart.high_52w-chart.low_52w,100);
      element.innerHTML=`<div class="sd-selector"><label>검토 기업<select id="sdCompany">${rows.map(x=>`<option value="${x.code}" ${x.code===r.code?'selected':''}>${esc(x.name)} · ${x.code}</option>`).join('')}</select></label><button data-sd-go="brief">간단 분석</button><button data-sd-go="holdings">보유 검토</button></div><header class="sd-stock-header"><div class="sd-name"><span class="sd-avatar" aria-hidden="true">${esc(r.name.slice(0,2))}</span><div><div class="sd-title"><h2>${esc(r.name)}</h2><small>${esc(r.code+' · '+r.market)}</small><button id="sdWatch" aria-label="${esc(r.name)} 관심종목" aria-pressed="${shared.isWatched(r.code)}">${shared.isWatched(r.code)?'★':'☆'}</button></div><b class="sd-stock-price">${unit(price,'원',0)}</b><small>${priceInfo.label} · ${priceInfo.date}</small></div></div><div class="sd-header-values">${card('시가총액',money(r.metrics.market_cap_eok))}${card('PER (TTM)',fmt(r.metrics.per,2)+'배')}<div class="sd-range"><span>52주 종가 범위</span><div>${fmt(chart.low_52w,0)} <i>${E.num(pos)?`<b style="left:${Math.max(0,Math.min(100,pos))}%"></b>`:''}</i> ${fmt(chart.high_52w,0)}</div><small>${esc(chart.reason)}</small></div></div></header><nav class="sd-tabs" aria-label="검토 상세분석 탭" role="tablist">${tabs.map(([id,t])=>`<button role="tab" id="sd-tab-${id}" aria-controls="sdContent" data-sd-tab="${id}" aria-selected="${state.tab===id}" tabindex="${state.tab===id?'0':'-1'}">${t}</button>`).join('')}</nav><p class="sd-muted" role="status">${esc(notice)}</p><div id="sdContent" role="tabpanel" aria-labelledby="sd-tab-${state.tab}">${({summary,business,financial,earnings,value:valuation,news})[state.tab]()}</div><details class="sd-source"><summary>출처·기간·미연결 자료 확인</summary><p>${esc(meta.financial_period+' · '+meta.financial_basis+' · 가격 '+meta.price_date)}</p>${models[r.code].notes.map(n=>`<p>${esc(n)}</p>`).join('')}<p>스탁이지 로그인 후 화면의 6개 탭과 배치를 참고했습니다. 원자료 미연결 항목은 자료 미연결로 표시하며 평가등급·전망치를 만들지 않습니다.</p></details>`;
      bind();
    }
    function bind(){const $=id=>element.querySelector('#'+id);
      $('sdCompany').onchange=e=>{setCode(e.target.value);settings=false;render();};$('sdWatch').onclick=()=>{shared.toggleWatch(row().code);render();};
      element.querySelectorAll('[data-sd-tab]').forEach(el=>el.onclick=()=>{state.tab=el.dataset.sdTab;settings=false;render();element.querySelector('#sd-tab-'+state.tab)?.focus();});
      element.querySelectorAll('[role=tab]').forEach(el=>el.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const i=tabs.findIndex(t=>t[0]===state.tab);state.tab=tabs[e.key==='Home'?0:e.key==='End'?5:(i+(e.key==='ArrowRight'?1:5))%6][0];render();element.querySelector('#sd-tab-'+state.tab).focus();});
      element.querySelectorAll('[data-sd-field]').forEach(el=>el.onclick=()=>{state[el.dataset.sdField]=el.dataset.value;if(el.dataset.sdField==='basis')delete financialViews[row().code];render();});element.querySelectorAll('[data-sd-toggle]').forEach(el=>el.onclick=()=>{state[el.dataset.sdToggle]=!state[el.dataset.sdToggle];render();});
      element.querySelectorAll('[data-sd-jump]').forEach(el=>el.onclick=()=>element.querySelector('#sd-'+el.dataset.sdJump)?.scrollIntoView({behavior:'smooth',block:'start'}));
      element.querySelectorAll('[data-sd-go]').forEach(el=>el.onclick=()=>go(el.dataset.sdGo));
      if($('sdChartRange'))$('sdChartRange').onchange=e=>{state.range=e.target.value;render();};
      if($('sdSettings'))$('sdSettings').onclick=()=>{settings=!settings;render();};if($('sdSettingsClose'))$('sdSettingsClose').onclick=()=>{settings=false;render();};
      if($('sdSettingsReset'))$('sdSettingsReset').onclick=()=>{state.shown=[...defaults.shown];render();};
      element.querySelectorAll('[data-sd-metric]').forEach(el=>el.onchange=()=>{state.shown=defaults.shown.filter(k=>element.querySelector(`[data-sd-metric="${k}"]`)?.checked);render();});
      if($('sdDividend'))$('sdDividend').onclick=()=>{state.tab='financial';render();$('sd-dividend').scrollIntoView();};
      element.querySelectorAll('[data-sd-trend]').forEach(el=>el.onclick=()=>{$('sdRowTrend').innerHTML=plot(periods(),[[el.dataset.sdTrend,el.textContent.replace(' ◷',''),'#8172c7']],el.textContent+' 추이');});
      const items=E.eventList(research.rows?.[row().code]?.events,state.filter);element.querySelectorAll('[data-sd-event]').forEach(el=>el.onclick=()=>{$('sdEventDetail').innerHTML=eventDetail(items[Number(el.dataset.sdEvent)]);element.querySelectorAll('[data-sd-event]').forEach(b=>b.classList.toggle('selected',b===el));});
      if(state.tab==='financial'){EbitdaEditor.bind(element,row(),shared.tables[row().code],inputGroup(),shared.ebitda,editors[row().code],render);if($('financialPeriodSelect'))$('financialPeriodSelect').onchange=e=>{financialViews[row().code]=e.target.value;editors[row().code]={};state.basis=e.target.value.split('-')[0];render();};}
    }
    return {render,state:()=>({...state})};
  }
  return {create};
})();
