'use strict';
const DashboardJourney=(()=>{
 const num=v=>typeof v==='number'&&Number.isFinite(v),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(v,d=1)=>num(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:d}):'—';
 const safeURL=u=>typeof u==='string'&&/^https:\/\/dart\.fss\.or\.kr\//.test(u);
 const links=urls=>(urls||[]).filter(safeURL).slice(-2).map(u=>` <a href="${esc(u)}" target="_blank" rel="noopener noreferrer">공시 원문 ↗</a>`).join('');
 const labels={revenue:'매출액',operating_profit:'영업이익',net_income:'순이익',roe_pct:'ROE',debt_ratio_pct:'부채비율',per:'PER',pbr:'PBR'};
 const defaults={query:'',market:'',industry:'',sort:'price_rs',direction:'desc'};
 const presets={growth:{label:'성장 + 강한 추세',values:{growthMin:'10',marginMin:'0',roeMin:'0',debtMax:'200',rsMin:'70',trend:true}},breakout:{label:'돌파 근접',values:{rsMin:'70',highMax:'5',trend:true}},improving:{label:'관심기업 중 개선',values:{improved:true}}};
 function health(r){const f=r.common_financial,h=r.collection_health||{};const missing=!f?['재무 기간']:Object.entries({...f.amounts,roe_pct:f.metrics?.roe_pct}).filter(([k,v])=>['revenue','operating_profit','net_income','roe_pct'].includes(k)&&!num(v)).map(([k])=>labels[k]);
  const reference=Object.values(f?.metric_details||{}).some(d=>d.within_tolerance);return {missing,status:h.status==='failed'?'조회 실패':h.status==='partial'?'일부 기간 대기':!f?'재무 미확보':missing.length?'일부 항목 대기':reference?'참고값 포함':'확보',period:f?.period,basis:f?.basis,reference};}
 function healthCard(r){const h=r.collection_health||{},v=health(r);return `<details class="panel below journey-health"><summary>자료 상태 · ${esc(v.status)} · ${esc(v.period||'기간 대기')} ${esc(v.basis||'')}</summary><p>누락: ${esc(v.missing.join(' · ')||'주요 금액·ROE 확보')} · 연속 4분기 ${r.common_financial?.ttm_complete?'확보':'대기'}</p><p class="psub">마지막 수집 성공 ${esc(h.last_success||'기록 없음')} · 마지막 조회 ${esc(h.last_checked||'기록 없음')} · 실패 기간 ${h.failed_periods||0}개</p><p class="psub">${esc(h.retry||'기업 선택 시 재무 조회 · 이후 일간 공시 점검')}${h.decision==='below_threshold'?' · 7% 미만 정정은 다음 반영 대기':''}${h.decision==='account_coverage_changed'?' · 계정 구성 변경 검토 대기':''}</p>${v.reference?'<p class="psub">허용오차 참고값 포함 · 항목별 출처 설명에서 원문 기간과 잔차를 확인할 수 있습니다.</p>':''}${links(h.source_urls)}</details>`;}
 function healthQueue(rows){const pending=rows.filter(r=>r.discovery_allowed!==false&&health(r).status!=='확보').sort((a,b)=>(a.common_financial?1:0)-(b.common_financial?1:0));return `<details class="journey-health-queue"><summary>기업별 자료 상태 · 확인할 기업 ${pending.length}개</summary><label>자료 상태 기업 검색<input data-health-search placeholder="기업명 또는 코드"></label><div data-health-list>${healthRows(pending.slice(0,20))}</div><p class="psub">최대 20개 표시 · 기업을 누르면 누락 항목과 갱신 기록을 확인합니다.</p></details>`;}
 function healthRows(rows){return rows.map(r=>`<button class="journey-row" data-journey-code="${esc(r.code)}"><span>${esc(r.name)}<small>${esc(r.code)}</small></span><span>${esc(health(r).status)}<small>${esc(r.common_financial?.period||'기간 대기')}</small></span></button>`).join('')||'<p class="psub">해당 기업 없음</p>';}
 function sectors(insights){const all=insights?.sectors||[],valid=all.filter(s=>num(s.short_rs?.['1m']?.score)).sort((a,b)=>b.short_rs['1m'].score-a.short_rs['1m'].score||a.industry.localeCompare(b.industry)),top=valid.slice(0,8);const total=all.reduce((a,s)=>a+(s.short_rs?.['1m']?.cap_eok||0),0);return `<p class="psub">순서: 1개월 업종 RS · 색상: 21거래일 수익률 · 막대: 탐색 업종 시총 비중 · 순위 유효 ${valid.length}/${all.length}개 업종</p><div class="journey-sectors">${top.map(s=>{const x=s.short_rs['1m'],share=total?x.cap_eok/total*100:0;return `<button data-journey-sector="${esc(s.industry)}" data-journey-market="${esc(s.market)}" class="${x.return_pct>=0?'positive':'negative'}"><b>${esc(s.industry)}</b><small>${esc(s.market)} · ${x.count}개</small><strong>${fmt(x.return_pct)}%</strong><span>RS ${fmt(x.score)} · 시총 ${fmt(share)}%</span><meter min="0" max="100" value="${share}" aria-label="시총 비중 ${fmt(share)}%"></meter></button>`;}).join('')||'<p class="psub">같은 시장 유효기업 5개 이상인 업종의 완료 가격 자료 대기</p>'}</div>`;}
 function capture(rows,research,day){return {day,items:Object.fromEntries(rows.map(r=>{const t=research.rows?.[r.code]?.technical||{},f=r.common_financial;return [r.code,{name:r.name,market:r.market,rs:t.short_rs?.['1m']?.score??null,trend:t.price_trend_status||t.status,period:f?.period,basis:f?.basis,priceDay:t.as_of}];}))};}
 function journal(rows,research,day,mode,storage){const key='investment-observations-v1-'+mode,current=capture(rows,research,day);let saved={},note='';try{saved=JSON.parse(storage.getItem(key)||'{}');}catch{}
  const valid=s=>s&&typeof s.day==='string'&&s.items&&typeof s.items==='object'&&!Array.isArray(s.items);
  const prior=valid(saved.current)&&saved.current.day<day?saved.current:valid(saved.previous)&&saved.previous.day<day?saved.previous:null;
  try{storage.setItem(key,JSON.stringify({current,previous:prior}));}catch{note='이 브라우저에서는 관측 기록 저장이 제한됩니다.';}
  return {current,previous:prior,note,events:diff(prior,current)};}
 function diff(before,after){if(!before)return [];const events=[];for(const [code,b] of Object.entries(after.items)){const a=before.items[code];if(!a||a.name!==b.name||a.market!==b.market)continue;
  if(a.period&&b.period&&a.basis===b.basis&&b.period>a.period)events.push({code,kind:'financial',text:`새 재무 ${a.period} → ${b.period}`});
  if(a.priceDay&&b.priceDay>a.priceDay){if(num(a.rs)&&num(b.rs)&&Math.abs(b.rs-a.rs)>=5)events.push({code,kind:'rs',delta:b.rs-a.rs,text:`1개월 RS ${fmt(a.rs)} → ${fmt(b.rs)} (${fmt(b.rs-a.rs)}점)`});if(['pass','fail'].includes(a.trend)&&['pass','fail'].includes(b.trend)&&a.trend!==b.trend)events.push({code,kind:'trend',text:b.trend==='pass'?'가격 추세 충족으로 전환':'가격 추세 이탈'});}}
  return events;}
 function changes(rows,watched,j){const selected=rows.filter(r=>watched(r.code)),events=(j?.events||[]).filter(e=>watched(e.code));for(const r of selected){const h=r.collection_health||{};if(h.decision==='new_reporting_period'&&h.decision_on&&h.decision_on<=j.current.day&&h.decision_on>=(j.previous?.day||j.current.day)&&!events.some(e=>e.code===r.code&&e.kind==='financial'))events.push({code:r.code,kind:'financial',text:`${h.decision_on} · 새 재무 기간 자료 확보`,urls:h.source_urls});if(h.decision==='material_revision'&&h.material_changes&&h.decision_on&&h.decision_on<=j.current.day&&h.decision_on>=(j.previous?.day||j.current.day))events.push({code:r.code,kind:'revision',text:`${h.decision_on} · 7% 이상·부호 전환 등 중요 정정 ${h.material_changes}개 계정 반영`,urls:h.source_urls});}
  return `<article class="panel below journey-changes"><h3>관심기업의 핵심 변화</h3><p class="psub">${j?.previous?esc(j.previous.day)+' → '+esc(j.current.day)+' 관측 비교':'첫 관측 기준을 저장했습니다. 다음 완료 가격일의 자료부터 비교합니다.'} · RS 5점 이상 변화 · ${esc(j?.note||'이 브라우저에서 마지막 두 관측일 보관')}</p>${events.length?events.slice(0,12).map(e=>`<p><button data-journey-code="${esc(e.code)}">${esc(rows.find(r=>r.code===e.code)?.name||e.code)}</button> ${esc(e.text)}${links(e.urls)}</p>`).join(''):`<p class="psub">${selected.length?'비교 가능한 자료에서 핵심 변화가 없습니다.':'별표로 관심기업을 추가하면 변화만 모아 보여줍니다.'}</p>`}${events.length>12?`<p class="psub">전체 ${events.length}건 중 최근 관측의 12건 표시</p>`:''}</article>`;}
 function growth(now,prior){return num(now)&&num(prior)&&prior>0?(now/prior-1)*100:null;}
 function adjacent(day,months){const d=new Date(day+'T00:00:00Z');return new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+months+1,0)).toISOString().slice(0,10);}
 function statements(table,basis,cadence){return (table?.groups||[]).find(g=>g.basis===basis&&g.cadence===cadence)?.columns||[];}
 function compareRows(rows,r){const f=r.common_financial;if(!f)return [];return rows.filter(x=>x.code!==r.code&&x.discovery_allowed!==false&&x.industry===r.industry&&x.common_financial?.period===f.period&&x.common_financial?.basis===f.basis).sort((a,b)=>Math.abs((a.metrics?.market_cap_eok||0)-(r.metrics?.market_cap_eok||0))-Math.abs((b.metrics?.market_cap_eok||0)-(r.metrics?.market_cap_eok||0))||a.code.localeCompare(b.code)).slice(0,5);}
 function company(r,rows,table,cadence='quarter'){const f=r.common_financial,basis=f?.basis||'CFS',cs=statements(table,basis,cadence),shown=cs.slice(-8),last=cs.at(-1),prev=cs.find(c=>c.period_end===adjacent(last?.period_end||'2000-01-01',cadence==='quarter'?-3:-12)),year=cs.find(c=>c.period_end===adjacent(last?.period_end||'2000-01-01',-12)),peers=compareRows(rows,r),keys=['revenue','operating_profit','net_income'];
  const bars=shown.flatMap(c=>keys.slice(0,2).map(k=>c.statement_values?.[k])).filter(num),max=Math.max(1,...bars.map(Math.abs));
  return `<article class="panel below journey-company"><div class="panel-heading"><h3>실적 흐름과 동종기업 비교</h3><label>실적 기간<select data-journey-cadence><option value="quarter" ${cadence==='quarter'?'selected':''}>단독분기</option><option value="annual" ${cadence==='annual'?'selected':''}>연간</option></select></label></div><p class="psub">${esc(basis)} · 금액 억원 · 매출 파랑 / 영업이익 초록 · 막대 길이는 절댓값, 음수는 부호·점선으로 구분</p>${shown.length?`<div class="journey-history">${shown.map(c=>`<div><span>${esc(c.period_end)}</span>${keys.slice(0,2).map(k=>{const v=c.statement_values?.[k];return `<div class="journey-bar ${k==='revenue'?'revenue':'profit'} ${v<0?'loss':''}" style="--bar:${num(v)?Math.abs(v)/max*100:0}%"><span>${labels[k]} ${fmt(v)}${num(v)?'':''}</span></div>`;}).join('')}</div>`).join('')}</div><div class="tscroll"><table><thead><tr><th>최신 ${esc(last.period_end)}</th><th>금액 (억원)</th><th>YoY</th>${cadence==='quarter'?'<th>QoQ</th>':''}</tr></thead><tbody>${keys.map(k=>`<tr><td>${labels[k]}</td><td>${fmt(last.statement_values?.[k])}</td><td>${fmt(growth(last.statement_values?.[k],year?.statement_values?.[k]))}%</td>${cadence==='quarter'?`<td>${fmt(growth(last.statement_values?.[k],prev?.statement_values?.[k]))}%</td>`:''}</tr>`).join('')}</tbody></table></div><p class="psub">전기 값이 0·음수이거나 비교기간이 없으면 증감률은 —입니다.${links(shown.map(c=>c.source_url))}</p>`:'<p class="psub">선택 기간의 검증된 재무 원자료를 불러오는 중이거나 미확보입니다.</p>'}<h4>같은 산업 · ${esc(f?.period||'기간 대기')} ${esc(f?.basis||'')} · 시총이 가까운 기업</h4>${peers.length?`<div class="tscroll"><table><thead><tr><th>기업</th><th>매출 YoY</th><th>영업이익률</th><th>ROE</th><th>부채비율</th></tr></thead><tbody>${[r,...peers].map(x=>`<tr><td><button data-journey-code="${esc(x.code)}">${x.code===r.code?'● ':''}${esc(x.name)}</button></td>${['revenue_growth_pct','operating_margin_pct','roe_pct','debt_ratio_pct'].map(k=>`<td title="${esc(x.common_financial?.metric_details?.[k]?.reason)}">${fmt(x.common_financial?.metrics?.[k])}%${x.common_financial?.metric_details?.[k]?.within_tolerance?' 참고':''}${k==='operating_margin_pct'&&Math.abs(x.common_financial?.metrics?.[k])>100?'<small>매출 범위 확인</small>':''}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="psub">비교기업 ${peers.length}개 · 연결/별도와 최신 분기를 맞췄습니다. ROE는 TTM, 나머지 손익 비율은 단독분기입니다. 같은 산업 분류라도 지주회사 등 사업 구조가 다를 수 있으며, 영업이익이 매출보다 큰 기업은 매출 범위를 확인하세요.</p>`:'<p class="psub">같은 산업·보고기간·회계 기준의 비교기업을 확보하지 못했습니다.</p>'}</article>`;}
 function bind(element,{go,search,rows=[]}){element.querySelectorAll('[data-journey-code]').forEach(b=>b.onclick=()=>go(b.dataset.journeyCode));element.querySelectorAll('[data-journey-sector]').forEach(b=>b.onclick=()=>search(b.dataset.journeySector,b.dataset.journeyMarket));element.querySelector('[data-health-search]')?.addEventListener('input',e=>{const q=e.target.value.toLocaleLowerCase();element.querySelector('[data-health-list]').innerHTML=healthRows(rows.filter(r=>r.discovery_allowed!==false&&`${r.name} ${r.code}`.toLocaleLowerCase().includes(q)).slice(0,20));bind(element.querySelector('[data-health-list]'),{go,search,rows});});}
 return {num,esc,fmt,links,defaults,presets,health,healthCard,healthQueue,sectors,capture,journal,diff,changes,growth,adjacent,compareRows,company,bind};
})();
if(typeof module!=='undefined')module.exports=DashboardJourney;
