'use strict';
const DashboardUpgradeUI=(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=v=>typeof v==='number'&&Number.isFinite(v),fmt=(v,d=1)=>num(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:d}):'—';
 function overview(element,{rows,research,insights}){
  const active=rows.filter(r=>r.discovery_allowed!==false),stored=active.filter(r=>r.common_financial),ttm=stored.filter(r=>r.common_financial.ttm_complete),roe=stored.filter(r=>num(r.common_financial.metrics.roe_pct)),ready=active.filter(r=>research.rows?.[r.code]?.technical?.price_health?.status==='ready');
  const observed=insights?.markets?.[0]?.as_of,day=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}),age=observed?Math.floor((Date.parse(day)-Date.parse(observed))/86400000):null;
  const freshness=age===null?'관측 날짜 확인 대기':age>7?'오래된 기준 자료 · '+observed+' · '+age+'일 전':'완료 관측 '+observed+' · 오늘 종가와 구분';
  element.innerHTML=`<article class="panel below"><div class="panel-heading"><h3>자료와 시장 환경</h3><span class="psub">재무 ${stored.length}/${active.length} · 연속 TTM ${ttm.length} · ROE ${roe.length} · 같은 날짜 가격 ${ready.length}/${active.length}</span></div><p class="psub">${esc(freshness)} · 새로운 완료 거래일은 자동 갱신 상태에서 확인합니다.</p><div class="grid2">${(insights?.markets||[]).map(m=>`<div><h4>${esc(m.market)} · ${esc(m.status)}</h4><p>200일선 위 ${fmt(m.above['200'].pct)}% <small>(${m.above['200'].count}/${m.above['200'].eligible})</small></p><p class="psub">상승 ${m.advancing} · 하락 ${m.declining} · 유효 ${m.valid}/${m.population} · ${esc(m.as_of)}</p></div>`).join('')}</div><details><summary>부족한 자료와 판정 기준</summary><p class="psub">재무는 최신 저장 단독분기와 연속 TTM 기준입니다. 연결 우선이며, 연결을 확보하지 못한 별도 자료는 OFS로 구분합니다. 미확보 ${active.length-stored.length}개 · 가격 대기 ${active.length-ready.length}개. 일부 과거 분기·지배주주 계정이 없으면 해당 비율은 —로 표시합니다. PER/PBR 근사는 주식수 불변 가정을 표시합니다. 검색·간단 분석은 같은 공통 지표를 사용합니다.</p><p class="psub">${esc(insights?.markets?.[0]?.definition||'공통 시장 관측 자료 대기')}</p><p class="psub">장후 일봉은 한국시간18:30 이후 제공자 자료와 양대 지수 관측일을 대조합니다. 원천 지연·휴장·정정 가능성이 있으며 공식 거래소 확정 보증은 아닙니다.</p></details></article>`;
 }
 function sectorTable(insights){const sectors=(insights?.sectors||[]).slice().sort((a,b)=>(b.short_rs['1m'].score??-1)-(a.short_rs['1m'].score??-1));return `<article class="panel below"><h3>업종 강도 · 단기 RS</h3><p class="psub">${esc(insights?.definition||'가격 이력 대기')}</p><div class="tscroll"><table><thead><tr><th>시장 / 산업</th><th>유효 기업</th><th>1개월 RS</th><th>3개월 RS</th><th>6개월 RS</th><th>1개월 가중 수익률</th></tr></thead><tbody>${sectors.map(s=>`<tr><td>${esc(s.market+' / '+s.industry)}</td><td>${s.count}</td>${['1m','3m','6m'].map(k=>`<td>${fmt(s.short_rs[k].score)}</td>`).join('')}<td>${fmt(s.short_rs['1m'].return_pct)}%</td></tr>`).join('')}</tbody></table></div></article>`;}
 function audit(model){const audit=model?.price_audit;if(!audit)return '';return `<details class="panel below"><summary>가격 출처·시장·수정 기준 대조</summary><p class="psub">${esc(audit.note)}</p>${audit.checks.length?`<div class="tscroll"><table><thead><tr><th>날짜</th><th>검토 저장 가격</th><th>네이버 차트</th><th>차이</th><th>기준</th></tr></thead><tbody>${audit.checks.map(c=>`<tr><td>${esc(c.date)}</td><td>${fmt(c.left_price,0)}원</td><td>${fmt(c.right_price,0)}원</td><td>${fmt(c.difference_pct,2)}%</td><td>${esc(c.status)}<small>${esc(c.left_venue||'시장 미확인')} / ${esc(c.left_basis||'보정 미확인')} → ${esc(c.right_venue)} / ${esc(c.right_basis)}</small></td></tr>`).join('')}</tbody></table></div>`:'<p class="psub">같은 날짜의 다른 원천 가격이 저장되지 않았습니다. 조회시각만 있는 최신 가격을 확정 종가와 동등하게 비교하지 않습니다.</p>'}<p class="psub">원천: ${esc(audit.source?.provider||'저장 이력')} · 관측 ${esc(audit.source?.fetched_at||'미확인')} · ${esc(audit.source?.adjustment_note||'보정 세부 확인 필요')}</p></details>`;}
 function short(t){return `<p class="psub">가격 관측 ${esc(t?.price_health?.observed_on||t?.as_of||'미확인')} · ${esc(t?.price_health?.reason||'공통 관측 기준 확인 대기')}</p><div class="rail">${['1m','3m','6m'].map((k,i)=>{const s=t?.short_rs?.[k];return `<div class="kpi"><span>${[1,3,6][i]}개월 RS</span><strong>${fmt(s?.score)}</strong><small>${fmt(s?.return_pct)}% · ${s?.days||[21,63,126][i]}거래일 · 유효 ${s?.eligible_count||0}개</small></div>`;}).join('')}</div><p class="psub">같은 거래소 저장 유효 기업 내 백분위 · 단기 상승 강도 참고값</p>`;}
 function reviewCards(r){return `<article class="panel below"><h3>추천 이유 · 반대 근거 · 유지 검토</h3><p class="psub">작성 당시의 수치 기준과 별도로 공식 사업 자료를 검토한 기록입니다. 과거 목표 비중과 편입 이유는 보존합니다.</p>${r.targets.map(t=>{const v=t.business_review||r.supplemental_reviews?.[t.code];return `<details class="journey-thesis"><summary>${esc(t.name)} · ${v?(v.stale?'사업 근거 재검토 시기':'사업 근거 확인'):'사업 근거 추가 검토'}</summary>${v?`<p class="psub">사업 검토 ${esc(v.reviewed_on)} · ${esc(v.method)}</p><p><b>확인한 사실</b> ${esc(v.fact)}</p><p><b>성장 가설</b> ${esc(v.thesis)}</p><p><b>반대 요인</b> ${esc(v.counter)}</p><p><b>유지 검토 조건</b> ${esc(v.keep)}</p><p class="psub">${(v.sources||[]).filter(x=>/^https:\/\//.test(x.url)).map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.title)} ↗</a> (${esc(x.published_on||'게시일 미명시')})`).join(' · ')}</p>`:'<p class="psub">재무·추세 기준 후보입니다. 사업 성장 원인은 아직 검토되지 않아 확정 설명을 붙이지 않았습니다.</p>'}<p class="psub">작성 당시 수치: ${esc(t.reason)}</p></details>`;}).join('')}${!r.targets.length?'<p>현재 종목 없는 현금안 · 자료 부족과 조건 미충족을 확인한 뒤 재검토하세요.</p>':''}${r.exclusion_reasons?`<details><summary>선별에서 제외한 이유</summary>${Object.entries(r.exclusion_reasons).map(([k,n])=>`<p>${esc(k)} · ${n}개</p>`).join('')}</details>`:''}</article>`;}
 function contributions(perf){return perf?.status==='ready'?`<h4>종목별 성과 기여</h4><div class="tscroll"><table><thead><tr><th>기업</th><th>가격 수익률</th><th>모델 기여도</th></tr></thead><tbody>${(perf.parts||[]).map(p=>`<tr><td>${esc(p.name)}</td><td>${fmt(p.return_pct,2)}%</td><td>${fmt(p.contribution_pct,2)}%p</td></tr>`).join('')}<tr><td>현금</td><td>0%</td><td>0%p</td></tr><tr><th>합계</th><td>—</td><th>${fmt(perf.return_pct,2)}%p</th></tr></tbody></table></div><p class="psub">기여도 = 작성 당시 비중 × 가격 수익률. 버전별 독립 모델이며 실제 보유 성과와 다릅니다.</p>`:'';}
 function recommendations(element,{live,go,onLoaded,onStatus}){
  let data={records:[]},selected=0,busy=false,message='',draft='';
  function render(){const rs=data.records,r=rs[selected]||rs.at(-1),perf=r?.performance;
   element.innerHTML=`<div class="section-title"><h2>성장형 월간 추천</h2><p>추천 목표와 실제 보유는 별도로 관리합니다.</p></div><article class="panel"><div class="panel-heading"><h3>${r?esc(r.month)+' · '+esc(r.kind==='monthly'?'월간 기준안':'월중 조정안'):'추천 작성 대기'}</h3><button data-rec-month ${busy||!live?'disabled':''}>이번 달 기준안 확인</button></div><p role="status" class="psub">${esc(message)} ${message&&live?'<button data-rec-retry>추천 기록 다시 불러오기</button>':''}</p>${r?`<label>추천 기록<select data-rec-version>${rs.map((v,i)=>`<option value="${i}" ${i===selected?'selected':''}>${esc(v.created_on)} · ${v.kind==='monthly'?'월간':'월중'} · ${i+1}차</option>`).join('')}</select></label><p class="psub">${esc(r.review_status)} · 작성 ${esc(r.created_on)} · 완료 종가 ${esc(r.price_date)}</p><p>${esc(r.reason)}</p><div class="tscroll"><table><thead><tr><th>기업</th><th>목표 비중</th><th>근거</th><th>재검토 조건</th></tr></thead><tbody>${r.targets.map(t=>`<tr><td><button data-rec-code="${esc(t.code)}">${esc(t.name)}</button><small>${esc(t.industry+' · '+t.financial_period)}</small></td><td>${fmt(t.weight_pct)}%</td><td>${esc(t.reason)}</td><td>${esc(t.risk)}</td></tr>`).join('')}<tr><td>현금</td><td>${fmt(r.cash_pct)}%</td><td colspan="2">미충족·자료 부족 슬롯은 현금 유지</td></tr></tbody></table></div><h4>이전 안에서 달라진 점</h4>${r.changes.length?`<ul>${r.changes.map(c=>`<li>${esc(c.name)} · ${esc(c.action)} · ${fmt(c.before_pct)}% → ${fmt(c.after_pct)}%<p class="psub">${esc(c.reason)}</p></li>`).join('')}</ul>`:'<p class="psub">종목 변경 없음</p>'}<h4>모델 성과 ${perf?.status==='ready'?fmt(perf.return_pct,2)+'%':'측정 대기'}</h4><p class="psub">${esc(perf?.definition||perf?.reason||'평가일 가격 대기')}${perf?.entry_date?' · 진입 '+esc(perf.entry_date)+' · 평가 '+esc(perf.as_of):''}</p>${perf?.status==='ready'?`<p class="psub">같은 기간 지수 ${Object.entries(perf.benchmark_returns||{}).map(([m,v])=>esc(m)+' '+fmt(v,2)+'%').join(' · ')} · 현금 포함 모델 성과와 비교</p>`:''}${contributions(perf)}<details><summary>선정 기준·가정·출처</summary><p>${esc(r.assumptions)}</p><p class="psub">${esc(r.method)}</p>${r.targets.map(t=>`<p class="psub">${esc(t.name)} · ${esc(t.sources.join(' / '))}${(t.source_urls||[]).filter(url=>/^https:\/\/dart\.fss\.or\.kr\//.test(url)).slice(-2).map(url=>` <a href="${esc(url)}" target="_blank" rel="noopener noreferrer">공시 원문 ↗</a>`).join('')}</p>`).join('')}</details>`:(live?'<p>저장된 월간 추천 기록을 불러오면 목표 구성이 표시됩니다.</p>':'<p>내보낸 화면에는 월간 추천 기록이 연결되지 않았습니다. <a href="http://127.0.0.1:8767/">연결 대시보드에서 추천 구성 확인 →</a></p>')}</article>${r?reviewCards(r):''}<form class="panel below" data-rec-exception><h3>월중 조정</h3><label>다음 정기 검토를 기다리지 않는 이유<textarea name="reason" maxlength="1000" required placeholder="새 실적·중요 공시·추세 변화 등">${esc(draft)}</textarea></label><button ${busy||!live?'disabled':''}>새 조정안 작성</button><p class="psub">기존 안을 보존하고 같은 자료 기준으로 다시 검토합니다. 입력한 이유와 종목별 편입·제외 근거를 기록합니다.</p></form>`;
   element.querySelector('[data-rec-retry]')?.addEventListener('click',()=>load());
   element.querySelector('[name=reason]').oninput=e=>{draft=e.target.value;};
   element.querySelector('[data-rec-version]')?.addEventListener('change',e=>{selected=+e.target.value;render();});element.querySelector('[data-rec-month]').onclick=()=>update('monthly','');element.querySelector('[data-rec-exception]').onsubmit=e=>{e.preventDefault();update('exception',new FormData(e.currentTarget).get('reason'));};element.querySelectorAll('[data-rec-code]').forEach(b=>b.onclick=()=>go('brief',b.dataset.recCode));
  }
  async function update(kind,reason){if(busy||!live)return;busy=true;message='저장 재무·완료 종가를 대조하는 중…';render();try{const r=await fetch('/recommendations',{method:'POST',headers:{'X-Dashboard-Token':live.token,'Content-Type':'application/json'},body:JSON.stringify({kind,reason})});if(!r.ok)throw Error((await r.json()).error||'추천 작성 대기');data=await r.json();selected=data.records.length-1;message='추천 기록 저장 완료';draft='';onLoaded?.(data);}catch(e){message=e.message||'추천 작성 연결 대기';}finally{busy=false;render();}}
  async function load(){message=live?'월간 추천 기록을 불러오는 중…':'월간 추천은 연결 대시보드에서 확인하세요.';onStatus?.(message);render();if(!live)return;try{const r=await fetch('/recommendations',{headers:{'X-Dashboard-Token':live.token},cache:'no-store'});if(!r.ok)throw Error();data=await r.json();selected=data.records.length-1;message='';onLoaded?.(data);render();const month=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}).slice(0,7);if(!data.records.some(r=>r.month===month&&r.kind==='monthly'))await update('monthly','');}catch{message='추천 기록을 불러오지 못했습니다. 다시 불러오기를 눌러 확인하세요.';onStatus?.(message);render();}}
  return {render,load};
 }
 return {overview,sectorTable,audit,short,recommendations};
})();
