'use strict';
const ResearchUI = (() => {
  const E=DiscoveryEngine, esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=(v,d=1)=>E.numeric(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:d}):'—';
  const baseLabels={roe_pct:'ROE',operating_margin_pct:'영업이익률',revenue_growth_pct:'매출 증가율',debt_ratio_pct:'부채비율',per:'PER',pbr:'PBR',market_cap_eok:'시가총액',price_rs:'가격 추세 순위',excess126_pct:'6개월 지수 초과수익',excess252_pct:'12개월 지수 초과수익'};
  const tableKeys=[...E.dimensions,'price_rs','excess126_pct','excess252_pct'];
  const unit=k=>['per','pbr'].includes(k)?'배':k==='market_cap_eok'?'억원':k==='price_rs'?'점':k.startsWith('excess')?'%p':'%';
  const blank=note=>`<div class="research-empty">${esc(note)}</div>`;
  const title=(heading,note)=>`<div class="section-title"><h2>${heading}</h2><p>${note}</p></div>`;
  const strengthSummary=s=>s?(s.status==='ready'?`${s.market||s.venue} · 저장 유효 ${s.eligible_count}/${s.universe_count}개 내 순위 · 전체 시장 순위 아님`:`저장 유효 ${s.eligible_count}/${s.universe_count}개 · ${s.market||s.venue||'거래소 미확인'} · ${s.reason}`):'확정 253거래일 이력과 유효 비교기업 5개 이상 필요';
  const strengthNote=s=>strengthSummary(s)+(s?.source_note?' · '+s.source_note:s?.source?' · 출처 '+s.source:'');
  function create({element,snapshot,research={},references={},insights=null,financialTables={},companyModels={},reviewedMeta=null,lazyTables=false,getCode,setCode,go,initial}){
    const rows=E.prepare(snapshot,research), meta=snapshot.meta, discovery=meta.discovery===true;
    const J=DashboardJourney,cadences={},presetKey='investment-presets-v1-'+meta.data_mode;
    let selectedPreset='',savedPresets=[];try{const v=JSON.parse(localStorage.getItem(presetKey)||'[]');if(Array.isArray(v))savedPresets=v.filter(x=>typeof x?.name==='string'&&x.filters&&typeof x.filters==='object').slice(0,8);}catch{}
    let observationStorage;try{observationStorage=localStorage;}catch{}
    const observations=J.journal(rows,research,new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}),meta.data_mode,observationStorage);
    const labels={...baseLabels,...(discovery?{per:'참고 PER',pbr:'참고 PBR'}:{})};
    const metricNote=(r,k)=>{const d=E.detail(r,research,k);return `출처 ${d.source||'미연결'} · 기간 ${d.period||'미확인'} · 기준 ${d.basis||'미확인'} · 관측 ${d.observed_on||'미확인'}${d.reason?' · '+d.reason:''}`;};
    const latestPrice=r=>r.latest_quote?`<p class="psub">최근 제공 가격 <b>${fmt(r.latest_quote.price,0)}원</b> · 조회 ${esc(r.latest_quote.retrieved_at)} · 시세시각/지연 미확인</p>`:'';
    const sourceNote=()=>discovery?`<p class="psub">${esc(meta.discovery_note||'기업 발굴용 공개 참고자료입니다. 보통주·비금융 분류를 확인할 후보가 포함됩니다. 인포맥스 우선 자료와 네이버 보완자료의 출처·기간을 개별 확인하세요.')}</p>`:'';
    let chartInstance=null;
    const chartStates={};
    let view='finder',watch=[],notice='',page=0,filters={query:'',market:'',industry:'',sort:'roe_pct',direction:'desc'};
    const financialViews={},financialEditors={};
    const ebitda=EbitdaInputs.create({dataMode:meta.data_mode,rows,tables:financialTables,initial:initial?.ebitda,lazyTables});
    const watchData=()=>({version:1,data_mode:meta.data_mode,companies:watch});
    const storageKey='investment-research-v1-'+meta.data_mode;
    if(!initial){try{initial=JSON.parse(sessionStorage.getItem(storageKey)||'null');}catch{}}
    if(initial){if(initial.filters&&typeof initial.filters==='object')for(const k of ['query','market','industry','sort','direction',...Object.keys(E.limits),'trend','highMax','improved'])if(['string','boolean'].includes(typeof initial.filters[k]))filters[k]=initial.filters[k];try{const restored=E.restoreWatch(initial.watch,rows,meta.data_mode);watch=restored.companies;if(restored.skipped)notice=`식별정보가 달라진 관심종목 ${restored.skipped}개 제외`; }catch{notice='이전 관심목록 복원 대기';}}
    if(initial?.charts&&typeof initial.charts==='object')for(const r of rows){const value=initial.charts[r.code];if(value&&typeof value==='object'&&!Array.isArray(value))chartStates[r.code]={...value};}
    const effective=()=>({...filters,watch:view==='watch'||filters.improved===true});
    const improved=r=>!filters.improved||observations.events.some(e=>e.code===r.code&&e.kind==='rs'&&e.delta>=5);
    const matches=()=>E.sort(E.filter(rows,effective(),research,watch).filter(improved),Object.hasOwn(labels,filters.sort)?filters.sort:'roe_pct',filters.direction);
    const row=()=>rows.find(r=>r.code===getCode())||rows[0];
    function financialContext(r){
      const model=companyModels[r.code];
      const matched=model&&model.code===r.code&&model.name===r.name&&model.market===r.market;
      const basis=matched?(model.common_financial?.basis||reviewedMeta?.financial_basis||meta.financial_basis):meta.financial_basis;
      // Discovery metadata deliberately has no global financial basis. A matched
      // reviewed company keeps its own basis without assigning it to candidates.
      const context={...meta,financial_basis:basis,financial_period:matched?(reviewedMeta?.financial_period||meta.financial_period):meta.financial_period};
      const latest=CompanyDetailEngine.periods(matched?model:null,basis,'quarter').at(-1);
      return {model:matched?model:null,meta:context,period:latest?.period_end?latest.period_end+' 단독분기':null,basis:latest?basis:null};
    }
    const badge=t=>discovery?`<span class="research-badge ${t?.price_trend_status==='pass'?'ok':''}">${t?.price_trend_status==='pass'?'기본 가격 배열 충족 · 거래대금 미확인':t?.price_trend_status==='fail'?'기본 가격 추세 미충족':'가격 추세 판단 대기'}</span>`:`<span class="research-badge ${t?.status==='pass'?'ok':''}">${t?.status==='pass'?'추세 조건 충족':t?.status==='fail'?'추세 조건 미충족':'추세 판단 대기'}</span>`;
    const name=r=>`<button class="company-link" data-research-code="${r.code}">${esc(r.name)}<small>${r.code} · ${esc(r.industry)}</small></button>`;
    const star=r=>`<button data-watch="${r.code}" aria-label="${esc(r.name)} 관심목록 ${watch.some(w=>w.code===r.code)?'제거':'추가'}" aria-pressed="${watch.some(w=>w.code===r.code)}">${watch.some(w=>w.code===r.code)?'★':'☆'}</button>`;
    function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
    function presetBar(){return `<div class="panel below journey-presets"><div class="research-actions">${Object.entries(J.presets).map(([k,v])=>`<button type="button" data-preset="${k}">${v.label}</button>`).join('')}</div><div class="research-actions below"><label>저장한 검색<select data-saved-preset><option value="">선택</option>${savedPresets.map((v,i)=>`<option value="${i}" ${String(i)===selectedPreset?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><label>검색 이름<input data-preset-name maxlength="40" placeholder="현재 적용 조건 이름"></label><button type="button" data-save-preset>현재 조건 저장</button><button type="button" data-delete-preset>선택 검색 삭제</button></div><p class="psub">${filters.improved?'관심기업 중 이전 관측 대비 1개월 RS가 5점 이상 오른 기업 · 비교 관측이 있어야 표시됩니다.':'성장: 매출 YoY≥10%, 영업이익률·ROE≥0%, 부채≤200%, RS≥70·추세 충족. 돌파 근접: 최고종가 대비 5% 이내·RS≥70·추세 충족.'} · 검색조건은 이 브라우저에 최대 8개 저장합니다.</p></div>`;}
    function why(r){const reasons=[];const f=effective();if(!f.watch&&r.discovery_allowed===false)reasons.push('시총·기업 탐색 범위 밖');if(f.market&&r.market!==f.market)reasons.push('시장 불일치');if(f.industry&&r.industry!==f.industry)reasons.push('산업 불일치');if(f.watch&&!watch.some(w=>w.code===r.code))reasons.push('관심목록 밖');for(const k of [...Object.keys(E.limits),'trend','highMax'])if(f[k]!==undefined&&f[k]!==''&&f[k]!==false&&!E.filter([r],{watch:true,[k]:f[k]},research,[r]).length)reasons.push(k==='trend'?'추세 미충족·대기':k==='highMax'?'최고종가 거리 미충족·대기':(labels[E.limits[k]?.[0]]||k)+' 조건 미충족·자료 대기');if(!improved(r))reasons.push('RS 개선 조건 미충족·비교 관측 대기');return reasons.length?reasons.join(' · '):'적용 조건 충족';}
    function exclusions(){const q=String(filters.query||'').trim().toLocaleLowerCase(),scope=rows.filter(r=>(!q||`${r.name} ${r.code}`.toLocaleLowerCase().includes(q))&&(!filters.industry||r.industry===filters.industry)),excluded=scope.filter(r=>why(r)!=='적용 조건 충족');return `<details class="panel below"><summary>후보에서 제외된 이유 · ${excluded.length}개</summary>${excluded.slice(0,8).map(r=>`<p>${name(r)} ${esc(why(r))}</p>`).join('')}<p class="psub">기업명·산업 범위 안에서 최대 8개 표시 · 검색어로 특정 기업을 확인하세요.</p></details>`;}
    function filterForm(){
      const selects=[['market','시장',[...new Set(rows.map(r=>r.market))]],['industry','산업',[...new Set(rows.map(r=>r.industry))]]];
      const rangeLabels={roeMin:'ROE 최소 (%)',marginMin:'영업이익률 최소 (%)',growthMin:'매출 증가율 최소 (%)',debtMax:'부채비율 최대 (%)',perMax:'PER 최대 (배)',pbrMax:'PBR 최대 (배)',rsMin:'가격 추세 순위 최소 (점)',highMax:'52주 최고 대비 하락폭 최대 (%)'};
      return `<form id="discoveryFilters" class="panel research-filters"><label>기업명 · 코드<input name="query" value="${esc(filters.query)}" placeholder="전체 저장 기업 검색"></label>${selects.map(([key,label,values])=>`<label>${label}<select name="${key}"><option value="">전체</option>${values.sort().map(v=>`<option value="${esc(v)}" ${filters[key]===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`).join('')}<label>정렬 지표<select name="sort">${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${filters.sort===k?'selected':''}>${v}</option>`).join('')}</select></label><label>정렬 방향<select name="direction"><option value="desc" ${filters.direction==='desc'?'selected':''}>큰 값부터</option><option value="asc" ${filters.direction==='asc'?'selected':''}>작은 값부터</option></select></label><details class="research-range" ${Object.keys(rangeLabels).some(k=>filters[k]!==undefined&&filters[k]!=='')||filters.trend?'open':''}><summary>수익성 · 재무 · 가격 · 추세 조건</summary><div class="research-range-grid">${Object.entries(rangeLabels).map(([key,label])=>`<label>${label}<input name="${key}" type="number" step="any" ${['debtMax','perMax','pbrMax','highMax'].includes(key)?'min="0"':''} value="${esc(filters[key]??'')}" placeholder="제한 없음"></label>`).join('')}<label class="research-check"><input name="trend" type="checkbox" ${filters.trend?'checked':''}>${discovery?'가격 추세 조건 충족만':'기존 추세 조건 충족만'}</label></div></details><div class="research-actions"><button type="submit" class="research-primary">조건 적용</button><button type="button" id="discoveryReset">조건 초기화</button></div><p class="control-scope">기본 조건은 비어 있습니다. 조건을 적용하면 해당 수치가 없는 기업은 제외됩니다. 낮은 PER/PBR만으로 저평가를 확정하지 않습니다.</p></form>`;
    }
    function list(){
      const found=matches(),pages=Math.max(1,Math.ceil(found.length/25));page=Math.min(page,pages-1);const shown=found.slice(page*25,(page+1)*25);
      const searchable=rows.filter(r=>r.discovery_allowed!==false);
      const complete=searchable.filter(r=>E.metric(r,'per')>0&&E.metric(r,'pbr')>0).length;
      return title(view==='watch'?'관심 기업':'좋은 기업, 합리적인 가격','수익성·재무 체력·가치평가를 확인하고 추세 분석으로 이어갑니다.')+`<div class="rail research-kpis">${[[discovery?'발굴 대상 기업':'분석 가능 기업',searchable.length+'개',discovery?'시가총액 850억원 초과 · 분류 확인 필요':'국내 보통주 · 비금융'],[discovery?'참고 PER · PBR 확보':'PER · PBR 확보',complete+'개',discovery?'양수 참고값 · 재무 기간·기준 별도 확인':'기준이 확인된 양수 수치'],['조건에 맞는 기업',found.length+'개','사용자 조건에 따른 검색 결과'],['관심 기업',watch.length+'개','같은 탭 새로고침 유지 · 파일 저장 가능']].map(([a,b,c])=>`<div class="kpi"><span>${a}</span><strong>${b}</strong><small>${c}</small></div>`).join('')}</div>`+sourceNote()+presetBar()+(view==='watch'?J.changes(rows,c=>watch.some(w=>w.code===c),observations):'')+filterForm()+exclusions()+`<article class="panel below"><div class="panel-heading"><h3>${view==='watch'?'관심목록':'후보 기업'}</h3><div class="research-actions"><button id="watchExport">관심목록 저장</button><label class="research-file">관심목록 불러오기<input id="watchImport" type="file" accept="application/json,.json"></label></div></div><p class="psub">표시 ${shown.length} / 필터 결과 ${found.length}개 · ${page+1}/${pages}페이지 · CSV에는 필터 결과 전체를 저장합니다.</p>${shown.length?`<div class="tscroll"><table id="discoveryTable"><thead><tr><th>관심 / 기업</th>${tableKeys.map(k=>`<th>${labels[k]} (${unit(k)})</th>`).join('')}<th>추세 확인</th></tr></thead><tbody>${shown.map(r=>`<tr><td><div class="research-company">${star(r)}${name(r)}</div>${latestPrice(r)}<small>${esc(why(r))} · ${esc(J.health(r).status)}</small></td>${tableKeys.map(k=>`<td title="${esc(k==='price_rs'?strengthNote(research.rows?.[r.code]?.technical?.price_strength):k.startsWith('excess')?'종목 수익률 − 해당 시장 지수 수익률 (%p)':metricNote(r,k))}">${fmt(E.metric(r,k))}</td>`).join('')}<td>${badge(research.rows?.[r.code]?.technical)}</td></tr>`).join('')}</tbody></table></div>`:blank('현재 조건에 맞는 기업이 없습니다. 조건을 줄이거나 필요한 데이터를 보완하세요.')}<div class="research-actions below"><button id="researchPrev" ${page===0?'disabled':''}>이전</button><button id="researchNext" ${page>=pages-1?'disabled':''}>다음</button></div></article>`;
    }
    function selector(r){return `<div class="panel controls"><label>분석 기업<select id="researchCompany">${rows.filter(x=>x.discovery_allowed!==false||watch.some(w=>w.code===x.code)||x.code===r?.code).map(x=>`<option value="${x.code}" ${r?.code===x.code?'selected':''}>${esc(x.name)} · ${x.code}</option>`).join('')}</select></label>${r?star(r):''}<button data-research-go="brief">간단 분석</button><button data-research-go="trend">추세 확인</button><button data-research-go="company" ${r?.legacy_available===false?'disabled title="검증된 기존 저장기업 자료 연결 필요"':''}>검토 상세분석</button></div>`;}
    function metricCard(r,k){const p=E.peers(rows,r,research,k);return `<div class="focus-row"><span>${labels[k]}</span><b>${fmt(E.metric(r,k))} ${unit(k)}</b></div><p class="psub">동일 산업·기간·기준의 다른 기업 ${p.count}개${p.median===null?' · 기간·기준 확인 및 비교기업 5개 이상 필요':` · 중앙값 ${fmt(p.median)} ${unit(k)}`}</p>${discovery?`<p class="psub">${esc(metricNote(r,k))}</p>`:''}`;}
    function brief(){const r=row();if(!r)return title('기업 간단 분석','저장 기업이 없습니다.')+blank('스냅샷 입력 대기');const data=research.rows?.[r.code]||{},f=data.fundamental||{},t=data.technical,financial=financialContext(r);
      return title(esc(r.name)+' · 간단 분석',`${esc(r.market)} / ${esc(r.industry)} · 보고기간 ${esc(financial.period||f.period||'미확인')} · ${esc(financial.basis||f.basis||'미확인')}`)+selector(r)+latestPrice(r)+sourceNote()+J.healthCard(r)+CompanyDetailUI.metricCards(r,financial.model,research,financial.meta)+J.company(r,rows,financial.model?financialTables[r.code]:null,cadences[r.code]||'quarter')+`<article class="panel below"><div class="panel-heading"><h3>완료 종가와 가격 추세</h3><button data-research-go="trend" class="link">추세 상세 →</button></div>${chart(t)}</article><details class="panel below"><summary>판단 근거와 보완할 자료</summary>${['per','pbr'].map(k=>{const v=discovery?{...E.detail(r,research,k),value:E.metric(r,k),price_date:E.detail(r,research,k).observed_on}:r.valuation_details?.[k]||{};return `<div class="research-evidence"><b>${labels[k]} ${fmt(v.value)}배</b><p>${esc(v.reason||'검증된 자료 대기')}</p><small>출처 ${esc(v.source||'미연결')} · 가격 ${esc(v.price_date||'미확인')} · 재무 ${esc(v.period||'미확인')} · ${esc(v.basis||'미확인')} / ${esc(v.period_type||'기간 미확인')}</small></div>`;}).join('')}<div class="research-evidence"><h3>가격 추세 순위 · 주지표</h3><b>${fmt(t?.price_strength?.score,2)}점</b><p>${esc(strengthNote(t?.price_strength))}</p></div><div class="research-evidence">${badge(t)}<p>${esc(t?.reason||'가격 이력 대기')}</p><p>보조지표 · 6개월 지수 초과수익 ${fmt(t?.rs126_pct)}%p · 12개월 ${fmt(t?.rs252_pct)}%p</p></div><p class="psub">${esc(research.rs_label||'가격 추세 순위 + 지수 초과수익')}</p></details>`+naver(r)+events(r,data.events||[])+`<article class="panel below"><div class="panel-heading"><h3>보유 · 포트폴리오 검토</h3><button data-research-go="holdings" ${r.legacy_available===false?'disabled title="검증된 기존 저장기업 자료 연결 필요"':''}>보유 유지·매도 검토 →</button></div><p class="psub">최대 5종목 구성과 기업·산업 집중도는 기존 포트폴리오 화면에서 확인합니다. 가격·검토 근거가 부족하면 판단 대기로 유지합니다.</p><button data-research-go="portfolio" ${r.legacy_available===false?'disabled title="검증된 기존 저장기업 자료 연결 필요"':''}>포트폴리오 구성 →</button></article>`;
    }
    function naver(r){const ref=references[r.code];if(!ref)return '';return `<article class="panel below research-reference"><div class="panel-heading"><h3>네이버 증권 · 보완 자료</h3><a href="${esc(ref.url)}" target="_blank" rel="noopener noreferrer">출처 보기 ↗</a></div><p class="psub">네이버 관측 ${esc((ref.price_time||ref.price_date||'미확인').replace('T',' ').replace('+09:00',' KST'))} · 조회 ${esc((ref.retrieved_at||ref.retrieved_on||'미확인').replace('T',' ').replace('+09:00',' KST'))} · ${ref.final===true?'원천 상태 확인':'확정 종가로 사용하지 않는 참고값'}</p><div class="research-reference-values">${[['price','관측 가격','원'],['per','PER','배'],['pbr','PBR','배'],['eps','EPS','원/주'],['bps','BPS','원/주']].map(([k,label,u])=>`<div><span>${label}</span><strong>${fmt(ref[k],k==='price'?0:2)} <small>${u}</small></strong></div>`).join('')}</div><p class="psub">${esc(ref.reason||'네이버 공개 화면의 참고 수치입니다.')} ${discovery?'발굴 화면은 인포맥스 우선 수치와 부족한 항목의 네이버 참고값을 표시합니다. 참고값의 재무 기간·기준을 확인해야 합니다.':'기본 분석은 '+esc(meta.price_date)+' 기준 인포맥스 우선 자료를 사용합니다. 이 참고값은 조건검색·포트폴리오 판단에 자동 합산하지 않습니다.'}</p><p class="psub">재무 기간 ${esc(ref.financial_period||'원천 미명시')} · 연결/별도 ${esc(ref.financial_basis||'원천 미명시')}</p><details><summary>EPS·BPS 산출 기준</summary><p class="psub">EPS: ${esc(ref.eps_basis)}<br>BPS: ${esc(ref.bps_basis)}<br>추정 PER·EPS는 표시 수치로 대체하지 않습니다.</p></details></article>`;}
    function events(r,items){return `<article class="panel below"><h3>저장된 공시 · 뉴스</h3><p class="psub">${esc(meta.price_date)} 기준 공개된 자료 · 최대 20건 · 원문에서 내용을 확인하세요.</p>${items.length?`<ul class="research-events">${items.map(e=>`<li><span>${esc(e.published_on)} · ${e.kind==='disclosure'?'공시':'뉴스'} · ${esc(e.source)}</span><a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">${esc(e.title)}</a></li>`).join('')}</ul>`:blank('이 기업의 기준일 이전 공개 기사·공시가 연결되지 않았습니다. 기존 공시·뉴스 관리에서 수집한 자료를 사용합니다.')}</article>`;}
    function trendAnalysis(t){
      const a=t?.trend_analysis;if(!a)return null;
      const score=t?.price_strength?.score,checks=a.checks.map(c=>c.id==='rs'?{...c,value:score,status:!E.numeric(score)?'unknown':score>=70?'pass':'fail'}:c);
      return {...a,checks,passed:checks.filter(c=>c.status==='pass').length,status:a.blocked?'unknown':checks.some(c=>c.status==='fail')?'fail':checks.some(c=>c.status==='unknown')?'unknown':'pass'};
    }
    function trendDiagnostics(t){
      const a=trendAnalysis(t);if(!a)return `<article class="panel below">${blank(t?.series_pending?'선택 기업의 가격 진단을 불러오는 중…':'추세 점검에 필요한 연속 가격 자료를 확인하세요.')}</article>`;
      const state=v=>v===true?'수축 관측':v===false?'수축 조건 미충족':'자료 확인 대기';
      const failed=a.checks.filter(c=>c.status==='fail').map(c=>c.label),unknown=a.checks.filter(c=>c.status==='unknown').map(c=>c.label);
      return `<article class="panel below" id="trendDiagnostics"><div class="panel-heading"><h3>미너비니 참고 · 종가 기준 점검</h3><span class="research-badge ${a.status==='pass'?'ok':''}" data-trend-health>${a.passed}/8 조건 충족${a.blocked?' · 거래 없음':a.status==='unknown'?' · 확인 대기':a.status==='fail'?' · 보완 필요':''}</span></div><p class="trend-phase" data-trend-phase>단기 위치 · ${esc(a.phase)}</p><div class="trend-metrics">${[['52주 최고종가 대비',fmt(a.drawdown_pct)+'%'],['50일선과 거리',fmt(a.extension50_pct)+'%'],['20일 종가 돌파선',fmt(a.pivot,0)+'원'],['당일 거래량 / 직전 50일 평균',E.numeric(a.volume_multiple)?fmt(a.volume_multiple,2)+'배':'미확보']].map(([label,value])=>`<div><span>${label}</span><strong>${value}</strong></div>`).join('')}</div>${failed.length?`<p class="psub">미충족: ${esc(failed.join(' · '))}</p>`:''}${unknown.length?`<p class="psub">확인 대기: ${esc(unknown.join(' · '))}</p>`:''}<details class="below"><summary>8개 조건과 계산 근거</summary><div class="trend-checks">${a.checks.map(c=>`<div data-trend-check="${c.id}" class="trend-check ${c.status}"><span>${esc(c.label)}</span><b>${c.status==='pass'?'충족':c.status==='fail'?'미충족':'대기'}</b><small>${E.numeric(c.value)?fmt(c.value,c.unit==='원'?0:2)+c.unit:'—'}</small></div>`).join('')}</div><p class="psub">52주 범위는 장중 고가·저가가 아닌 완료 종가입니다. 저점 대비 +30%, 고점 대비 -25%, 자체 RS 70을 쓰는 연구용 변형입니다. 공식 IBD RS·스탁이지 MMT·미너비니 SEPA 전체와 같은 판정이 아닙니다.</p><p class="psub">스탁이지 공개식 근접도(최고가 ≤ 종가×1.25)를 종가에 적용: ${a.mmt_status==='pass'?'5조건 충족':a.mmt_status==='fail'?'미충족':'자료 대기'}. 이는 고점 대비 -20% 이내에 해당하며 위의 -25% 조건과 다릅니다.</p><a href="https://stockeasy.intellio.kr/guide/rs" target="_blank" rel="noopener noreferrer">스탁이지 공개 조건 ↗</a> · <a href="https://cdn.minervini.com/static/dist/mtp-review.1f8e8633.pdf" target="_blank" rel="noopener noreferrer">미너비니 추세·VCP 설명 ↗</a></details><details class="below"><summary>눌림·돌파 준비 점검</summary><div class="focus-row"><span>돌파선까지 거리</span><b>${fmt(a.pivot_gap_pct)}%</b></div><div class="focus-row"><span>최근 10일 / 60일 수익률 변동성</span><b>${E.numeric(a.volatility_ratio)?fmt(a.volatility_ratio,2)+'배':'—'}</b></div><div class="focus-row"><span>최근 5일 / 50일 평균 거래량</span><b>${E.numeric(a.volume_dry_ratio)?fmt(a.volume_dry_ratio,2)+'배':'—'}</b></div><div class="focus-row"><span>앞선 → 최근 10일 종가 범위</span><b>${a.ranges_pct?.length?a.ranges_pct.map(x=>fmt(x)+'%').join(' → '):'—'}</b></div><p class="psub">${state(a.contraction)} · 세 10일 구간의 범위가 연속 축소되고 변동성·거래량 비율이 각각 0.7 미만이면 수축을 표시합니다. VCP 패턴의 확정 판정이 아닙니다.</p><p class="psub">돌파선은 오늘을 제외한 직전 20거래일 최고종가입니다. 선 위 종가와 직전 50일 평균 대비 거래량 1.5배 이상을 구분합니다. 거래대금·세부 수정 기준은 미확인이며 최신 조회 가격으로 종가 판정을 바꾸지 않습니다.</p></details></article>`;
    }
    function chart(t){return t?.series?.length?'<div class="interactiveTrendChart"></div>':blank('완료 가격 이력 조회 중');}
    function trend(){const r=row(),t=research.rows?.[r?.code]?.technical;if(!r)return blank('분석 기업 대기');return title(esc(r.name)+' · 추세 확인',discovery?'공개 일별 가격 · 이동평균 · 종가 기준 52주 최고':'확정 수정주가 · 이동평균 · 종가 기준 52주 최고')+selector(r)+latestPrice(r)+trendDiagnostics(t)+`<article class="panel below">${badge(t)}<p class="psub">${esc((discovery?t?.price_trend_reason:t?.reason)||'가격 이력 대기')} · 관측 ${t?.history_count||0}건${t?.source_note?' · '+esc(t.source_note):''}</p>${chart(t)}</article>${typeof DashboardUpgradeUI!=='undefined'?DashboardUpgradeUI.short(t)+DashboardUpgradeUI.financialSeries(companyModels[r.code]?.chart?.time_series)+DashboardUpgradeUI.audit(companyModels[r.code]):''}<div class="grid2 below"><article class="panel"><h3>추세·돌파 조건</h3>${[[discovery?'공개 일별 종가':'수정종가',fmt(t?.close,0)+'원'],...['50','150','200'].map(n=>[n+'일 이동평균',fmt(t?.sma?.[n],0)+'원']),['52주 최고 종가',fmt(t?.high_52w_close,0)+'원'],['최고 대비 거리',fmt(t?.gap_to_52w_high_pct)+'%'],['52주 최저 종가',fmt(t?.trend_analysis?.low_52w_close,0)+'원']].map(([a,b])=>`<div class="focus-row"><span>${a}</span><b>${b}</b></div>`).join('')}<p class="psub">${esc(t?.high_52w_reason||'52주 거래일 확인 대기')}</p></article><article class="panel"><h3>가격 추세 순위 · 주지표</h3><div class="research-rs"><strong>${fmt(t?.price_strength?.score,2)}</strong><span> / 99.99점</span></div><p class="psub">${esc(strengthNote(t?.price_strength))}</p><div class="focus-row"><span>분기 가중 가격수익률</span><b>${fmt(t?.price_strength?.weighted_return_pct)}%</b></div><details class="below"><summary>계산식과 순위 범위</summary><p class="psub">63거래일씩 나눈 4개 분기의 독립 수익률을 (최근 분기×2 + 나머지 세 분기) ÷ 5로 합산합니다. 약 12개월(252거래일) 기준입니다. 같은 거래소의 저장 유효 기업에서 동률 중간 백분위로 변환합니다. 유효 기업 5개 이상일 때만 순위를 표시합니다.</p><p class="psub">화면 필터를 바꿔도 순위 모집단은 바뀌지 않습니다. 전체 시장 순위가 아닙니다. 스탁이지 공개 설명을 참고한 자체 계산이며 동일 수치를 보장하지 않습니다.</p><a href="https://stockeasy.intellio.kr/guide/rs" target="_blank" rel="noopener noreferrer">스탁이지 공개 정의 ↗</a></details><h3 class="below">지수 초과수익 · 보조지표</h3><div class="focus-row"><span>126거래일 (약 6개월)</span><b>${fmt(t?.rs126_pct)}%p</b></div><div class="focus-row"><span>252거래일 (약 12개월)</span><b>${fmt(t?.rs252_pct)}%p</b></div><p class="psub">종목 수익률 − 해당 시장 지수 수익률. 양수이면 해당 기간 지수보다 높은 수익률입니다.</p><p class="psub">${discovery?'가격 추세 조건: 종가 &gt; 50일 &gt; 150일 &gt; 200일 평균, 200일 평균 상승, 6개월 수익률·지수 초과수익 양수. 기존 전략의 20일 평균 거래대금 10억원 조건은 자료 확인 대기입니다.':'기존 추세 조건: 종가 &gt; 50일 &gt; 150일 &gt; 200일 평균, 200일 평균 상승, 6개월 수익률·지수 초과수익 양수, 20일 평균 거래대금 10억원 이상.'}</p></article></div>`;}
    function sectors(){const selected=matches(),groups=E.sectors(selected,research),cap=groups.reduce((s,g)=>s+g.cap,0);return title('산업별 후보 살펴보기','현재 필터에 맞는 저장 기업의 규모와 지표 중앙값')+filterForm()+`<article class="panel below"><p class="psub">${selected.length}개 기업 · 카드의 비율은 유효 시가총액 합계 비중 · 전체 시장의 업종 수익률이 아닙니다.</p><div class="research-sectors">${groups.filter(g=>g.cap>0).map(g=>`<button data-sector="${esc(g.name)}" style="flex-grow:${Math.max(.01,g.cap/(cap||1))}"><b>${esc(g.name)}</b><span>${fmt(g.cap)}억원</span><small>${fmt(g.cap/(cap||1)*100)}% · ${g.count}개</small></button>`).join('')}</div>${groups.length?`<div class="tscroll"><table><thead><tr><th>산업 · 표본</th><th>시가총액 (억원)</th>${E.dimensions.map(k=>`<th>${labels[k]} 중앙값 (${unit(k)})</th>`).join('')}</tr></thead><tbody>${groups.map(g=>`<tr><td><button data-sector="${esc(g.name)}">${esc(g.name)} · ${g.count}개</button></td><td>${g.capCount?fmt(g.cap):'—'}<small> / 유효 ${g.capCount}개</small></td>${E.dimensions.map(k=>`<td>${fmt(g.metrics[k].value)}<small> / ${g.metrics[k].count}개</small></td>`).join('')}</tr>`).join('')}</tbody></table></div>`:blank('현재 조건에 맞는 기업이 없습니다.')}<p class="psub">산업을 누르면 해당 후보 목록으로 이동합니다. 지표마다 유효 기업이 다르며 보고기간·회계 기준이 섞일 수 있습니다. 기간·회계 기준을 확인하지 못한 발굴 자료의 중앙값은 표시하지 않습니다. 동일 기준의 기업 비교는 간단 분석에서 확인하세요.</p></article>`;}
    function render(id=view){chartInstance?.destroy();chartInstance=null;view=id;
      try{sessionStorage.setItem(storageKey,JSON.stringify({filters:{...filters},watch:watchData()}));}
      catch{notice='이 브라우저에서는 새로고침 복원이 제한됩니다. 관심목록 저장으로 파일을 보관하세요.';}
      element.innerHTML=`<div id="researchNotice" class="psub" role="status">${esc(notice)}</div><p id="financialLoadStatus" class="psub" role="status" aria-live="polite"></p>`+(['finder','watch'].includes(view)?list():view==='brief'?brief():view==='trend'?trend():sectors());if(view==='sectors'&&typeof DashboardUpgradeUI!=='undefined'&&element.insertAdjacentHTML)element.insertAdjacentHTML('beforeend',DashboardUpgradeUI.sectorTable(insights));bind();
      if(['brief','trend'].includes(view)&&row()&&typeof window!=='undefined'){
        const selected=row(),pending=research.rows?.[selected.code]?.technical?.series_pending;
        if(pending&&window.INVESTMENT_LOAD_COMPANY_VIEW)window.INVESTMENT_LOAD_COMPANY_VIEW(selected.code).then(loaded=>{if(loaded&&view==='brief'&&getCode()===selected.code&&!financialContext(selected).period)window.INVESTMENT_ENSURE_FINANCIALS?.(selected.code);});
        else if(view==='brief'&&!financialContext(selected).period)window.INVESTMENT_ENSURE_FINANCIALS?.(selected.code);
      }
    }
    function bind(){const $=id=>element.querySelector('#'+id);
      J.bind(element,{rows,go:c=>{setCode(c);go('brief');},search:(industry,market)=>{filters={...J.defaults,industry,market};page=0;go('finder');}});
      element.querySelector('[data-journey-cadence]')?.addEventListener('change',e=>{cadences[row().code]=e.target.value;render();});
      element.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{filters={...J.defaults,...J.presets[b.dataset.preset].values};page=0;render();});
      element.querySelector('[data-saved-preset]')?.addEventListener('change',e=>{if(e.target.value==='')return;selectedPreset=e.target.value;filters={...J.defaults,...savedPresets[+e.target.value].filters};page=0;render();});
      element.querySelector('[data-save-preset]')?.addEventListener('click',()=>{const name=element.querySelector('[data-preset-name]').value.trim();if(!name){notice='검색 이름을 입력하세요.';element.querySelector('#researchNotice').textContent=notice;return;}savedPresets=savedPresets.filter(v=>v.name!==name);savedPresets.push({name,filters:{...filters}});savedPresets=savedPresets.slice(-8);try{localStorage.setItem(presetKey,JSON.stringify(savedPresets));notice='검색조건 저장 완료';}catch{notice='검색조건 저장 공간 확인 필요';}render();});
      element.querySelector('[data-delete-preset]')?.addEventListener('click',()=>{const name=element.querySelector('[data-preset-name]').value.trim(),select=element.querySelector('[data-saved-preset]').value;const idx=select!==''?+select:savedPresets.findIndex(x=>x.name===name);if(idx<0){notice='삭제할 검색을 선택하거나 이름을 입력하세요.';}else{savedPresets.splice(idx,1);selectedPreset='';try{localStorage.setItem(presetKey,JSON.stringify(savedPresets));notice='검색조건 삭제 완료';}catch{notice='삭제 저장 실패';}}render();});
      const chartElement=element.querySelector('.interactiveTrendChart'),selected=row();
      if(chartElement&&selected&&typeof TrendChartUI!=='undefined'){const model=companyModels[selected.code],matched=model&&model.code===selected.code&&model.name===selected.name&&model.market===selected.market;chartInstance=TrendChartUI.mount(chartElement,{technical:research.rows[selected.code].technical,model:matched?model:null,state:chartStates[selected.code]||(chartStates[selected.code]={})});}
      if(view==='brief'&&row())EbitdaEditor.bind(element,row(),financialTables[row().code],financialViews[row().code],ebitda,financialEditors[row().code]||(financialEditors[row().code]={}),()=>render());
      if($('financialPeriodSelect'))$('financialPeriodSelect').onchange=e=>{financialViews[row().code]=e.target.value;financialEditors[row().code]={};render();};
      if($('discoveryFilters'))$('discoveryFilters').onsubmit=e=>{e.preventDefault();const data=new FormData(e.currentTarget);filters={...Object.fromEntries(data.entries()),improved:filters.improved===true};filters.trend=data.has('trend');page=0;render();};
      if($('discoveryReset'))$('discoveryReset').onclick=()=>{filters={query:'',market:'',industry:'',sort:'roe_pct',direction:'desc'};page=0;render();};
      if($('researchCompany'))$('researchCompany').onchange=e=>{setCode(e.target.value);render();};
      element.querySelectorAll('[data-research-code]').forEach(el=>el.onclick=()=>{setCode(el.dataset.researchCode);go('brief');});
      element.querySelectorAll('[data-research-go]').forEach(el=>el.onclick=()=>go(el.dataset.researchGo));
      element.querySelectorAll('[data-sector]').forEach(el=>el.onclick=()=>{filters.industry=el.dataset.sector;page=0;go('finder');});
      element.querySelectorAll('[data-watch]').forEach(el=>el.onclick=()=>{const r=rows.find(r=>r.code===el.dataset.watch);if(!r)return;const idx=watch.findIndex(w=>w.code===r.code);if(idx<0)watch.push({code:r.code,name:r.name,market:r.market});else watch.splice(idx,1);notice=`${r.name} 관심목록 ${idx<0?'추가':'제거'}`;render();});
      if($('researchPrev'))$('researchPrev').onclick=()=>{page--;render();};if($('researchNext'))$('researchNext').onclick=()=>{page++;render();};
      if($('watchExport'))$('watchExport').onclick=()=>download(JSON.stringify(watchData(),null,2),'investment_watchlist.json','application/json');
      if($('watchImport'))$('watchImport').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>2000000)throw Error('2MB 이하 파일을 사용하세요.');const result=E.restoreWatch(JSON.parse(await file.text()),rows,meta.data_mode);watch=result.companies;notice=`관심목록 ${watch.length}개 불러옴 · 식별 불일치/중복 ${result.skipped}개 제외`;page=0;}catch(error){notice=error.message||'관심목록 형식 확인 필요';}render();};
    }
    function csv(){download(E.csv(matches(),meta,research),'investment_candidates.csv','text/csv;charset=utf-8');}
    return {updateHealth:(code,health)=>{const r=rows.find(r=>r.code===code);if(r)r.collection_health=health;},updateCommon:(code,common)=>{const r=rows.find(r=>r.code===code);if(r){r.common_financial=common;Object.assign(r.metrics,common.metrics);Object.assign(r.metric_details||(r.metric_details={}),common.metric_details);}},render,csv,ebitda,tables:financialTables,search:(query,industry='',market='')=>{filters={...J.defaults,query,industry,market};page=0;},isWatched:c=>watch.some(w=>w.code===c),toggleWatch:c=>{const r=rows.find(r=>r.code===c);if(!r)return;const i=watch.findIndex(w=>w.code===c);if(i<0)watch.push({code:r.code,name:r.name,market:r.market});else watch.splice(i,1);try{sessionStorage.setItem(storageKey,JSON.stringify({filters:{...filters},watch:watchData()}));}catch{}},state:()=>({filters:{...filters},watch:watchData(),ebitda:ebitda.pack(),charts:JSON.parse(JSON.stringify(chartStates))}),isPage:id=>['finder','brief','trend','watch','sectors'].includes(id)};
  }
  return {create};
})();
