'use strict';
const TrendChartUI=(()=>{
 const num=v=>typeof v==='number'&&Number.isFinite(v),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=(v,d=0)=>num(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:d}):'—';
 const lines=[['close','종가','#253144'],['ma20','20일','#069b87'],['ma50','50일','#327af0'],['ma150','150일','#bd8a29'],['ma200','200일','#9565c5']];
 function mount(element,{technical,model,state={}}){
  const t=technical,series=t.series||[],source=model?.chart?.bars||[],lookup=new Map(source.map(p=>[p.date,p]));
  const matched=series.length&&series.every(p=>lookup.get(p.date)?.close===p.close)&&source.at(-1)?.date===t.as_of;
  const bars=(matched?source:series).filter(p=>p.date<=t.as_of).map(p=>({...p}));
  const totals=[0];for(const p of bars)totals.push(totals.at(-1)+p.close);
  bars.forEach((p,i)=>{for(const n of [20,50,150,200])p['ma'+n]=i+1>=n?(totals[i+1]-totals[i+1-n])/n:(matched?null:p['ma'+n]??null);});
  if(!bars.length){element.textContent='완료 가격 자료 대기';return {destroy(){}};}
  const validOHLC=p=>['open','high','low'].every(k=>num(p[k])&&p[k]>0)&&p.low<=Math.min(p.open,p.close)&&p.high>=Math.max(p.open,p.close);
  const hasCandles=bars.every(validOHLC);
  state.range=[63,126,253].includes(state.range)?state.range:126;state.mode=state.mode==='candle'&&hasCandles?'candle':'line';state.pivot=state.pivot!==false;state.hidden=Array.isArray(state.hidden)?state.hidden.filter(k=>lines.some(([key])=>key===k)):[];
  let pinned=false,observer,drag=null,destroyed=false,geometry;
  const pivot=t.trend_analysis?.pivot;
  function extent(){let end=state.end_date?bars.findLastIndex(p=>p.date<=state.end_date):bars.length-1;end=Math.max(0,end);let start=state.start_date?bars.findIndex(p=>p.date>=state.start_date):Math.max(0,end-state.range+1);start=Math.max(0,Math.min(start,end));return {start,end};}
  function render(){
   if(destroyed)return;const {start,end}=extent(),ps=bars.slice(start,end+1),width=Math.max(220,element.clientWidth),left=12,right=width-82,top=24,base=320,bottom=370,plotW=right-left;
   const active=lines.filter(([k])=>!state.hidden.includes(k)),values=ps.flatMap(p=>[p.close,...(state.mode==='candle'?[p.high,p.low]:[]),...active.map(([k])=>p[k])].filter(num));if(state.pivot&&num(pivot))values.push(pivot);
   const low=Math.min(...values),high=Math.max(...values),pad=(high-low)*.08||high*.01,lo=Math.max(0,low-pad),hi=high+pad,y=v=>base-(v-lo)/(hi-lo)*(base-top),x=i=>left+(ps.length===1?.5:i/(ps.length-1))*plotW,nx=i=>left+i/Math.max(1,bars.length-1)*plotW;
   const path=(key,points=ps,xFn=x,yFn=y)=>{let begun=false;return points.map((p,i)=>{if(!num(p[key])){begun=false;return '';}const part=(begun?'L':'M')+xFn(i)+','+yFn(p[key]);begun=true;return part;}).join(' ');};
   const id='trend-chart-'+Math.random().toString(36).slice(2),clip=`<defs><clipPath id="${id}"><rect x="${left}" y="${top}" width="${plotW}" height="${base-top}"/></clipPath></defs>`;
   let grid='';for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4;grid+=`<line x1="${left}" x2="${right}" y1="${y(v)}" y2="${y(v)}" class="tc-grid"/><text x="${right+9}" y="${y(v)+4}">${fmt(v/10000,1)}</text>`;}
   let prices='';const candleW=Math.max(1,Math.min(10,plotW/ps.length*.7));
   if(state.mode==='candle'&&!state.hidden.includes('close'))prices=ps.map((p,i)=>{const color=p.close>=p.open?'#dd5463':'#397dd2';return `<line x1="${x(i)}" x2="${x(i)}" y1="${y(p.high)}" y2="${y(p.low)}" stroke="${color}"/><rect x="${x(i)-candleW/2}" y="${Math.min(y(p.open),y(p.close))}" width="${candleW}" height="${Math.max(1,Math.abs(y(p.close)-y(p.open)))}" fill="${color}"/>`;}).join('');
   prices+=active.filter(([k])=>k!=='close'||state.mode!=='candle').map(([k,,c])=>`<path d="${path(k)}" fill="none" stroke="${c}" stroke-width="${k==='close'?2.3:1.6}"/>`).join('');
   if(state.pivot&&num(pivot))prices+=`<line x1="${left}" x2="${right}" y1="${y(pivot)}" y2="${y(pivot)}" stroke="#dd5463" stroke-dasharray="5 5"/>`;
   const ticks=[...new Set(Array.from({length:width<500?3:5},(_,i)=>Math.round(i*(ps.length-1)/(width<500?2:4))))];
   const axis=ticks.map(i=>`<text x="${x(i)}" y="${base+22}" text-anchor="${i===0?'start':i===ps.length-1?'end':'middle'}">${esc(ps[i].date.slice(2).replaceAll('-','.'))}</text>`).join('');
   const allLow=Math.min(...bars.map(p=>p.close)),allHigh=Math.max(...bars.map(p=>p.close)),ny=v=>45-(v-allLow)/(allHigh-allLow||1)*36,vm=Math.max(1,...ps.map(p=>num(p.volume)&&p.volume>=0?p.volume:0)),vg=ps.map((p,i)=>num(p.volume)&&p.volume>=0?`<rect x="${x(i)-candleW/2}" y="${74-p.volume/vm*54}" width="${candleW}" height="${p.volume/vm*54}" fill="${validOHLC(p)?p.close>=p.open?'#dd5463':'#397dd2':'#a8bed7'}" opacity=".55"/>`:'').join('');
   element.innerHTML=`<div class="tc-toolbar"><div class="research-actions">${[[63,'3개월'],[126,'6개월'],[253,'1년']].map(([n,label])=>`<button data-trend-range="${n}" aria-pressed="${!state.start_date&&state.range===n}">${label}</button>`).join('')}</div><div class="tc-switches"><label>가격 <select data-tc-mode><option value="line" ${state.mode==='line'?'selected':''}>종가 선</option><option value="candle" ${state.mode==='candle'?'selected':''} ${hasCandles?'':'disabled'}>캔들${hasCandles?'':' · OHLC 대기'}</option></select></label><label><input type="checkbox" data-tc-pivot ${state.pivot?'checked':''} ${num(pivot)?'':'disabled'}> 돌파선</label></div></div><div class="tc-legend">${lines.map(([k,label,c])=>`<button data-tc-series="${k}" aria-pressed="${!state.hidden.includes(k)}"><i style="background:${c}"></i>${label}</button>`).join('')}</div><p class="tc-readout" role="status" aria-live="polite">${esc(ps.at(-1).date)} · 종가 ${fmt(ps.at(-1).close)}원 · ${ps.length}개 완료 거래일</p><div class="tc-plot"><svg viewBox="0 0 ${width} ${bottom}" class="tc-price-svg" role="img" aria-label="완료 종가와 이동평균 및 20일 종가 돌파선">${clip}<text x="${right+9}" y="14">가격 (만원)</text>${grid}<g clip-path="url(#${id})">${prices}</g>${axis}<text x="${(left+right)/2}" y="365" text-anchor="middle">날짜</text><line data-tc-guide x1="0" x2="0" y1="${top}" y2="${base}" visibility="hidden"/><g data-tc-markers></g><rect data-chart-hit x="${left}" y="${top}" width="${plotW}" height="${base-top}" fill="transparent"/></svg></div><svg viewBox="0 0 ${width} 60" class="tc-nav-svg" role="img" aria-label="전체 가격 이력에서 표시 구간 선택"><path d="${path('close',bars,nx,ny)}" fill="none" stroke="#a8bed7"/><rect x="${nx(start)}" y="4" width="${Math.max(2,nx(end)-nx(start))}" height="46" fill="#327af0" opacity=".1"/><rect data-tc-handle="start" x="${nx(start)-5}" y="3" width="10" height="49" fill="#327af0"/><rect data-tc-handle="end" x="${nx(end)-5}" y="3" width="10" height="49" fill="#327af0"/></svg><div class="tc-window"><label>시작 <input type="date" data-tc-date="start" value="${bars[start].date}" min="${bars[0].date}" max="${bars[end].date}"></label><label>끝 <input type="date" data-tc-date="end" value="${bars[end].date}" min="${bars[start].date}" max="${bars.at(-1).date}"></label></div><svg viewBox="0 0 ${width} 98" class="tc-volume-svg" role="img" aria-label="일별 거래량"><text x="${left}" y="14">거래량 (주)</text>${vg}<line data-tc-volume-guide x1="0" x2="0" y1="18" y2="74" visibility="hidden"/><text x="${left}" y="96">${ps[0].date}</text><text x="${right}" y="96" text-anchor="end">${ps.at(-1).date}</text></svg><div class="tc-foot"><span>20일 종가 돌파선 ${num(pivot)?fmt(pivot)+'원':'미확보'}</span><span>52주 최고종가 대비 ${fmt(t.trend_analysis?.drawdown_pct,1)}%</span></div><p class="psub">완료 일봉 ${esc(t.as_of)} · 범위 변경은 표시만 바꾸며 추세 점검은 전체 이력으로 계산합니다.${hasCandles?'':' 시가·고가·저가 미확보로 종가 선만 표시합니다.'}</p><div class="tc-tooltip" role="tooltip" hidden></div>`;
   geometry={width,left,right,top,base,ps,x,y,start,end,nx};pinned=false;
   element.querySelectorAll('[data-trend-range]').forEach(b=>b.onclick=()=>{state.range=+b.dataset.trendRange;state.start_date=null;state.end_date=null;render();});
   element.querySelector('[data-tc-mode]').onchange=e=>{state.mode=e.target.value;render();};element.querySelector('[data-tc-pivot]').onchange=e=>{state.pivot=e.target.checked;render();};
   element.querySelectorAll('[data-tc-series]').forEach(b=>b.onclick=()=>{const k=b.dataset.tcSeries;state.hidden=state.hidden.includes(k)?state.hidden.filter(v=>v!==k):[...state.hidden,k];render();});
   element.querySelectorAll('[data-tc-date]').forEach(input=>input.onchange=()=>{if(input.value){state[input.dataset.tcDate==='start'?'start_date':'end_date']=input.value;render();}});
   const hit=element.querySelector('[data-chart-hit]');
   hit.onpointermove=e=>{if(!pinned)show(e);};hit.onpointerleave=()=>{if(!pinned)hide();};hit.onclick=e=>{pinned=!pinned;show(e);};
   element.querySelectorAll('[data-tc-handle]').forEach(handle=>handle.onpointerdown=e=>{e.preventDefault();const nav=element.querySelector('.tc-nav-svg');drag={side:handle.dataset.tcHandle,box:nav.getBoundingClientRect(),start,end};handle.setPointerCapture(e.pointerId);handle.onpointermove=move;handle.onpointerup=finish;handle.onpointercancel=()=>{drag=null;};});
  }
  function cursor(event,svg){const box=svg.getBoundingClientRect();return (event.clientX-box.left)/box.width*geometry.width;}
  function show(event){const g=geometry,svg=element.querySelector('.tc-price-svg'),cx=Math.max(g.left,Math.min(g.right,cursor(event,svg))),position=(cx-g.left)/(g.right-g.left)*Math.max(0,g.ps.length-1),index=Math.round(position),p=g.ps[index],a=g.ps[Math.floor(position)],b=g.ps[Math.ceil(position)],fraction=position-Math.floor(position),tip=element.querySelector('.tc-tooltip');
   element.querySelectorAll('[data-tc-guide],[data-tc-volume-guide]').forEach(line=>{line.setAttribute('x1',cx);line.setAttribute('x2',cx);line.setAttribute('visibility','visible');});
   const values=lines.filter(([k])=>!state.hidden.includes(k)).map(([k,label,c])=>[k,label,c,num(a[k])&&num(b[k])?a[k]+(b[k]-a[k])*fraction:null]);
   element.querySelector('[data-tc-markers]').innerHTML=state.mode==='line'?values.filter(([, , ,v])=>num(v)).map(([k,,c,v])=>`<circle data-tc-marker="${k}" cx="${cx}" cy="${g.y(v)}" r="3.5" fill="${c}" stroke="white"/>`).join(''):'';
   const readout=`${p.date} · 종가 ${fmt(p.close)}원 · 거래량 ${num(p.volume)?fmt(p.volume)+'주':'미확보'}`;element.querySelector('.tc-readout').textContent=readout;
   tip.innerHTML=`<b>${esc(p.date)}${state.mode==='line'?' · 커서 보간':''}</b><br>${state.mode==='candle'?`시 ${fmt(p.open)} · 고 ${fmt(p.high)}<br>저 ${fmt(p.low)} · 종 ${fmt(p.close)}원`:values.filter(([, , ,v])=>num(v)).map(([,label,,v])=>`${label} ${fmt(v)}원`).join('<br>')}<br>거래량 ${num(p.volume)?fmt(p.volume)+'주':'미확보'}`;tip.hidden=false;
   const plot=element.querySelector('.tc-plot'),offset=cx/g.width*plot.clientWidth;tip.style.left=Math.max(0,Math.min(element.clientWidth-tip.offsetWidth,offset>plot.clientWidth*.55?offset-tip.offsetWidth-12:offset+12))+'px';tip.style.top=plot.offsetTop+28+'px';
  }
  function hide(){element.querySelector('.tc-tooltip').hidden=true;element.querySelectorAll('[data-tc-guide],[data-tc-volume-guide]').forEach(line=>line.setAttribute('visibility','hidden'));element.querySelector('[data-tc-markers]').innerHTML='';}
  function move(e){if(!drag)return;const cx=(e.clientX-drag.box.left)/drag.box.width*geometry.width,i=Math.max(0,Math.min(bars.length-1,Math.round((cx-geometry.left)/(geometry.right-geometry.left)*(bars.length-1))));drag[drag.side]=drag.side==='start'?Math.min(i,drag.end):Math.max(i,drag.start);const handle=element.querySelector(`[data-tc-handle="${drag.side}"]`);handle.setAttribute('x',geometry.nx(drag[drag.side])-5);}
  function finish(e){if(!drag)return;move(e);state.start_date=bars[drag.start].date;state.end_date=bars[drag.end].date;drag=null;render();}
  render();if(typeof ResizeObserver!=='undefined'){observer=new ResizeObserver(()=>{if(!drag&&Math.max(220,element.clientWidth)!==geometry.width)render();});observer.observe(element);}
  return {destroy(){destroyed=true;observer?.disconnect();}};
 }
 return {mount};
})();
