'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,u='',digits=1)=>isNum(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:digits})+(u?' '+u:''):'—';
const STATUS={pass:'충족',fail:'미충족',unknown:'자료 부족'};
const EMPTY={schema_version:'0.1',meta:{price_date:null,flow_start:null,flow_end:null,financial_period:null,financial_basis:null,venue:null,universe_label:'데이터 미연결',universe_total:null},companies:[]};
let snapshot=structuredClone(EMPTY),activeTab='screen',companyCode='',comparisonIndustry='',comparisonCodes=new Set(),lastRows=[];
let rules=[{metric:'operating_margin_pct',op:'gte',value:null},{metric:'debt_ratio_pct',op:'lte',value:null},{metric:'avg_trading_value_20d_eok',op:'gte',value:null}];
let savedConfigs={};try{savedConfigs=JSON.parse(localStorage.getItem('investment-screen-presets-v01')||'{}');if(!savedConfigs||typeof savedConfigs!=='object'||Array.isArray(savedConfigs))savedConfigs={};}catch{savedConfigs={};}
let toastTimer;function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4200);}
function download(name,content,type='application/json'){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function metricOptions(selected){let out='';for(const cat of [...new Set(Object.values(METRICS).map(m=>m.category))]){out+=`<optgroup label="${esc(cat)}">`;for(const [k,m]of Object.entries(METRICS))if(m.category===cat)out+=`<option value="${k}" ${k===selected?'selected':''}>${esc(m.label)}</option>`;out+='</optgroup>';}return out;}
function activate(tab){if(tab==='company'&&window.parent!==window&&window.parent.INVESTMENT_OPEN_COMPANY){window.parent.INVESTMENT_OPEN_COMPANY(companyCode);return;}activeTab=tab;document.querySelectorAll('[data-tab]').forEach(el=>{el.classList.toggle('active',el.dataset.tab===tab);el.setAttribute('aria-selected',el.dataset.tab===tab?'true':'false')});document.querySelectorAll('.tab-panel').forEach(el=>el.hidden=el.id!==`panel-${tab}`);if(tab==='company')renderCompany();if(tab==='compare')renderComparison();}
function validRules(){return rules.filter(r=>isNum(r.value));}
function renderRules(){
 $('rules').innerHTML=rules.map((r,i)=>`<div class="rule"><div class="rule-top"><select aria-label="조건 ${i+1} 지표" data-rule="${i}" data-part="metric">${metricOptions(r.metric)}</select><button data-remove="${i}" aria-label="조건 ${i+1} 삭제">×</button></div><div class="rule-value"><select aria-label="조건 ${i+1} 연산" data-rule="${i}" data-part="op">${[['gte','이상 ≥'],['lte','이하 ≤'],['gt','초과 >'],['lt','미만 <'],['eq','같음 =']].map(([k,v])=>`<option value="${k}" ${r.op===k?'selected':''}>${v}</option>`).join('')}</select><input type="number" step="any" placeholder="값 입력" aria-label="조건 ${i+1} 값" data-rule="${i}" data-part="value" value="${r.value??''}"><span class="unit">${METRICS[r.metric].unit}</span></div></div>`).join('');
 $('rules').querySelectorAll('[data-part]').forEach(el=>el.addEventListener('change',()=>{const i=+el.dataset.rule,k=el.dataset.part;rules[i][k]=k==='value'?(el.value===''?null:Number(el.value)):el.value;if(k==='metric')renderRules();renderScreen();}));
 $('rules').querySelectorAll('[data-remove]').forEach(el=>el.addEventListener('click',()=>{rules.splice(+el.dataset.remove,1);renderRules();renderScreen();}));
 $('activeRules').textContent=`활성 조건 ${validRules().length}개 · 빈 값은 적용하지 않음`;
}
function renderSaved(){const keys=Object.keys(savedConfigs);$('savedPreset').innerHTML='<option value="">저장한 조건 선택</option>'+keys.map(k=>`<option value="${esc(k)}">${esc(k)}</option>`).join('');}
function allEligible(){return eligible(snapshot.companies);}
function filteredBase(){const market=$('market').value,ind=$('industry').value,q=$('nameSearch').value.trim().toLowerCase();return allEligible().filter(r=>(!market||r.market===market)&&(!ind||r.industry===ind)&&(!q||r.code.includes(q)||r.name.toLowerCase().includes(q)));}
function setIndustries(){const industries=[...new Set(allEligible().map(r=>r.industry))].sort((a,b)=>a.localeCompare(b,'ko'));const current=$('industry').value;$('industry').innerHTML='<option value="">전체 산업</option>'+industries.map(s=>`<option>${esc(s)}</option>`).join('');if(industries.includes(current))$('industry').value=current;$('compareIndustry').innerHTML=industries.length?industries.map(s=>`<option>${esc(s)}</option>`).join(''):'<option value="">산업 데이터 미연결</option>';if(!industries.includes(comparisonIndustry))comparisonIndustry=industries[0]||'';$('compareIndustry').value=comparisonIndustry;}
function scopeMeta(){
 const m=snapshot.meta,has=snapshot.companies.length>0,fixture=m.data_mode==='fixture';
 $('dataBadge').textContent=has?(fixture?'가상 테스트 자료':'불러온 데이터 · 자동연결 없음'):'시제품 · 데이터 미연결';
 $('dataBadge').className='tag warning';
 $('noticeText').textContent=has?(fixture?'가상으로 만든 테스트 자료입니다. 실제 시장 관측이나 투자 판단 자료가 아닙니다.':`불러온 ${snapshot.companies.length}개 종목 범위의 분석입니다. 전 시장 완전성·수치 원문 검증·자동 갱신은 확인되지 않았습니다.`):'조건 설정과 화면 이동을 확인하는 시제품입니다. 실제 기업·가격·재무 데이터는 아직 연결하지 않았습니다.';
 $('scopeBar').innerHTML=[`시세 ${m.price_date||'미연결'}`,`재무 ${m.financial_period||'미연결'} · ${m.financial_basis||'기준 미설정'}`,`수급 ${m.flow_start&&m.flow_end?`${m.flow_start} ~ ${m.flow_end}`:'미연결'}`,`시장 범위 ${m.venue||'미설정'}`].map(t=>`<span>${esc(t)}</span>`).join('');
 $('dataMeta').textContent=JSON.stringify(m,null,2);$('importCount').textContent=has?`${snapshot.companies.length.toLocaleString()}개 종목`:'연결 전';
 $('coverageDetail').textContent=has?`파일 범위: ${m.universe_label}. 전체 모집단: ${m.universe_total==null?'미확인':m.universe_total+'개'}. 일반 스크리너 대상: ${allEligible().length}개.`:'불러온 자료가 없습니다. 전 종목 데이터베이스나 API 연결은 포함하지 않습니다.';
}
function renderScreen(){
 const has=snapshot.companies.length>0,rs=validRules(),logic=$('logic').value;let rows=filteredBase().map(row=>({row,status:evaluate(row,rs,logic)}));
 $('universeStat').textContent=has?rows.length.toLocaleString():'—';$('matchStat').textContent=has?rows.filter(x=>x.status==='pass').length.toLocaleString():'—';$('unknownStat').textContent=has?rows.filter(x=>x.status==='unknown').length.toLocaleString():'—';$('activeRules').textContent=`활성 조건 ${rs.length}개 · 빈 값은 적용하지 않음`;
 const status=$('resultStatus').value;if(status)rows=rows.filter(x=>x.status===status);
 const sort=$('sortMetric').value,dir=$('sortDir').value==='desc'?-1:1;
 rows.sort((a,b)=>{if(sort==='name')return dir*a.row.name.localeCompare(b.row.name,'ko');const av=val(a.row,sort),bv=val(b.row,sort);if(av===null&&bv===null)return a.row.code.localeCompare(b.row.code);if(av===null)return 1;if(bv===null)return-1;return dir*(av-bv)||a.row.code.localeCompare(b.row.code)});
 lastRows=rows;$('exportResults').disabled=!has;$('resultsCount').textContent=has?`${rows.length}개 표시`:'결과 데이터 미연결';
 if(!has){$('resultBody').innerHTML='';$('resultTable').hidden=true;$('screenEmpty').hidden=false;return;}
 $('resultTable').hidden=false;$('screenEmpty').hidden=true;
 if(!rows.length){$('resultBody').innerHTML='<tr><td colspan="9" style="text-align:center;padding:45px">현재 필터에 맞는 항목이 없습니다. 자료 부족 항목도 별도로 확인하세요.</td></tr>';return;}
 $('resultBody').innerHTML=rows.map(({row:r,status:s})=>{const missing=rs.filter(c=>val(r,c.metric)===null).map(c=>METRICS[c.metric].label);return `<tr><td><input type="checkbox" data-compare="${r.code}" aria-label="${esc(r.name)} 비교 선택" ${comparisonCodes.has(r.code)?'checked':''}></td><td class="left"><button class="company-btn" data-company="${r.code}">${esc(r.name)}</button><div class="sub">${r.code} · ${esc(r.market)}</div></td><td class="left">${esc(r.industry)}</td><td>${fmt(val(r,'operating_margin_pct'))}</td><td>${fmt(val(r,'debt_ratio_pct'))}</td><td>${fmt(val(r,'foreign_net_20d_eok'))}</td><td>${fmt(val(r,'avg_trading_value_20d_eok'))}</td><td><span class="tag ${s==='pass'?'good':s==='fail'?'fail':'warning'}" title="${esc(missing.length?'누락: '+missing.join(', '):'현재 입력된 조건 기준')}">${STATUS[s]}</span></td><td><button class="small" data-company="${r.code}">분석</button></td></tr>`}).join('');
 $('resultBody').querySelectorAll('[data-company]').forEach(b=>b.addEventListener('click',()=>{companyCode=b.dataset.company;activate('company')}));
 $('resultBody').querySelectorAll('[data-compare]').forEach(b=>b.addEventListener('change',()=>{const row=snapshot.companies.find(r=>r.code===b.dataset.compare);if(b.checked){if(comparisonIndustry!==row.industry){comparisonCodes.clear();comparisonIndustry=row.industry;toast('같은 산업끼리 비교하도록 비교 집합을 변경했습니다.');}if(comparisonCodes.size>=5){b.checked=false;toast('비교 기업은 최대 5개입니다.');return;}comparisonCodes.add(row.code);}else comparisonCodes.delete(row.code);$('compareIndustry').value=comparisonIndustry;renderScreen();renderComparison();}));
}
function companySelect(){const rows=allEligible().sort((a,b)=>a.name.localeCompare(b.name,'ko'));if(!rows.some(r=>r.code===companyCode))companyCode=rows[0]?.code||'';$('companySelect').innerHTML=rows.length?rows.map(r=>`<option value="${r.code}" ${companyCode===r.code?'selected':''}>${esc(r.name)} · ${r.code}</option>`).join(''):'<option value="">기업 데이터 미연결</option>';return rows.find(r=>r.code===companyCode);}
function metricRows(row,keys){return keys.map(k=>`<div class="metric-row"><span title="${esc(row?.metric_missing_reasons?.[k]||METRICS[k].definition)}">${esc(METRICS[k].label)}</span><b>${fmt(row?val(row,k):null,METRICS[k].unit)}</b></div>`).join('');}
function renderCompany(){
 const row=companySelect();$('companyTitle').textContent=row?row.name:'기업을 선택하면 핵심 지표를 확인할 수 있습니다.';$('companyMeta').textContent=row?`${row.code} · ${row.market} · ${row.industry} · ${snapshot.meta.financial_period} / ${snapshot.meta.financial_basis}`:'수익성 · 재무안정성 · 수급 · 두 가지 유동성';
 $('profitMetrics').innerHTML=metricRows(row,['revenue_growth_pct','operating_margin_pct','roe_pct']);$('stabilityMetrics').innerHTML=metricRows(row,['debt_ratio_pct','net_debt_equity_pct','interest_coverage_x']);$('flowMetrics').innerHTML=metricRows(row,['foreign_net_20d_eok','institution_net_20d_eok','foreign_net_turnover_20d_pct']);$('liquidityMetrics').innerHTML=metricRows(row,['avg_trading_value_20d_eok','current_ratio_pct']);
 if(!row){$('companySummary').innerHTML='<p>데이터 연결 전입니다. 자동 요약은 확인된 수치와 비교 범위만 설명하며, 매수·매도 판단이나 종합 점수는 생성하지 않습니다.</p>';$('historyBody').innerHTML='<tr><td colspan="4" style="text-align:center;padding:30px">연간 재무 데이터 미연결</td></tr>';$('historyChart').innerHTML='<div class="chart-empty">실제 연도별 재무자료가 연결되면 표시됩니다.</div>';$('companySources').innerHTML='출처 원문 미연결';return;}
 const peers=peerRows(snapshot.companies,row.industry),med=median(peers.map(r=>val(r,'operating_margin_pct'))),op=val(row,'operating_margin_pct'),diff=op!==null&&med!==null?`${Math.abs(op-med).toFixed(1)}%p ${op>=med?'높음':'낮음'}`:'비교 자료 부족';
 $('companySummary').innerHTML=`<p><strong>수익성</strong> · 영업이익률 ${fmt(op,'%')}. 불러온 동일 산업 중앙값 ${fmt(med,'%')} 대비 ${diff}.</p><p><strong>재무</strong> · 부채비율 ${fmt(val(row,'debt_ratio_pct'),'%')}, 이자보상배율 ${fmt(val(row,'interest_coverage_x'),'배')}. 지표만으로 지급능력이나 위험을 확정하지 않습니다.</p><p><strong>수급</strong> · 최근 20거래일 외국인 ${fmt(val(row,'foreign_net_20d_eok'),'억원')}, 기관 ${fmt(val(row,'institution_net_20d_eok'),'억원')} 순매수.</p><p><strong>유동성</strong> · 주식의 일평균 거래대금 ${fmt(val(row,'avg_trading_value_20d_eok'),'억원')}; 회사의 유동비율 ${fmt(val(row,'current_ratio_pct'),'%')}. 서로 다른 지표입니다.</p><p class="sub">규칙 기반 요약 · 업종 모집단은 불러온 기업 ${peers.length}개 · 결측치는 추정하지 않음</p>`;
 const hist=(row.history||[]).slice().sort((a,b)=>a.year-b.year).slice(-5);
 $('historyBody').innerHTML=hist.length?hist.map(h=>`<tr><td>${h.year}</td><td>${fmt(h.revenue_eok)}</td><td>${fmt(h.operating_profit_eok)}</td><td>${fmt(isNum(h.revenue_eok)&&h.revenue_eok>0&&isNum(h.operating_profit_eok)?h.operating_profit_eok/h.revenue_eok*100:null)}</td></tr>`).join(''):'<tr><td colspan="4" style="text-align:center;padding:30px">연간 이력 없음 · 수집된 최신 지표만 표시합니다.</td></tr>';
 $('historyChart').innerHTML=lineChart(hist);
 $('companySources').innerHTML=(row.sources||[]).length?row.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)}</a>`).join(''):'공시·시장자료 원문 출처 미입력. 수치의 실제 출처를 검증하지 않은 상태입니다.';
 if(row.data_quality?.length)$('companySources').innerHTML+=`<p><strong>자료 확인이 필요한 항목</strong></p><ul>${row.data_quality.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>`;
}
function lineChart(hist){
 const pts=hist.map(h=>({year:h.year,value:isNum(h.revenue_eok)&&h.revenue_eok>0&&isNum(h.operating_profit_eok)?h.operating_profit_eok/h.revenue_eok*100:null}));
 const nums=pts.map(p=>p.value).filter(isNum);if(!nums.length)return '<div class="chart-empty">영업이익률 추이를 계산할 연간 자료가 없습니다.</div>';
 const minY=Math.min(0,...nums),maxY=Math.max(1,...nums),span=maxY-minY||1;const years=pts.map(p=>p.year),minX=Math.min(...years),maxX=Math.max(...years),x=yr=>48+(yr-minX)/Math.max(maxX-minX,1)*400,y=v=>190-(v-minY)/span*150;
 let path='',prev=null;for(const p of pts){if(p.value===null){prev=null;continue;}path+=`${prev!==null&&p.year===prev+1?'L':'M'}${x(p.year)},${y(p.value)} `;prev=p.year;}
 return `<svg class="plot" viewBox="0 0 490 230" role="img" aria-label="연도별 영업이익률. 자료가 없는 연도는 선으로 연결하지 않습니다.">${[0,.5,1].map(t=>{const v=minY+span*t;return `<line x1="48" x2="460" y1="${y(v)}" y2="${y(v)}" stroke="#e7edf4"/><text x="40" y="${y(v)+4}" text-anchor="end">${v.toFixed(1)}%</text>`}).join('')}<path d="${path}" fill="none" stroke="#326acb" stroke-width="2.5"/>${pts.filter(p=>p.value!==null).map(p=>`<circle cx="${x(p.year)}" cy="${y(p.value)}" r="4" fill="#326acb"><title>${p.year}: ${p.value.toFixed(1)}%</title></circle>`).join('')}${years.map(yr=>`<text x="${x(yr)}" y="216" text-anchor="middle">${yr}</text>`).join('')}</svg>`;
}
function barChart(rows,key,med){const items=rows.map(r=>({name:r.name,value:val(r,key)}));if(med!==null)items.push({name:'업종 중앙값',value:med,median:true});const vals=items.map(i=>i.value).filter(isNum);if(!vals.length)return '<div class="chart-empty">비교 가능한 자료가 없습니다.</div>';const lo=Math.min(0,...vals),hi=Math.max(0,...vals),span=hi-lo||1,zero=(0-lo)/span*100;return `<div class="bar-list">${items.map(i=>{const pos=i.value===null?zero:(i.value-lo)/span*100;return `<div class="bar-row"><span class="bar-name" title="${esc(i.name)}">${esc(i.name)}</span><div class="bar-area"><span class="zero-line" style="left:${zero}%"></span>${i.value===null?'':`<span class="bar ${i.median?'median':''}" style="left:${Math.min(zero,pos)}%;width:${Math.abs(pos-zero)}%"></span>`}</div><span class="bar-number">${fmt(i.value,'%')}</span></div>`}).join('')}</div>`;}
function renderComparison(){
 const peers=peerRows(snapshot.companies,comparisonIndustry).sort((a,b)=>a.name.localeCompare(b.name,'ko'));const rows=peers.filter(r=>comparisonCodes.has(r.code));$('compareIndustry').value=comparisonIndustry;
 $('peerScope').textContent=peers.length?`업종: ${comparisonIndustry} · 불러온 동종업계 ${peers.length}개 · 선택기업 ${rows.length}개 · 검색 조건과 독립된 모집단`:'업종 데이터 미연결 · 전체 업종 기준과 선택기업을 함께 비교합니다.';
 $('peerPicker').innerHTML=peers.length?peers.map(r=>`<label class="peer-chip"><input type="checkbox" data-peer="${r.code}" ${comparisonCodes.has(r.code)?'checked':''}>${esc(r.name)}</label>`).join(''):'<span class="muted">실제 기업 자료가 연결되면 비교 기업을 최대 5개 선택할 수 있습니다.</span>';
 $('peerPicker').querySelectorAll('[data-peer]').forEach(el=>el.addEventListener('change',()=>{if(el.checked){if(comparisonCodes.size>=5){el.checked=false;toast('비교는 최대 5개 기업입니다.');return;}comparisonCodes.add(el.dataset.peer);}else comparisonCodes.delete(el.dataset.peer);renderComparison();renderScreen();}));
 const keys=['operating_margin_pct','roe_pct','debt_ratio_pct','interest_coverage_x','foreign_net_turnover_20d_pct','institution_net_turnover_20d_pct','avg_trading_value_20d_eok','current_ratio_pct'];
 $('compareHead').innerHTML='<tr><th class="left">지표</th>'+rows.map(r=>`<th>${esc(r.name)}</th>`).join('')+'<th>업종 중앙값</th><th>유효 표본</th></tr>';
 $('compareBody').innerHTML=keys.map(k=>{const values=peers.map(r=>val(r,k)),m=median(values),n=values.filter(isNum).length;return `<tr><td class="left" title="${esc(METRICS[k].definition)}">${METRICS[k].label} (${METRICS[k].unit})</td>${rows.map(r=>`<td>${fmt(val(r,k))}</td>`).join('')}<td>${fmt(m)}</td><td>${peers.length?n+' / '+peers.length:'—'}</td></tr>`}).join('');
 $('marginCompare').innerHTML=rows.length?barChart(rows,'operating_margin_pct',median(peers.map(r=>val(r,'operating_margin_pct')))):'<div class="chart-empty">비교 기업을 선택하면 표시됩니다.</div>';
 $('flowCompare').innerHTML=rows.length?barChart(rows,'foreign_net_turnover_20d_pct',median(peers.map(r=>val(r,'foreign_net_turnover_20d_pct')))):'<div class="chart-empty">비교 기업을 선택하면 표시됩니다.</div>';
}
function renderAll(){scopeMeta();setIndustries();renderScreen();renderCompany();renderComparison();}
function exportCsv(){if(!lastRows.length){toast('내보낼 결과가 없습니다.');return;}const cols=['code','name','market','industry','status',...Object.keys(METRICS)];const safe=s=>{let t=String(s??'');if(/^[=+@\-]/.test(t)&&!/^[-+]?\d+(\.\d+)?$/.test(t))t="'"+t;return '"'+t.replace(/"/g,'""')+'"'};const lines=[cols,...lastRows.map(({row:r,status:s})=>[r.code,r.name,r.market,r.industry,STATUS[s],...Object.keys(METRICS).map(k=>val(r,k))])];download('screen_results.csv','\uFEFF'+lines.map(a=>a.map(safe).join(',')).join('\r\n'),'text/csv;charset=utf-8');toast('현재 필터 결과만 CSV로 내보냈습니다. 종목코드는 가져오기 시 문자열로 지정하세요.');}
function currentConfig(){return{schema_version:'0.1',logic:$('logic').value,market:$('market').value,industry:$('industry').value,rules:validRules()};}
function importConfig(config){if(!config||!Array.isArray(config.rules)||!['AND','OR'].includes(config.logic))throw new Error('조건 설정 형식이 올바르지 않습니다.');for(const r of config.rules)if(!hasOwn(METRICS,r.metric)||!['gte','lte','gt','lt','eq'].includes(r.op)||!isNum(r.value))throw new Error('조건의 지표·연산·수치가 올바르지 않습니다.');rules=structuredClone(config.rules);$('logic').value=config.logic;$('market').value=['KOSPI','KOSDAQ'].includes(config.market)?config.market:'';$('industry').value=[...$('industry').options].some(o=>o.value===config.industry)?config.industry:'';renderRules();renderScreen();}
$('dataInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>30*1024*1024){toast('파일은 30MB 이하만 지원합니다.');e.target.value='';return;}try{const data=JSON.parse(await file.text());if(data.rules&&!data.companies){importConfig(data);toast('조건 설정 파일을 불러왔습니다.');}else{validateSnapshot(data);snapshot=data;comparisonCodes.clear();companyCode='';comparisonIndustry='';renderAll();toast(`${snapshot.companies.length}개 종목을 불러왔습니다. 원문 수치 검증·자동 연결과는 별개입니다.`);}}catch(err){toast('불러오기 실패: '+err.message);}e.target.value='';});
$('uploadButton').addEventListener('click',()=>$('dataInput').click());$('addRule').addEventListener('click',()=>{if(rules.length>=20){toast('조건은 최대 20개입니다.');return;}rules.push({metric:'roe_pct',op:'gte',value:null});renderRules();});
$('sampleRules').addEventListener('click',()=>{rules=[{metric:'operating_margin_pct',op:'gte',value:8},{metric:'debt_ratio_pct',op:'lte',value:100},{metric:'avg_trading_value_20d_eok',op:'gte',value:20},{metric:'foreign_net_20d_eok',op:'gt',value:0}];$('logic').value='AND';renderRules();renderScreen();toast('조작 확인용 입력 예시입니다. 추천 투자 기준이 아닙니다.');});
$('resetRules').addEventListener('click',()=>{rules=[];$('market').value='';$('industry').value='';$('nameSearch').value='';$('resultStatus').value='';renderRules();renderScreen();});
$('savePreset').addEventListener('click',()=>{const name=$('presetName').value.trim();if(!name){toast('저장할 조건 이름을 입력하세요.');return;}if(name.length>60){toast('조건 이름은 60자 이내로 입력하세요.');return;}Object.defineProperty(savedConfigs,name,{value:currentConfig(),writable:true,enumerable:true,configurable:true});try{localStorage.setItem('investment-screen-presets-v01',JSON.stringify(savedConfigs));renderSaved();toast('이 브라우저에 조건을 저장했습니다. 다른 PC와 자동 동기화되지 않습니다.');}catch{toast('브라우저 저장을 사용할 수 없습니다. 조건 파일로 내보내세요.');}});
$('savedPreset').addEventListener('change',()=>{const name=$('savedPreset').value;if(!name||!hasOwn(savedConfigs,name))return;try{importConfig(savedConfigs[name]);$('presetName').value=name;}catch(err){toast(err.message);}});
$('exportConfig').addEventListener('click',()=>download('screen_conditions.json',JSON.stringify(currentConfig(),null,2)));
$('downloadTemplate').addEventListener('click',()=>download('snapshot_empty.json',JSON.stringify(EMPTY,null,2)));
$('clearData').addEventListener('click',()=>{snapshot=structuredClone(EMPTY);comparisonCodes.clear();companyCode='';comparisonIndustry='';renderAll();toast('현재 화면에서 불러온 데이터를 제거했습니다. 원본 파일은 변경하지 않았습니다.');});
$('exportResults').addEventListener('click',exportCsv);
for(const id of ['market','industry','logic','sortMetric','sortDir','resultStatus'])$(id).addEventListener('change',renderScreen);$('nameSearch').addEventListener('input',renderScreen);
$('companySelect').addEventListener('change',()=>{companyCode=$('companySelect').value;renderCompany();});
$('compareIndustry').addEventListener('change',()=>{comparisonIndustry=$('compareIndustry').value;comparisonCodes.clear();renderComparison();renderScreen();});
$('goCompare').addEventListener('click',()=>activate('compare'));
$('showData').addEventListener('click',()=>activate('data'));
document.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',()=>activate(el.dataset.tab)));
$('sortMetric').innerHTML='<option value="name">기업명</option>'+metricOptions('');
$('definitions').innerHTML=Object.entries(METRICS).map(([k,m])=>`<div class="definition"><div><strong>${esc(m.label)}</strong> <span class="muted">(${m.unit})</span><br><code class="muted">${k}</code></div><p>${esc(m.definition)}</p></div>`).join('');
if(window.INVESTMENT_INITIAL_SNAPSHOT){
 const initial=structuredClone(window.INVESTMENT_INITIAL_SNAPSHOT);
 // The embedded legacy screen supports a subset of the Python metrics.
 for(const row of initial.companies){for(const key of ['metrics','metric_missing_reasons'])if(row[key])row[key]=Object.fromEntries(Object.entries(row[key]).filter(([k])=>hasOwn(METRICS,k)));}
 validateSnapshot(initial);snapshot=initial;
}
window.INVESTMENT_ACTIVATE=activate;
renderRules();renderSaved();renderAll();activate('screen');
