'use strict';
(() => {
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const snap=WORKSPACE_DATA.analysis_snapshot||WORKSPACE_DATA.snapshot, rows=eligible(snap.companies), meta=snap.meta;
const discovery=WORKSPACE_DATA.discovery?.snapshot?.meta?.discovery===true?WORKSPACE_DATA.discovery:null;
const researchSnap=discovery?.snapshot||snap,researchData=discovery?.research||WORKSPACE_DATA.research,researchRows=DiscoveryEngine.prepare(researchSnap,researchData||{});
const allRows=[...rows,...researchRows.filter(r=>!rows.some(c=>c.code===r.code))];
const canUseLegacy=c=>rows.some(r=>r.code===c)&&researchRows.find(r=>r.code===c)?.legacy_available!==false;
let liveReceipt=INVESTMENT_LIVE?.receipt||null;
const handoffKey='investment-live-refresh-handoff';
let handoff=null,restorationNote="";
if(INVESTMENT_LIVE){
  try{handoff=JSON.parse(sessionStorage.getItem(handoffKey)||'null');}catch{}
  sessionStorage.removeItem(handoffKey);
  $('refreshData').hidden=false;
  $('sourceModeHint').textContent='화면을 열 때 저장자료의 최신 여부를 확인합니다. 새로고침은 기존 Infomax 저장자료를 다시 검사합니다.';
}
const specs={...METRICS,per:{label:'PER',unit:'배'},pbr:{label:'PBR',unit:'배'}};
const keys=['market_cap_eok','roe_pct','operating_margin_pct','revenue_growth_pct','debt_ratio_pct','per','pbr'];
const heatKeys=['roe_pct','operating_margin_pct','revenue_growth_pct','debt_ratio_pct'];
const fmt=(v,d=1)=>isNum(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:d}):'—';
const pages=[['시장 대시보드','overview','통합 개요'],['시장 대시보드','prices','관측 가격 이력'],['기업 비교','bars','지표별 데이터바'],['기업 비교','heatmap','기업 × 지표 히트맵'],['기업 비교','scatter','수익성 · 재무 관계'],['기업 분석','screen','조건검색'],['기업 분석','company','기업분석'],['기업 분석','compare','산업비교'],['보유 · 포트폴리오','holdings','보유 입력 · 검토'],['보유 · 포트폴리오','waterfall','평가손익 기여'],['보유 · 포트폴리오','portfolio','포트폴리오 · 시나리오'],['데이터','data','원수치 · 산출 기준']];
pages.unshift(['고급 시각화','advanced','Advanced Visuals'],['기업 발굴','finder','수익성 · 가치 조건검색'],['기업 발굴','watch','관심 기업'],['기업 발굴','sectors','산업별 후보'],['기업 분석','brief','기업 간단 분석'],['기업 분석','trend','추세 확인']);
let page='overview',code=rows[0]?.code||'',frameReady=false,pendingTab='screen';
const researchUI=ResearchUI.create({element:$('research'),snapshot:researchSnap,research:researchData,references:WORKSPACE_DATA.references||{},getCode:()=>code,setCode:c=>{code=c;},go,initial:handoff?.mode===meta.data_mode?handoff.research:undefined});
const advancedUI=AdvancedVisuals.create({element:$('advanced'),snapshot:researchSnap,research:researchData||{},getHoldings:()=>$('detailFrame').contentWindow?.INVESTMENT_GET_HOLDINGS?.(),getPolicy:()=>$('detailFrame').contentWindow?.INVESTMENT_GET_POLICY?.()||{},go:(id,c)=>{if(c)code=c;if(['holdings','portfolio'].includes(id)&&!canUseLegacy(code))code=rows[0]?.code||'';go(id);}});
let group='';$('navigation').innerHTML=pages.map(([g,id,t])=>{let s=g!==group?`<span class="nav-group">${esc(g)}</span>`:'';group=g;return s+`<button class="nav-item" data-page="${id}">${esc(t)}</button>`}).join('');
$('pageSelect').innerHTML=pages.map(([g,id,t])=>`<option value="${id}">${esc(t)}</option>`).join('');
for(const id of ['barMetric','xMetric','yMetric'])$(id).innerHTML=keys.map(k=>`<option value="${k}">${esc(specs[k].label)} (${specs[k].unit})</option>`).join('');
$('barMetric').value='market_cap_eok';$('xMetric').value='roe_pct';$('yMetric').value='operating_margin_pct';
for(const [id,key] of [['viewMarket','market'],['viewIndustry','industry']])$(id).innerHTML+=[...new Set(rows.map(r=>r[key]))].sort().map(v=>`<option>${esc(v)}</option>`).join('');
$('asof').textContent=(discovery?researchSnap.meta.price_date:meta.price_date)||'미연결';$('sideSource').textContent=discovery?`발굴 ${researchRows.length}개 · 기존 분석 ${rows.length}개 · 인포맥스 우선 / 공개자료 보완`:`${meta.data_mode==='fixture'?'가상 테스트':'Infomax 저장자료'} · ${rows.length}개 적격 기업 · ${meta.price_date}`;
$('sourceNotice').textContent=`${meta.data_mode==='fixture'?'가상 테스트 · 실제 관측 아님':'실제 저장 스냅샷 · 새 API 조회 없음'} · 가격 ${meta.price_date} · 재무 ${meta.financial_period} ${meta.financial_basis}`;
$('footerScope').textContent=`가격 ${meta.price_date} · 재무 ${meta.financial_period} ${meta.financial_basis} · 시장 ${meta.venue} · 전체 모집단 ${meta.universe_total??'미확인'}`;
function selected(){const q=$('viewSearch').value.trim().toLowerCase();return rows.filter(r=>(!$('viewMarket').value||r.market===$('viewMarket').value)&&(!$('viewIndustry').value||r.industry===$('viewIndustry').value)&&(!q||r.name.toLowerCase().includes(q)||r.code.includes(q)));}
function scope(){const all=selected();return all.slice(0,30);}
function empty(text){return `<div class="empty"><strong>자료 대기</strong><span>${esc(text)}</span></div>`;}
function companyButton(r){return `<button class="company-link" data-code="${r.code}">${esc(r.name)}<small>${r.code}</small></button>`;}
function bars(rs,key){const valid=rs.filter(r=>isNum(val(r,key))).sort((a,b)=>val(b,key)-val(a,key));if(!valid.length)return empty('선택 지표의 유효한 값이 없습니다.');const lo=Math.min(0,...valid.map(r=>val(r,key))),hi=Math.max(0,...valid.map(r=>val(r,key))),span=hi-lo||1,z=-lo/span*100;return valid.map(r=>{const v=val(r,key),x=(v-lo)/span*100;return `<div class="bar-row">${companyButton(r)}<div class="bar-track"><i style="left:${Math.min(x,z)}%;width:${Math.abs(x-z)}%"></i><em style="left:${z}%"></em></div><span class="bar-value">${fmt(v)}</span></div>`}).join('')+`<p class="psub">유효 ${valid.length}/${rs.length}개 · ${esc(specs[key].unit)} · 막대 길이는 값의 크기</p>`;}
function heat(rs,ks){if(!rs.length)return empty('필터에 맞는 기업이 없습니다.');const ranges=ks.map(k=>{const vs=rs.map(r=>val(r,k)).filter(isNum);return [Math.min(...vs),Math.max(...vs)];});return `<div class="tscroll"><table class="heat"><thead><tr><th>기업</th>${ks.map(k=>`<th>${esc(specs[k].label)}<br>${specs[k].unit}</th>`).join('')}</tr></thead><tbody>${rs.map(r=>`<tr><td>${companyButton(r)}</td>${ks.map((k,i)=>{const v=val(r,k),[lo,hi]=ranges[i],p=v===null?null:hi===lo?.5:(v-lo)/(hi-lo),bg=p===null?'#f1f3f6':`rgb(${Math.round(237-188*p)},${Math.round(245-115*p)},${Math.round(255-9*p)})`;return `<td><button data-code="${r.code}" data-key="${k}" class="${v===null?'missing ':''}${code===r.code?'selected':''}" style="background:${bg};color:${p>.65?'white':'#333d4b'}" title="${esc(r.name+' · '+specs[k].label+': '+fmt(v)+' '+specs[k].unit)}">${fmt(v)}</button></td>`}).join('')}</tr>`).join('')}</tbody></table></div><div class="ramp">선택 기업 내 상대 크기 <span>낮음</span><i></i><span>높음</span></div><p class="psub">셀 숫자는 원값. 지표별 최솟값~최댓값으로 색을 계산하며 동일 값은 중간색입니다. 부채비율도 큰 값이 진합니다. 투자 점수가 아닙니다.</p>`;}
function table(rs){return `<table><thead><tr><th>기업</th>${keys.map(k=>`<th>${esc(specs[k].label)} (${specs[k].unit})</th>`).join('')}</tr></thead><tbody>${rs.map(r=>`<tr><td>${companyButton(r)}</td>${keys.map(k=>`<td>${fmt(val(r,k))}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
function framePlot(content,title){return `<svg class="plot" viewBox="0 0 660 390" role="img" aria-label="${esc(title)}">${content}</svg>`;}
function scatter(rs){const xk=$('xMetric').value,yk=$('yMetric').value,vs=rs.filter(r=>isNum(val(r,xk))&&isNum(val(r,yk)));if(!vs.length)return empty('두 지표가 함께 있는 기업이 없습니다. 결측을 0으로 대체하지 않습니다.');const bounds=k=>{let lo=Math.min(...vs.map(r=>val(r,k))),hi=Math.max(...vs.map(r=>val(r,k))),pad=(hi-lo)*.1||Math.abs(lo)*.1||1;return[lo-pad,hi+pad]};const [xl,xh]=bounds(xk),[yl,yh]=bounds(yk),x=v=>76+(v-xl)/(xh-xl)*550,y=v=>320-(v-yl)/(yh-yl)*285;let svg='';for(let i=0;i<=5;i++){const xx=76+i*110,yy=320-i*57;svg+=`<line class="grid" x1="${xx}" x2="${xx}" y1="35" y2="320"/><line class="grid" x1="76" x2="626" y1="${yy}" y2="${yy}"/><text x="${xx}" y="343" text-anchor="middle">${fmt(xl+(xh-xl)*i/5)}</text><text x="65" y="${yy+4}" text-anchor="end">${fmt(yl+(yh-yl)*i/5)}</text>`;}svg+=vs.map(r=>`<circle role="button" tabindex="0" aria-label="${esc(r.name+' '+r.code)}" class="point ${r.code===code?'selected':''}" data-code="${r.code}" cx="${x(val(r,xk))}" cy="${y(val(r,yk))}" r="8"><title>${esc(r.name)} · ${r.code}\n${esc(specs[xk].label)} ${fmt(val(r,xk))} ${specs[xk].unit}\n${esc(specs[yk].label)} ${fmt(val(r,yk))} ${specs[yk].unit}</title></circle>`).join('');svg+=`<text class="axis-label" x="350" y="375" text-anchor="middle">${esc(specs[xk].label)} (${specs[xk].unit})</text><text class="axis-label" transform="translate(18,180) rotate(-90)" text-anchor="middle">${esc(specs[yk].label)} (${specs[yk].unit})</text>`;return framePlot(svg,'기업별 두 지표 산점도')+`<p class="psub">유효 ${vs.length}/${rs.length}개 · 점 클릭 또는 Enter로 기업 선택 · 표본의 관계이며 인과가 아닙니다.</p>`;}
function observedPrices(r){return (r?.prices||[]).filter(p=>isNum(p.close)&&p.close>0&&p.date<=meta.price_date&&typeof p.final==='boolean'&&Object.hasOwn(p,'venue')&&typeof p.adjustment_basis==='string'&&p.adjustment_basis);}
function price(r){const ps=observedPrices(r);if(!ps.length)return empty('이 기업의 저장된 관측 종가 이력이 없습니다.');const ys=ps.map(p=>p.close),lo=Math.min(...ys),hi=Math.max(...ys),span=hi-lo||1,dates=ps.map(p=>Date.parse(p.date+'T00:00:00Z')),t0=dates[0],td=dates.at(-1)-t0||1,x=i=>ps.length===1?350:76+(dates[i]-t0)/td*550,y=v=>310-(v-lo)/span*260;let out='';for(let i=0;i<=4;i++){const yy=310-i*65;out+=`<line class="grid" x1="76" x2="626" y1="${yy}" y2="${yy}"/><text x="67" y="${yy+4}" text-anchor="end">${fmt(lo+span*i/4,0)}</text>`;}out+=`<path d="${ps.map((p,i)=>(i?'L':'M')+x(i)+','+y(p.close)).join(' ')}" fill="none" stroke="#3182f6" stroke-width="3"/>`+ps.map((p,i)=>`<circle cx="${x(i)}" cy="${y(p.close)}" r="4" fill="#3182f6"><title>${esc(p.date)} · ${fmt(p.close,0)}원</title></circle>`).join('')+`<text x="76" y="346">${ps[0].date}</text><text x="626" y="346" text-anchor="end">${ps.at(-1).date}</text><text x="350" y="375" text-anchor="middle">관측 종가 (원) · ${ps.length}건</text>`;return framePlot(out,'관측 종가 이력');}
function renderFocus(rs){if(!rs.some(r=>r.code===code))code=rs[0]?.code||'';$('focusCompany').innerHTML=rs.map(r=>`<option value="${r.code}">${esc(r.name)} · ${r.code}</option>`).join('');$('focusCompany').value=code;const r=rs.find(r=>r.code===code);$('focusMetrics').innerHTML=r?keys.map(k=>`<div class="focus-row"><span>${esc(specs[k].label)}</span><b>${fmt(val(r,k))} ${specs[k].unit}</b></div>`).join(''):empty('기업을 선택하세요.');}
function updateStatus(rs,total){if(page==='advanced'){$('sourceNotice').textContent=`${researchSnap.meta.data_mode==='fixture'?'가상 테스트 · 실제 관측 아님':'실제 저장자료'} · Advanced 모집단 ${researchRows.length}개 · 기준일 ${researchSnap.meta.price_date||'unknown'} · 검토 상세 ${rows.length}개 · 필터 결과는 아래 표시`;return;}const liveNote=liveReceipt?` · ${liveReceipt.stale?'오래된 자료':'기준일 확인'} · 갱신 ${liveReceipt.status}${liveReceipt.error?' · '+liveReceipt.error:''}`:'';$('sourceNotice').textContent=`${meta.data_mode==='fixture'?'가상 테스트 · 실제 관측 아님':'실제 저장 스냅샷'+(INVESTMENT_LIVE?' · 열 때 최신 자료 확인':' · 새 API 조회 없음')} · 가격 ${meta.price_date} · 재무 ${meta.financial_period} ${meta.financial_basis}${liveNote} · ${$('viewMarket').value||'전체 시장'} / ${$('viewIndustry').value||'전체 산업'}${$('viewSearch').value?' / 검색: '+$('viewSearch').value:''} · 표시 ${rs.length}/${total}개 (최대 30)`+restorationNote;if(researchUI.isPage(page))$('sourceNotice').textContent=(discovery?`기업 발굴 ${researchRows.length}개 · 참고 기준일 ${researchSnap.meta.price_date} · ${researchSnap.meta.discovery_note||'인포맥스 우선 · 네이버 공개 보완자료 · 종목 분류 및 재무 기간·기준 확인 필요'}`:`${meta.data_mode==='fixture'?'가상 테스트 · 실제 관측 아님':'실제 저장 스냅샷'} · 가격 ${meta.price_date} · 재무 ${meta.financial_period} ${meta.financial_basis}${liveNote} · 저장 적격 기업 ${rows.length}개`)+restorationNote;}
function render(){if(page==='advanced'){advancedUI.render();return;}if(researchUI.isPage(page)){researchUI.render(page);updateStatus([],rows.length);return;}const rs=scope(),total=selected().length;renderFocus(rs);updateStatus(rs,total);$('scope').textContent=`표시 ${rs.length}/${total}개 · 최대 30개 · 비교 차트·원수치·CSV에 동일 범위 적용`;$('sourceTable').innerHTML=table(rs);const overviewKeys=['roe_pct','operating_margin_pct','debt_ratio_pct'];if(page==='overview'){$('kpis').innerHTML=[['표시 기업',String(rs.length),'현재 비교 범위'],['ROE 중앙값',fmt(median(rs.map(r=>val(r,'roe_pct'))))+'%','유효 '+rs.filter(r=>val(r,'roe_pct')!==null).length+'개'],['영업이익률 중앙값',fmt(median(rs.map(r=>val(r,'operating_margin_pct'))))+'%','유효 '+rs.filter(r=>val(r,'operating_margin_pct')!==null).length+'개'],['관측 가격 보유',rs.filter(r=>observedPrices(r).length).length+' / '+rs.length,'종가 이력 포함 기업']].map(([l,v,n])=>`<div class="kpi"><span>${l}</span><strong>${v}</strong><small>${n}</small></div>`).join('');$('overviewBars').innerHTML=bars(rs,'market_cap_eok');$('overviewHeat').innerHTML=heat(rs,overviewKeys);$('overviewTable').innerHTML=table(rs);}
const labels={bars:['지표별 데이터바','하나의 지표를 같은 기준선으로 비교합니다.','기업별 '+specs[$('barMetric').value].label,'막대 또는 기업명을 눌러 오른쪽 상세를 확인하세요.'],heatmap:['기업 × 지표 히트맵','같은 보고기간의 재무 지표를 함께 비교합니다.','재무 지표 한눈에','셀 클릭으로 기업을 선택합니다.'],scatter:['수익성 · 재무 관계','선택한 두 지표의 기업별 분포를 살펴봅니다.','두 지표의 관계','X/Y 지표를 바꾸고 기업 점을 선택하세요.'],prices:['관측 가격 이력','선택 기업의 저장된 종가를 확인합니다.','선택 기업의 가격 추이','저장된 날짜를 기준으로 표시하며 가격 이력을 임의 생성하지 않습니다.']};if(labels[page]){const [t,d,c,n]=labels[page];$('exploreTitle').textContent=t;$('exploreDescription').textContent=d;$('chartTitle').textContent=c;$('chartNote').textContent=n;$('barMetric').parentElement.hidden=page!=='bars';for(const id of ['xMetric','yMetric'])$(id).parentElement.hidden=page!=='scatter';$('metricControls').hidden=!['bars','scatter'].includes(page);$('mainChart').innerHTML=page==='bars'?bars(rs,$('barMetric').value):page==='heatmap'?heat(rs,heatKeys):page==='scatter'?scatter(rs):price(rs.find(r=>r.code===code));}
bindCompanies();}
function pick(c,key){code=c;if(page==='overview'){go('heatmap');}else render();$('selectionNote').textContent=(rows.find(r=>r.code===c)?.name||c)+(key?' · '+specs[key].label:'')+' 선택';}
function bindCompanies(){document.querySelectorAll('[data-code]').forEach(el=>{el.addEventListener('click',()=>pick(el.dataset.code,el.dataset.key));if(el.tagName.toLowerCase()==='circle')el.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();pick(el.dataset.code);}});});}
function waterfall(){const data=$('detailFrame').contentWindow?.INVESTMENT_GET_HOLDINGS?.();$('waterfallScope').textContent=data?`${data.mode==='fixture'?'가상 테스트 · 실제 보유 아님':'현재 브라우저의 보유 입력'} · 평가 ${data.as_of}`:'보유 입력 대기';if(!data?.holdings.length){$('waterfallChart').innerHTML=empty('보유 입력 · 검토에서 보유 JSON을 불러오세요.');return;}const pos=PortfolioEngine.reviewHoldings(data).rows;if(pos.some(r=>!isNum(r.cost_krw)||!isNum(r.value_krw))){$('waterfallChart').innerHTML=empty('모든 보유종목의 유효 가격과 매입 원가가 필요합니다.');return;}const start=pos.reduce((s,r)=>s+r.cost_krw,0),end=pos.reduce((s,r)=>s+r.value_krw,0);if(!Number.isSafeInteger(Math.round(start))||!Number.isSafeInteger(Math.round(end))){$('waterfallChart').innerHTML=empty('합계가 안전한 계산 범위를 초과합니다.');return;}const sorted=[...pos].sort((a,b)=>Math.abs(b.pnl_krw)-Math.abs(a.pnl_krw)),drivers=sorted.slice(0,10).map(r=>[r.name+' · '+r.code,r.value_krw-r.cost_krw]);if(sorted.length>10)drivers.push(['그 외 '+(sorted.length-10)+'종목',sorted.slice(10).reduce((s,r)=>s+r.value_krw-r.cost_krw,0)]);let cursor=start,vs=[['주식 원가',0,start,start]];for(const [n,v]of drivers){vs.push([n,cursor,cursor+v,v]);cursor+=v;}vs.push(['주식 평가액',0,end,end]);const lo=Math.min(0,...vs.flatMap(r=>[r[1],r[2]])),hi=Math.max(0,...vs.flatMap(r=>[r[1],r[2]])),span=hi-lo||1,y=v=>285-(v-lo)/span*225,step=550/vs.length;let svg='';for(let i=0;i<=4;i++)svg+=`<line class="grid" x1="70" x2="630" y1="${285-i*56.25}" y2="${285-i*56.25}"/><text x="64" y="${289-i*56.25}" text-anchor="end">${fmt(lo+span*i/4,0)}</text>`;svg+=vs.map(([n,a,b,v],i)=>`<rect x="${76+i*step}" y="${Math.min(y(a),y(b))}" width="${step*.65}" height="${Math.max(1,Math.abs(y(a)-y(b)))}" rx="3" fill="${i===0||i===vs.length-1?'#6b7684':v>=0?'#f06b63':'#3182f6'}"><title>${esc(n)} · ${fmt(v,0)}원</title></rect><text transform="translate(${83+i*step},310) rotate(28)" font-size="10">${esc(n.length>13?n.slice(0,12)+'…':n)}</text>`).join('');$('waterfallChart').innerHTML='<div class="chart-scroll">'+framePlot(svg,'보유 평가손익 워터폴')+'</div>'+`<p class="psub">${fmt(start,0)} + ${fmt(end-start,0)} = ${fmt(end,0)}원 · 이익 빨강 / 손실 파랑 / 합계 회색</p>`;}
function go(id){if(!pages.some(p=>p[1]===id))return;if(['company','holdings','portfolio'].includes(id)&&!canUseLegacy(code)){$('sourceNotice').textContent='선택 기업은 기존 상세·보유 평가용 자료가 연결되지 않았습니다. 기업 발굴·간단 분석·추세 화면에서 확인하세요.';return;}try{sessionStorage.setItem('investment-advanced-open',id==='advanced'?'1':'0');}catch{}window.scrollTo(0,0);page=id;$('pageSelect').value=id;const p=pages.find(p=>p[1]===id);$('workspacePath').textContent=p[0]+' / '+p[2];document.querySelectorAll('.nav-item').forEach(el=>el.setAttribute('aria-current',el.dataset.page===id?'page':'false'));const legacy=['screen','company','compare','holdings','portfolio','data'].includes(id);for(const v of ['overview','explorer','waterfall','legacy','research','advanced'])$(v).hidden=v!==(id==='advanced'?'advanced':researchUI.isPage(id)?'research':legacy?'legacy':id==='overview'||id==='waterfall'?id:'explorer');$('exportCsv').hidden=legacy||['advanced','waterfall','brief','trend'].includes(id);if(legacy){$('legacyTitle').textContent=p[2];pendingTab=id;if(frameReady){const w=$('detailFrame').contentWindow;w.INVESTMENT_ACTIVATE(id);if(id==='company'){const sel=w.document.getElementById('companySelect');if([...sel.options].some(o=>o.value===code)){sel.value=code;sel.dispatchEvent(new Event('change'));}}}}else if(id==='waterfall')waterfall();else render();updateStatus(scope(),selected().length);}
$('detailFrame').addEventListener('load',()=>{frameReady=true;const f=$('detailFrame'),w=f.contentWindow;w.INVESTMENT_ACTIVATE?.(pendingTab);if(handoff?.input&&handoff.mode===meta.data_mode){try{const status=w.INVESTMENT_RESTORE_SESSION(handoff.input,handoff.policy);if(status==='identity_review_needed')restorationNote=' · 보유 입력은 복원했습니다. 종목 식별이 바뀌어 새 가격을 연결하지 않았습니다. 확인하세요.';}catch{ restorationNote=' · 이전 보유 입력 복원 실패 · 내보낸 JSON을 다시 불러오세요.';}}new w.ResizeObserver(()=>{f.style.height=Math.max(700,w.document.body.scrollHeight+30)+'px';}).observe(w.document.body);if(page==='advanced')advancedUI.render();if(page==='waterfall')waterfall();updateStatus(scope(),selected().length);});$('detailFrame').srcdoc=WORKSPACE_DATA.detail_html;
document.querySelectorAll('[data-page]').forEach(el=>el.onclick=()=>go(el.dataset.page));document.querySelectorAll('[data-go]').forEach(el=>el.onclick=()=>go(el.dataset.go));$('pageSelect').onchange=()=>go($('pageSelect').value);
for(const id of ['viewMarket','viewIndustry','barMetric','xMetric','yMetric'])$(id).onchange=render;$('viewSearch').oninput=render;$('focusCompany').onchange=()=>pick($('focusCompany').value);
$('reset').onclick=()=>{for(const id of ['viewMarket','viewIndustry','viewSearch'])$(id).value='';$('barMetric').value='market_cap_eok';$('xMetric').value='roe_pct';$('yMetric').value='operating_margin_pct';code=rows[0]?.code||'';render();};
$('exportCsv').onclick=()=>{if(researchUI.isPage(page)){researchUI.csv();return;}const safe=v=>{let s=String(v??'');if(/^[\s\uFEFF]*[=+@\-]/.test(s)&&!/^[-+]?\d+(\.\d+)?$/.test(s.trim()))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const csv=[['code','name','market','industry','price_date','financial_period',...keys],...scope().map(r=>[r.code,r.name,r.market,r.industry,meta.price_date,meta.financial_period,...keys.map(k=>val(r,k))])].map(r=>r.map(safe).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='investment_comparison.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('refreshData').onclick=async()=>{
  if(!INVESTMENT_LIVE)return;
  const button=$('refreshData');button.disabled=true;button.textContent='확인 중…';
  try{
    const response=await fetch('/refresh',{method:'POST',headers:{'X-Dashboard-Token':INVESTMENT_LIVE.token}});
    if(!response.ok)throw Error('갱신 요청 실패');
    const result=await response.json();liveReceipt=result.receipt;
    if(result.snapshot_id&&result.snapshot_id!==INVESTMENT_LIVE.snapshot_id){
      const w=$('detailFrame').contentWindow;
      const state={mode:meta.data_mode,input:w?.INVESTMENT_GET_HOLDINGS?.(),policy:w?.INVESTMENT_GET_POLICY?.(),
                   page,code,research:researchUI.state(),filters:Object.fromEntries(['viewMarket','viewIndustry','viewSearch','barMetric','xMetric','yMetric'].map(id=>[id,$(id).value]))};
      try{sessionStorage.setItem(handoffKey,JSON.stringify(state));}
      catch{ $('sourceNotice').textContent+=' · 새 자료가 저장됐습니다. 보유 입력을 JSON으로 내보낸 뒤 이 페이지를 다시 열어주세요.';return;}
      location.reload();return;
    }
    render();
  }catch{ $('sourceNotice').textContent+=' · 연결 실패 · 현재 저장자료를 계속 표시합니다.';}
  finally{button.disabled=false;button.textContent='데이터 새로고침';}
};
$('print').onclick=()=>window.print();
if(handoff?.filters){for(const [id,value] of Object.entries(handoff.filters))if($(id)&&[...($(id).options||[])].some(o=>o.value===value)||$(id)?.tagName==='INPUT')$(id).value=value;}
render();
if(handoff?.code&&allRows.some(r=>r.code===handoff.code))code=handoff.code;
let restoreAdvanced=false;try{restoreAdvanced=sessionStorage.getItem('investment-advanced-open')==='1';}catch{}
go(handoff?.page||(restoreAdvanced?'advanced':'finder'));
})();
